<?php

function getConntring() {
	if (!isset($_ENV["CONTAINER"]) || !$_ENV["CONTAINER"]) {
		$con_params = parse_ini_file(__DIR__."/database.ini");

		$_SERVER["DB_HOST"]= $con_params['DB_HOST']; 
		$_SERVER["DB_USER"]= $con_params['DB_USER'];
		$_SERVER["DB_NAME"]= $con_params['DB_NAME'];
		$_SERVER["DB_PASS"]= $con_params['DB_PASS'];
		$_SERVER["DB_PORT"]= $con_params['DB_PORT'];
        $_SERVER["ERROR_REPORTING"]= isset($con_params['ERROR_REPORTING']) ? $con_params['ERROR_REPORTING'] : 0;

        error_reporting((int)$con_params['ERROR_REPORTING']);

		return "host=".$_SERVER['DB_HOST']." port=".$_SERVER['DB_PORT']." dbname=".$_SERVER['DB_NAME']." user=".$_SERVER['DB_USER']." password=".$_SERVER['DB_PASS'];
	} else {
		
		$_SERVER["DB_HOST"]= $_ENV['DB_HOST']; 
		$_SERVER["DB_USER"]= $_ENV['DB_USER'];
		$_SERVER["DB_NAME"]= $_ENV['DB_NAME'];
		$_SERVER["DB_PASS"]= $_ENV['DB_PASS'];
		$_SERVER["DB_PORT"]= $_ENV['DB_PORT'];
        $_SERVER["ERROR_REPORTING"]= isset($_ENV['ERROR_REPORTING']) ? $_ENV['ERROR_REPORTING'] : 0;

        error_reporting((int)$_SERVER["ERROR_REPORTING"]);

		return "host=".$_SERVER['DB_HOST']." port=".$_SERVER['DB_PORT']." dbname=".$_SERVER['DB_NAME']." user=".$_SERVER['DB_USER']." password=".$_SERVER['DB_PASS'];
	}
}

function Conectarse_POSTGRES() {
	$conn_string = getConntring();
	$link = pg_connect($conn_string);
	return $link;
}

function grabar_log_accesos($operacion, $cod_user, $url, $descripcion) {
	$linkPG = Conectarse_POSTGRES();
	if ($operacion=='salida') {
		$sql = "update tab_log_accesos set fecsalida = now(), estado = 0
				where estado = 1 and url='".$url."' cod_user = '".$cod_user."'";
	} else {
		$sql = "update tab_log_accesos set fecsalida = now(), estado = 0
				where estado = 1 and url='".$url."' and cod_user = '".$cod_user."';
				insert into tab_log_accesos (cod_user, fecregistro, url, descripcion, estado)
				values ('".$cod_user."', now(), '".$url."', '".$descripcion."', 1)";
	}
	$rs = pg_query( $linkPG , $sql);
}

?> 
