
<?php

if (isset($_GET['excel']) && ($_GET['excel']=='excel')){
	header("Content-type:application/x-msexcel");
	$file=$_GET['capa'];
	header("Content-Disposition: attachment; filename=".$file.".xls");
	$imgtitulo='';
} else{
	$imgtitulo='<img src="imajes/desplegable.png" width="11" height="11">';
}

/*@session_start();
	if(empty($_SESSION['usuario'])){
        header('Location: ../index.php');
	}else{$cod_user = $_SESSION['usuario'];}*/
	include ('conexion_postgres.phtml');
	include ('injection/funciones.php');
	$player = 	limpiarCadena($_GET['olayer']);
	$pcampo = 	limpiarCadena($_GET['ocampo']);
	$pvalor = limpiarCadena(limpiarNumeros($_GET['ovalor']));
	$linkPG = Conectarse_POSTGRES();
	// Browse Data
	$sQueryS = "SELECT *";
	$sQueryF = " FROM vw_peru_actores_sociales";
	$sQueryW = " WHERE gid = '" . $pvalor . "'";

    

	$sQuery = $sQueryS . $sQueryF . $sQueryW;
    $rsDet = pg_query( $linkPG , $sQuery );
    $ambito = pg_fetch_result($rsDet,0,"\"cod_nivel\"");
	$titulo_ventana = pg_fetch_result($rsDet,0,"\"tipo\"").' - Actores Sociales - '.pg_fetch_result($rsDet,0,"\"nivel\"");
	$titulo = pg_fetch_result($rsDet,0,"\"tipo\"").' - Actores Sociales - '.pg_fetch_result($rsDet,0,"\"nivel\"");
	include ('inc/consulta_cabecera.php');
?>
<table width="100%" border="0" cellspacing="0" cellpadding="10">
  <tr><td>
	<table width="100%" class="marco_general">
	  <tr><td>
		<table width="100%" class="marco_individual">
		  <tr>
			<td>
				<table width="100%" class="titulo_general">
				  <tr>
					<td>&nbsp;&nbsp;UBICACI&Oacute;N GEOGR&Aacute;FICA</td>
				  </tr>
                </table>
                <?php if ($ambito == 3) { ?>
				<table width='100%' align='center' class='general'>
					<thead>
					  <tr>
						<th width='25%'>Departamento</th>
						<th width='25%'>Provincia</th>
						<th width='25%'>Distrito</th>
						<th width='25%'>Codigo Distrito</th>
					  </tr>
					</thead>
					<tbody>
					<tr>
						<td align='center' class='texto'><?php echo(pg_fetch_result($rsDet,0,"\"nom_dpto\"")) ?></td>
						<td align='center' class='texto'><?php echo(pg_fetch_result($rsDet,0,"\"nom_prov\"")) ?></td>
						<td align='center' class='texto'><?php echo(pg_fetch_result($rsDet,0,"\"nom_dist\"")) ?></td>
						<td align='center' class='texto'><?php echo(pg_fetch_result($rsDet,0,"\"cod_dist\"")) ?></td>
					</tr>
	
					</tbody>
                </table>
                <?php } else if ($ambito == 9) {?>

                    <table width='100%' align='center' class='general'>
					<thead>
					  <tr>
						<th width='25%'>País</th>
					  </tr>
					</thead>
					<tbody>
					<tr>
						<td align='center' class='texto'>PERÚ</td>
					</tr>
	
					</tbody>
                </table>

                <?php } else if ($ambito == 1) {?>

                    <table width='100%' align='center' class='general'>
					<thead>
					  <tr>
                        <th width='25%'>Departamento</th>
                        <th width='25%'>Ubigeo</th>
					  </tr>
					</thead>
					<tbody>
					<tr>
                        <td align='center' class='texto'><?php echo(pg_fetch_result($rsDet,0,"\"nom_dpto\"")) ?></td>
                        <td align='center' class='texto'><?php echo(pg_fetch_result($rsDet,0,"\"cod_dpto\"")) ?></td>
					</tr>
	
					</tbody>
                </table>

                <?php } else if ($ambito == 2) {?>
                    
                    <table width='100%' align='center' class='general'>
					<thead>
					  <tr>
						<th width='25%'>Departamento</th>
                        <th width='25%'>Provincia</th>
                        <th width='25%'>Ubigeo</th>
					  </tr>
					</thead>
					<tbody>
					<tr>
						<td align='center' class='texto'><?php echo(pg_fetch_result($rsDet,0,"\"nom_dpto\"")) ?></td>
                        <td align='center' class='texto'><?php echo(pg_fetch_result($rsDet,0,"\"nom_prov\"")) ?></td>
                        <td align='center' class='texto'><?php echo(pg_fetch_result($rsDet,0,"\"cod_prov\"")) ?></td>
					</tr>
	
					</tbody>
                </table>
                
                <?php } else if ($ambito == 4) {?>

                    <table width='100%' align='center' class='general'>
					<thead>
					  <tr>
						<th width='20%'>Departamento</th>
                        <th width='20%'>Provincia</th>
                        <th width='20%'>Distrito</th>
                        <th width='20%'>Centro Poblado</th>
                        <th width='20%'>Ubigeo</th>
					  </tr>
					</thead>
					<tbody>
					<tr>
						<td align='center' class='texto'><?php echo(pg_fetch_result($rsDet,0,"\"nom_dpto\"")) ?></td>
                        <td align='center' class='texto'><?php echo(pg_fetch_result($rsDet,0,"\"nom_prov\"")) ?></td>
                        <td align='center' class='texto'><?php echo(pg_fetch_result($rsDet,0,"\"nom_dist\"")) ?></td>
                        <td align='center' class='texto'><?php echo(pg_fetch_result($rsDet,0,"\"nom_ccpp\"")) ?></td>
                        <td align='center' class='texto'><?php echo(pg_fetch_result($rsDet,0,"\"cod_ccpp\"")) ?></td>
					</tr>
	
					</tbody>
                </table>
                <?php } ?>
			</td>
		  </tr>
		</table>
		<br>
		<table width="100%" class="marco_individual">
		  <tr>
			<td>
				<table width="100%" class="titulo_general">
					  <tr>
						<td>&nbsp;&nbsp;DATOS GENERALES</td>
					  </tr>
				</table>
			<table width='100%' align='center' class='general'>
		<?php
        print "
        <tr>
        <td width='50%' class='lista_titulo'>Apellidos y nombres del actor social</td>
        <td width='50%' class='texto1'>".pg_fetch_result($rsDet,0,"\"ape_nom\"")."</td>
      </tr>
        <tr>
				<td width='50%' class='lista_titulo'>Cargo</td>
				<td width='50%' class='texto1'>".pg_fetch_result($rsDet,0,"\"cargo\"")."</td>
			  </tr>
			  <tr>
				<td class='lista_titulo'>Organización</td>
                <td class='texto1'>".pg_fetch_result($rsDet,0,"\"org\"")."</td>
			  </tr>
			  <tr>
				<td class='lista_titulo'>¿Tiene vínculo con alguna organización radical?</td>
				<td class='texto1'>".pg_fetch_result($rsDet,0,"\"vo\"")."</td>
              </tr>
              <tr>
                <td class='lista_titulo'>Nombre de la organización radical</td>
                <td class='texto1'>".pg_fetch_result($rsDet,0,"\"si\"")."</td>
              </tr>
              <tr>
                <td class='lista_titulo'>¿Tiene vínculo constante con alguna ONG?</td>
                <td class='texto1'>".pg_fetch_result($rsDet,0,"\"vc\"")."</td>
              </tr>

              <tr>
                <td class='lista_titulo'>Nombre de la ONG con la cual tiene vínculo constante</td>
                <td class='texto1'>".pg_fetch_result($rsDet,0,"\"cual\"")."</td>
              </tr>

              <tr>
                <td class='lista_titulo'>Apreciación del nivel de influencia</td>
               <td class='texto1'>".pg_fetch_result($rsDet,0,"\"an\"")."</td>
              </tr>

              <tr>
                <td class='lista_titulo'>¿Tiene antecedentes electorales?</td>
                <td class='texto1'>".pg_fetch_result($rsDet,0,"\"ae\"")."</td>
              </tr>

              <tr>
                <td class='lista_titulo'>¿Qué cargo electoral presenta y en qué año?</td>
                <td class='texto1'>".pg_fetch_result($rsDet,0,"\"scc\"")."</td>
              </tr>

              

			";
		?>
			</table>
			</td>
		  </tr>
		</table>
		<br>
		
		<table class='fuente_general' width="100%"><thead><tr><th><b>Fuente:</b>
			<br><?php echo pg_fetch_result($rsDet,0,"\"fuente\"");?></th></tr></thead>
		</table>
	<?php
	//$name=strtoupper(pg_fetch_result($rsDet,0,"\"tipoaerona\"").' - '.pg_fetch_result($rsDet,0,"\"label\""));
	$name=pg_fetch_result($rsDet,0,"\"tipo\"").' - Actores Sociales - '.pg_fetch_result($rsDet,0,"\"nivel\"");
	$capa='consulta_actores_sociales';
	if (!isset($_GET['excel'])) {
		$ruta=$capa.'.phtml?excel=excel&capa='.$capa.'&ovalor='.$pvalor.'&olayer=peru_actores_sociales'.'&ocampo=gid';
		include 'inc/consulta_pie.php';
	}
	if (isset($_SESSION['usuario'])) {
		grabar_log_accesos('ingreso', $cod_user, $name, $descripcion);
	}
	?>
		</td>
	  </tr>
	</table>
	</td>
  </tr>
</table>
</body>
</html>
<?php include_once("./analyticstracking.php");?>


