<?php

if (isset($_GET['excel']) && ($_GET['excel']=='excel')) {
	header("Content-type:application/x-msexcel");
	$file=$_GET['capa'];
	header("Content-Disposition: attachment; filename=".$file.".xls");
	$imgtitulo='';
} else {
	$imgtitulo='<img src="imajes/desplegable.png" width="11" height="11">';
}

/*@session_start();
	if(empty($_SESSION['usuario'])){
        header('Location: ../index.php');
	}else{$cod_user = $_SESSION['usuario'];}*/
	include ('conexion_postgres.phtml');
	include ('injection/funciones.php');
	$player = 	limpiarCadena($_GET['olayer']);
	$pcampo = 	limpiarCadena($_GET['ocampo']);
	$gid = limpiarNumeros($_GET['ovalor']);
	
	$linkPG = Conectarse_POSTGRES(); 
	// Browse Data
	$sQueryS = " SELECT *  ";   
	$sQueryF = " FROM vw_peru_cuota_empleo_gob_region_2022";
	$sQueryW = " WHERE gid = '" . $gid. "'";
	$sQuery = $sQueryS . $sQueryF . $sQueryW;
	$rsDet = pg_query( $linkPG , $sQuery );
	$titulo_ventana = 'CUMPLIMIENTO DE LA CUOTA DE EMPLEO (5%) - GOBIERNOS REGIONALES';
	$titulo = $titulo_ventana;
	
	
	include ('inc/consulta_cabecera.php');
?>
<table width="100%" border="0" cellspacing="0" cellpadding="10">
		<br>
		<table width="100%" class="marco_individual">
		  <tr>
			<td>
			<table width="100%" class="titulo_general">
			  <tr>
				<td>&nbsp;&nbsp;CUMPLIMIENTO DE LA CUOTA DE EMPLEO (5%) - GOBIERNOS REGIONALES</td>
			  </tr>
			</table>
			<table align='center' width="100%" class="listado" >
			
<?php

		//EMPRESA ENTEL
		print "<tr>";
		print "<td width='50%' class='lista_titulo' colspan='3' ><b >Nombre del Gobierno Regional</b></td>";
		print "<td class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"entidades\"")."</td>";
		print "</tr>";

		print "<tr>";
		print "<td width='50%' class='lista_titulo' colspan='3' ><b >Total de Trabajadores</b></td>";
		print "<td class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"tot_trab\"")."</td>";
		print "</tr>";

		print "<tr>";
		print "<td width='50%' class='lista_titulo' colspan='3' ><b >Total de Personas con Discapacidad</b></td>";
		print "<td class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"tot_pcd\"")."</td>";
		print "</tr>";

		print "<tr>";
		print "<td width='50%' class='lista_titulo' colspan='3' ><b >% de Cumplimiento</b></td>";
		print "<td class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"p_cumplim\"")."%</td>";
		print "</tr>";

		print "<tr>";
		print "<td width='50%' class='lista_titulo' colspan='3' ><b >Total de Personas con Discapacidad faltantes</b></td>";
		print "<td class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"tot_pcd_f\"")."</td>";
		print "</tr>";

		print "<tr>";
		print "<td width='50%' class='lista_titulo' colspan='3' ><b >% Faltante al cumplimiento del 5%</b></td>";
		print "<td class='lista_textosub'>".number_format(pg_fetch_result($rsDet,0,"\"p_falt_cu5\""),2)."%</td>";
		print "</tr>";

		print "<tr>";
		print "<td width='50%' class='lista_titulo' colspan='3' ><b >Total de Personas con Discapacidad del género Masculino</b></td>";
		print "<td class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"pcd_mas\"")."</td>";
		print "</tr>";

		print "<tr>";
		print "<td width='50%' class='lista_titulo' colspan='3' ><b >Total de Personas con Discapacidad del género Femenino</b></td>";
		print "<td class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"pcd_fem\"")."</td>";
		print "</tr>";

		print "<tr>";
		print "<td width='50%' class='lista_titulo' colspan='3' ><b >Total de Personas con Discapacidad del Régimen Laboral del Decreto Legislativo N° 276</b></td>";
		print "<td class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"pcd_dl276\"")."</td>";
		print "</tr>";

		print "<tr>";
		print "<td width='50%' class='lista_titulo' colspan='3' ><b >Total de Personas con Discapacidad del Régimen Laboral del Decreto Legislativo N° 728</b></td>";
		print "<td class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"pcd_dl728\"")."</td>";
		print "</tr>";

		print "<tr>";
		print "<td width='50%' class='lista_titulo' colspan='3' ><b >Total de Personas con Discapacidad del Régimen Laboral (CAS)</b></td>";
		print "<td class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"pcd_cas\"")."</td>";
		print "</tr>";

		print "<tr>";
		print "<td width='50%' class='lista_titulo' colspan='3' ><b >Total de Personas con Discapacidad con otro Régimen Laboral</b></td>";
		print "<td class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"pcd_otro\"")."</td>";
		print "</tr>";

		print "<tr>";
		print "<td width='50%' class='lista_titulo' colspan='3' ><b >Total de Entidades Fiscalizadas</b></td>";
		print "<td class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"t_ent_fisc\"")."</td>";
		print "</tr>";

		print "<tr>";
		print "<td width='50%' class='lista_titulo' colspan='3' ><b >N° de entidades que SI dan Cumplimiento de la Cuota de Empleo (5%)</b></td>";
		print "<td class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"cu_ce5_si\"")."</td>";
		print "</tr>";

		print "<tr>";
		print "<td width='50%' class='lista_titulo' colspan='3' ><b >N° de entidades que NO dan Cumplimiento de la Cuota de Empleo (5%)</b></td>";
		print "<td class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"cu_ce5_no\"")."</td>";
		print "</tr>";

		print "<tr>";
		print "<td width='50%' class='lista_titulo' colspan='3' ><b >N° de entidades que NO enviaron información</b></td>";
		print "<td class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"no_env_inf\"")."</td>";
		print "</tr>";
	
	?>
			</table>
		</table>
		<br>
		<table class='fuente_general' width="100%"><thead><tr><th><b>Fuente:</b>
			<br><?php echo(pg_fetch_result($rsDet,0,"\"fuente\"")); ?>
		</th></tr></thead></table>
	<?php
	$name='Segun Regiones';
	$capa='peru_cuota_empleo_gob_region_2022';
	if (!isset($_GET['excel'])) {
		$ruta='consulta_cuota_empleo_segun_regiones.phtml?excel=excel&capa='.$capa.'&ovalor='.$gid;
		include 'inc/consulta_pie.php';
	}
	if (isset($_SESSION['usuario'])) {
		grabar_log_accesos('ingreso', $cod_user, $name, $descripcion);
	}
	?>
</td></tr>
	</table>
	</td></tr>
</table>
</body>

</html>


<?php include_once("./analyticstracking.php");?>
