
<?php

if (isset($_GET['excel']) && ($_GET['excel']=='excel')){
	header("Content-type:application/x-msexcel");
	$file=$_GET['capa'];
	header("Content-Disposition: attachment; filename=".$file.".xls");
	$imgtitulo='';
} else{
	$imgtitulo='<img src="imajes/desplegable.png" width="11" height="11">';
}

/*@session_start();
	if(empty($_SESSION['usuario'])){
        header('Location: ../index.php');
	}else{$cod_user = $_SESSION['usuario'];}*/
	include ('conexion_postgres.phtml');
	include ('injection/funciones.php');
	$player = limpiarCadena($_GET['olayer']);
	$pcampo = limpiarCadena($_GET['ocampo']);
	$pvalor = limpiarNumeros($_GET['ovalor']);
	$linkPG = Conectarse_POSTGRES();
    // Browse Data
    // select pec.cod_des_op, pec.tot_vot,pec.desc_op, pd.cod_dist, pd.nom_dist, pd.cod_prov , pd.nom_prov, pd.cod_dpto, pd.nom_dpto,pd.the_geom from peru_elecciones_congresales pec
	//   	inner join peru_distritos pd on pd.cod_dist = pec.cod_dist where pd.cod_dist = '010101';
	$sQueryS = "select * FROM";
	$sQueryF = " peru_poblacion_electoral";
	$sQueryW = "  where gid = '" . $pvalor . "'";

	$sQuery = $sQueryS . $sQueryF . $sQueryW;
	$rsDet = pg_query( $linkPG , $sQuery );
	$titulo_ventana = 'Población Electoral';
	$titulo = 'Población Electoral';
	include ('inc/consulta_cabecera.php');
?>
<table width="100%" border="0" cellspacing="0" cellpadding="10">
  <tr><td>
	<table width="100%" class="marco_general">
	  <tr><td>
		<table width="100%" class="marco_individual">
		  <!--tr>
			<td>
				<table width="100%" class="titulo_general">
				  <tr>
					<td>&nbsp;&nbsp;UBICACI&Oacute;N GEOGR&Aacute;FICA</td>
				  </tr>
				</table>
				<table width='100%' align='center' class='general'>
					<thead>
					  <tr>
						<th width='25%'>Departamento</th>
						<th width='25%'>Provincia</th>
						<th width='25%'>Distrito</th>
						<th width='25%'>Codigo Distrito</th>
					  </tr>
					</thead>
					<tbody>
					<tr>
						<td align='center' class='texto'><?php echo(pg_fetch_result($rsDet,0,"\"nom_dpto\"")) ?></td>
						<td align='center' class='texto'><?php echo(pg_fetch_result($rsDet,0,"\"nom_prov\"")) ?></td>
						<td align='center' class='texto'><?php echo(pg_fetch_result($rsDet,0,"\"nom_dist\"")) ?></td>
						<td align='center' class='texto'><?php echo(pg_fetch_result($rsDet,0,"\"cod_dist\"")) ?></td>
					</tr>
	
					</tbody>
				</table>
			</td>
		  </tr-->
		</table>
		<br>
		<table width="100%" class="marco_individual">
		  <tr>
			<td>
				<table width="100%" class="titulo_general">
					  <tr>
						<td>&nbsp;&nbsp;DATOS GENERALES</td>
					  </tr>
				</table>
			<table width='100%' align='center' class='general'>
            
		<?php
			
					print "
					<tr>
						<td width='50%' class='lista_titulo'>Distrito</td>
						<td width='50%' class='texto1'>".pg_fetch_result($rsDet,0,"\"nom_dist\"")."</td>
					</tr>
					<tr>
						<td width='50%' class='lista_titulo'>Población Electoral Total</td>
						<td width='50%' class='texto1'>".number_format(pg_fetch_result($rsDet,0,"\"tot\""),0)."</td>
					</tr>
					<tr>
						<td width='50%' class='lista_titulo'>Población Electoral Hombres</td>
						<td width='50%' class='texto1'>".number_format(pg_fetch_result($rsDet,0,"\"hom\""),0)."</td>
					</tr>
					<tr>
						<td width='50%' class='lista_titulo'>Población Electoral Mujeres</td>
						<td width='50%' class='texto1'>".number_format(pg_fetch_result($rsDet,0,"\"muj\""),0)."</td>
					</tr>
					<tr>
						<td width='50%' class='lista_titulo'>Población Electoral de 18 a 30 años</td>
						<td width='50%' class='texto1'>".number_format(pg_fetch_result($rsDet,0,"\"tot_18_30\""),0)."</td>
					</tr>

					<tr>
						<td width='50%' class='lista_titulo'>Población Electoral Hombres de 18 a 30 años</td>
						<td width='50%' class='texto1'>".number_format(pg_fetch_result($rsDet,0,"\"hom_18_30\""),0)."</td>
					</tr>

					<tr>
						<td width='50%' class='lista_titulo'>Población Electoral Mujeres de 18 a 30 años</td>
						<td width='50%' class='texto1'>".number_format(pg_fetch_result($rsDet,0,"\"muj_18_30\""),0)."</td>
					</tr>
					<tr>
						<td width='50%' class='lista_titulo'>Población Electoral de 30 a 59 años</td>
						<td width='50%' class='texto1'>".number_format(pg_fetch_result($rsDet,0,"\"tot_30_59\""),0)."</td>
					</tr>
					<tr>
						<td width='50%' class='lista_titulo'>Población Electoral Hombres de 30 a 59 años</td>
						<td width='50%' class='texto1'>".number_format(pg_fetch_result($rsDet,0,"\"hom_30_59\""),0)."</td>
					</tr>


					<tr>
						<td width='50%' class='lista_titulo'>Población Electoral Mujeres de 30 a 59 años</td>
						<td width='50%' class='texto1'>".number_format(pg_fetch_result($rsDet,0,"\"muj_30_59\""),0)."</td>
					</tr>

					<tr>
						<td width='50%' class='lista_titulo'>Población Electoral de 60 años a más</td>
						<td width='50%' class='texto1'>".number_format(pg_fetch_result($rsDet,0,"\"tot_60m\""),0)."</td>
					</tr>

					<tr>
						<td width='50%' class='lista_titulo'>Población Electoral Hombres de 60 años a más</td>
						<td width='50%' class='texto1'>".number_format(pg_fetch_result($rsDet,0,"\"hom_60m\""),0)."</td>
					</tr>

					<tr>
						<td width='50%' class='lista_titulo'>Población Electoral Mujeres de 60 años a más</td>
						<td width='50%' class='texto1'>".number_format(pg_fetch_result($rsDet,0,"\"muj_60m\""),0)."</td>
					</tr>
					";
			
       
		?>
			</table>
			</td>
		  </tr>
		</table>
		<br>
		
		<table class='fuente_general' width="100%"><thead><tr><th><b>Fuente:</b>
			<br><?php echo pg_fetch_result($rsDet,0,"\"fuente\"");?></th></tr></thead>
		</table>
	<?php
	//$name=strtoupper(pg_fetch_result($rsDet,0,"\"tipoaerona\"").' - '.pg_fetch_result($rsDet,0,"\"label\""));
	$name='Población Electoral';
	$capa='consulta_elecciones_congresales';
	if (!isset($_GET['excel'])) {
		$ruta=$capa.'.phtml?excel=excel&capa='.$capa.'&ovalor='.$pvalor.'&olayer=peru_actores_politicos'.'&ocampo=gid';
		include 'inc/consulta_pie.php';
	}
	if (isset($_SESSION['usuario'])) {
		grabar_log_accesos('ingreso', $cod_user, $name, $descripcion);
	}
	?>
		</td>
	  </tr>
	</table>
	</td>
  </tr>
</table>
</body>
</html>
<?php include_once("./analyticstracking.php");?>


