<?php

if (isset($_GET['excel']) && ($_GET['excel']=='excel')) {
	header("Content-type:application/x-msexcel");
	$file=$_GET['capa'];
	header("Content-Disposition: attachment; filename=".$file.".xls");
	$imgtitulo='';
} else {
	$imgtitulo='<img src="imajes/desplegable.png" width="11" height="11">';
}

/*@session_start();
	if(empty($_SESSION['usuario'])){
        header('Location: ../index.php');
		}else{$cod_user = $_SESSION['usuario'];}*/
	include ('conexion_postgres.phtml');
	include ('injection/funciones.php');
	$player = limpiarCadena($_GET['olayer']);
	$pcampo = limpiarCadena($_GET['ocampo']);
    $pvalor = limpiarNumeros($_GET['ovalor']);
	$linkPG = Conectarse_POSTGRES();
	// Browse Data
	$sQueryS = "SELECT *";
	//$sQueryF = " FROM peru_comisarias";
	$sQueryF = " FROM peru_puntos_estrategicos_ucloud";
	$sQueryW = " WHERE \"gid\" = '" . $pvalor . "'";

	$sQuery = $sQueryS . $sQueryF . $sQueryW;
	$rsDet = pg_query( $linkPG , $sQuery );
	$titulo_ventana = 'Puntos Estratégicos Ucloud-Net';
	$titulo = $titulo_ventana;
	include ('inc/consulta_cabecera.php');
?>
<table width="100%" border="0" cellspacing="0" cellpadding="10">
  <tr><td>
	<table width="100%" class="marco_general">
	  <tr><td>
		<table width="100%" class="marco_individual">
		  <tr>
			<td>
			<table width="100%" class="titulo_general">
			  <tr>
				<td>&nbsp;&nbsp;UBICACI&Oacute;N GEOGR&Aacute;FICA</td>
			  </tr>
			</table>
			<table width='100%' align='center' class='general'>
				<thead>
				<?php print" <tr>
					<th width='25%'>DEPARTAMENTO</th>
					<th width='25%'>PROVINCIA</th>
					<th width='25%'>DISTRITO</th>
					<th width='25%'>CÓDIGO DISTRITO</th>
				  </tr>";?>
				</thead>
				<tbody>
	<?php
			print "<tr>
					<td align='center' class='texto'>".pg_fetch_result($rsDet,0,"\"nom_dpto\"")."</td>
					<td align='center' class='texto'>".pg_fetch_result($rsDet,0,"\"nom_prov\"")."</td>
					<td align='center' class='texto'>".pg_fetch_result($rsDet,0,"\"nom_dist\"")."</td>
					<td align='center' class='texto'>".pg_fetch_result($rsDet,0,"\"cod_dist\"")."</td>
				  </tr>";
	?>
				</tbody>
			</table>
			</td>
		  </tr>
		</table>
		<br>
        <table width="100%" border="0" cellspacing="0" style="padding-left: 20px; padding-right: 20px">
  <tbody><tr>
	<td>
	<table width="100%" cellspacing="0" cellpadding="1" class="marco_reporte">
	  <tbody><tr>
		<td>
		<table width="100%" cellpadding="10" cellspacing="0">
		  <tbody><tr>
			<td colspan="7" class="titulo_reporte" style="font-size:20px;">Datos de Puntos Estratégicos Ucloud-Net</td>
		  </tr>
		</tbody></table>
	  </td></tr>
	</tbody></table>
  </td></tr>
</tbody></table>
<br>


		<table width="100%" class="marco_individual">
		  <tr>
			<td>
			<table width="100%" class="listado">
	<?php
		print "<tr>
				<td width='50%' class='lista_titulo'>Nombre de centro poblado: </td>
				<td width='50%' class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"nom_ccpp\"")."</td>
			  </tr>
			  <tr>
				<td class='lista_titulo'>Población censada (Hab.): </td>
				<td class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"pob_tot17\"")."</td>
			  </tr>
			  <tr>
				<td class='lista_titulo'>Altitud del centro poblado en msnm: </td>
				<td class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"altitud\"")."</td>
              </tr>
              <tr>
				<td class='lista_titulo'>¿El centro poblado contiene la sede municipal?: </td>
				<td class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"municipio\"")."</td>
			  </tr>
			<tr>
			  <td class='lista_titulo'>¿El centro poblado dispone de alguna institución educativa cercana?: </td>
			  <td class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"inst_educ\"")."</td>
			</tr>
			<tr>
				<td class='lista_titulo'>¿El centro poblado dispone de algún local comunal cercano?: </td>
				<td class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"comunal\"")."</td>
			</tr>
			<tr>
				<td class='lista_titulo'>¿El centro poblado dispone de alguna biblioteca cercana?: </td>
				<td class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"biblioteca\"")."</td>
			</tr>
			<tr>
				<td class='lista_titulo'>¿El centro poblado dispone de algún Tambo (Programa PAIS) cercano?: </td>
				<td class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"tambo\"")."</td>
			</tr>
			<tr>
				<td class='lista_titulo'>Número de viviendas sin alumbrado eléctrico en el centro poblado: </td>
				<td class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"vs_aelec\"")."</td>
			</tr>
			<tr>
                <td class='lista_titulo'>% de viviendas sin alumbrado eléctrico en el centro poblado: </td>
                <td class='lista_textosub'>".number_format(pg_fetch_result($rsDet,0,"\"pvs_aelec\""),2)."</td>
            </tr>
            <tr>
                <td class='lista_titulo'>Población Distrital (Hab.): </td>
                <td class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"pob_dist20\"")."</td>
            </tr>
            <tr>
                <td class='lista_titulo'>Número de hogares sin internet en el distrito: </td>
                <td class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"hs_inter\"")."</td>
            </tr>
            <tr>
                <td class='lista_titulo'>% de hogares sin internet en el distrito: </td>
                <td class='lista_textosub'>".number_format(pg_fetch_result($rsDet,0,"\"phs_inter\""),2)."</td>
            </tr>
            <tr>
                <td class='lista_titulo'>Número de hogares sin computadora, laptop o tablet en el distrito: </td>
                <td class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"hs_pclptb\"")."</td>
            </tr>
            <tr>
                <td class='lista_titulo'>% de hogares sin computadora, laptop o tablet en el distrito: </td>
                <td class='lista_textosub'>".number_format(pg_fetch_result($rsDet,0,"\"phs_pclptb\""),2)."</td>
            </tr>

            
			
			<tr>
                <td class='lista_titulo'>Número de hogares sin teléfono celular en el distrito: </td>
                <td class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"hs_tcelu\"")."</td>
			</tr>
			
			<tr>
                <td class='lista_titulo'>% de hogares sin teléfono celular en el distrito: </td>
                <td class='lista_textosub'>".number_format(pg_fetch_result($rsDet,0,"\"phs_tcelu\""),2)."</td>
			</tr>
			
			<tr>
                <td class='lista_titulo'>Incidencia de Pobreza Distrital 2018: </td>
                <td class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"pobr18_dis\"")."</td>
            </tr>
			";
	    ?>
			</table>
			</td>
		  </tr>
		</table>

		<br>

		<table class='fuente_general' width="100%"><thead><tr><th><b>Fuente:</b>
			<br><?php echo(pg_fetch_result($rsDet,0,"\"fuente\"")); ?>
		</th></tr></thead></table>
	<?php
	$name='Datos de Puntos Estratégicos Ucloud-Net';
	$capa='consulta_puntos_estrategicos_ucloud';
	if (!isset($_GET['excel'])) {
		$ruta=$capa.'.phtml?excel=excel&capa='.$capa.'&ovalor='.$pvalor.'&olayer=puntos_estrategicos_ucloud'.'&ocampo=gid';
		
		include 'inc/consulta_pie.php';
	}
	if (isset($_SESSION['usuario'])) {
		grabar_log_accesos('ingreso', $cod_user, $name, $descripcion);
	}
	?>
		</td></tr>
	</table>
	</td></tr>
</table>
</body>
</html>
<?php include_once("./analyticstracking.php");?>
