<?php
/***************************************************************************************
Organización: 	Presidencia del Consejo de Ministros - PCM
Gerencia	: 	Secretaría de Descentralización
Sistema		: 	Sistema Nacional de Información Geográfica - SAYWITE
Coordinador/Desarrollador TIC: Vitaly Uriel Cespedes Reynaga vitalyuri@hotmail.com/vitalyuri@gmail.com/969228151
Periodo		: 	Septiembre 2012 - 2013
***************************************************************************************/

if (isset($_GET['excel']) && ($_GET['excel']=='excel')) {
	header("Content-type:application/x-msexcel");
	$file=$_GET['capa'];
	header("Content-Disposition: attachment; filename=".$file.".xls");
	$imgtitulo='';
} else {
	$imgtitulo='<img src="imajes/desplegable.png" width="11" height="11">';
}

// @session_start();
// 	if(empty($_SESSION['usuario'])){
//         header('Location: ../index.php');
// 		}else{$cod_user = $_SESSION['usuario'];}
	
	include ('conexion_postgres.phtml');
	
	include ('injection/funciones.php');
	
	set_time_limit(1000);		
	$player = limpiarCadena($_GET['olayer']);
	$pcampo = limpiarCadena($_GET['ocampo']);
	$pvalor = limpiarCadena(limpiarNumeros($_GET['ovalor']));
	$linkPG = Conectarse_POSTGRES(); 

	$gid = $pvalor;
	// Browse Data
	$sQueryS = "SELECT *";   
	$sQueryF = " FROM plan_acondic_territorial_mayo2022";
	$sQueryW = " WHERE \"gid\" = '" . $gid . "'";

	$sQuery = $sQueryS . $sQueryF . $sQueryW;   
	$rsDet = pg_query( $linkPG , $sQuery );
	$titulo_ventana = 'PLAN DE ACONDICIONAMIENTO TERRITORIAL (PAT)';
	$titulo = 'Plan de Acondicionamiento Territorial (PAT)';
	include ('inc/consulta_cabecera.php');
?>
<table width="100%" border="0" cellspacing="0" cellpadding="10">
  <tr><td>
	<table width="100%" class="marco_general">
	  <tr><td>
		<table class="marco_individual">
		  <tr>
			<td>
				<div id="u1" style="width: 100%;">
					<h1><table width="100%" class="titulo_general">
						  <tr>
							<td><?php echo $imgtitulo;?>&nbsp;&nbsp;UBICACI&Oacute;N GEOGR&Aacute;FICA</td>
						  </tr>
						</table></h1>
					<div>
						<table width='100%' align='center' class='general'>
							<thead>
							  <tr>
								<th width='20%'>Departamento</th>
								<th width='20%'>Provincia</th>
								<th width='20%'>C&oacute;digo Provincia</th>
							  </tr>
							</thead>
						<tbody>
				<?php
					print "<tr>
							<td align='center' class='texto'>".pg_fetch_result($rsDet,0,"\"nom_dpto\"")."</td>
							<td align='center' class='texto'>".pg_fetch_result($rsDet,0,"\"nom_prov\"")."</td>
							<td align='center' class='texto'>".pg_fetch_result($rsDet,0,"\"cod_prov\"")."</td>
						   </tr>";
				?>
						</tbody>
						</table>
					</div>
				</div>
			</td>
		  </tr>
		</table>
		<br>
		<table width="100%" class="marco_individual">
		  <tr>
			<td>
				<div id="u2" style="width: 100%;">
					<h1><table width="100%" class="titulo_general">
						  <tr>
							<td><?php echo $imgtitulo;?>&nbsp;&nbsp;DATOS DE PLAN DE ACONDICIONAMIENTO TERRITORIAL</td>
						  </tr>
						</table></h1>
					<div>
						<table width='100%' align='center' class='listado'>
		  <?php
		  		print "<tr>";
				print "<td width='50%' class='lista_titulo'>Tipo de Asistencia Técnica</td>";
		  		print "<td width='50%' class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"tipo_as_tc\"")."&nbsp;</td>";
				print "</tr>";
		  		print "<tr>";
				print "<td width='50%' class='lista_titulo'>Año del PAT</td>";
		  		print "<td width='50%' class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"anio_pat\"")."&nbsp;</td>";
				print "</tr>";
		  		print "<tr>";
				print "<td class='lista_titulo'>Vigencia de Plan de Acondicionamiento Territorial (PAT)</td>";
				print "<td class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"vigenc_pat\"")."&nbsp;</td>";
		  		print "</tr>";
				print "<tr>";
				print "<td class='lista_titulo'>Dispositivo Legal</td>";
				print "<td class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"disp_legal\"")."&nbsp;</td>";
		  		print "</tr>";
				print "<tr>";
				print "<td class='lista_titulo'>Fuente de Plan de Acondicionamiento Territorial (PAT)</td>";
				print "<td class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"fuente_pat\"")."&nbsp;</td>";
		  		print "</tr>";
				print "<tr >";
				print "<td class='lista_titulo'>Área en hectáreas</td>";
				print "<td class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"area_ha\"")."&nbsp;</td>";
		  		print "</tr>";
				print "<tr >";
				print "<td class='lista_titulo'>Total de Poblacion 2017</td>";
				print "<td class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"pob_2017\"")."&nbsp;</td>";
		  		print "</tr>";
				print "<tr >";
				print "<td class='lista_titulo'>Fecha de actualización del registro</td>";
				print "<td class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"fec_act_re\"")."&nbsp;</td>";
		  		print "</tr>";
		  		print "</tr>";
				print "<tr >";
				print "<td class='lista_titulo'>Observación</td>";
				print "<td class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"obs\"")."&nbsp;</td>";
		  		print "</tr>";
	
?>
						</table>
					</div>
				</div>
			</td>
		  </tr>
		</table>

	
<?php 
	if(getComDesc($player)!=''){
			include ('inc/descarga.php');	
	}
		?><br>
		<table class='fuente_general' width="100%"><thead><tr><th><b>Fuente:</b>
			<br><?php echo pg_fetch_result($rsDet,0,"\"fuente\"");?>
			</th></tr></thead>
		</table>
	<?php
	$name=strtoupper('PLAN DE ACONDICIONAMIENTO TERRITORIAL ');
	$capa='consulta_info_gl_pat';
	if (!isset($_GET['excel'])) {
		//$ruta=$capa.'.phtml?excel=excel&capa='.$capa.'&ovalor='.$pvalor;
		$ruta=$capa.'.phtml?excel=excel&capa='.$capa.'&ovalor='. $pvalor.'&olayer='.$player.'&niv_descarga='.$niv_descarga.'&descarga='.$descarga;
		include 'inc/consulta_pie.php';
	}
	if (isset($_SESSION['usuario'])) {
		grabar_log_accesos('ingreso', $cod_user, $name, $descripcion);
	}
	
	pg_close($linkPG);
	?>
		</td></tr>
	</table>
	</td></tr>
</table>
</body>

<script language="javascript" type="text/javascript">
	$(document).ready(function(){
		$("#u1").h2c_acordeon();
		$("#u2").h2c_acordeon();
		$("#u3").h2c_acordeon();
		$("#u4").h2c_acordeon();
		$("#u5").h2c_acordeon();
		$("#u6").h2c_acordeon();
	});
</script>

</html>