
<?php

if (isset($_GET['excel']) && ($_GET['excel']=='excel')){
	header("Content-type:application/x-msexcel");
	$file=$_GET['capa'];
	header("Content-Disposition: attachment; filename=".$file.".xls");
	$imgtitulo='';
} else{
	$imgtitulo='<img src="imajes/desplegable.png" width="11" height="11">';
}

/*@session_start();
	if(empty($_SESSION['usuario'])){
        header('Location: ../index.php');
	}else{$cod_user = $_SESSION['usuario'];}*/
	include ('conexion_postgres.phtml');
	include ('injection/funciones.php');
	$player = 	limpiarCadena($_GET['olayer']);
	$pcampo = 	limpiarCadena($_GET['ocampo']);
	$pvalor = limpiarCadena(limpiarNumeros($_GET['ovalor']));
	$linkPG = Conectarse_POSTGRES();
	// Browse Data
	$sQueryS = "SELECT *";
	$sQueryF = " FROM vw_peru_seguciu_adolesinfra_infrac_distrito_cjdr";
	$sQueryW = " WHERE gid = '" . $pvalor . "'";

	$sQuery = $sQueryS . $sQueryF . $sQueryW;
	$rsDet = pg_query( $linkPG , $sQuery );
	$titulo_ventana = 'INFRACCIONES POR DISTRITO SEGÚN CJDR';
	$titulo = 'INFRACCIONES POR DISTRITO SEGÚN CJDR';
	include ('inc/consulta_cabecera.php');
?>
<table width="100%" border="0" cellspacing="0" cellpadding="10">
  <tr><td>
	<table width="100%" class="marco_general">
	  <tr><td>
		<table width="100%" class="marco_individual">
		  <!--tr>
			<td>
				<table width="100%" class="titulo_general">
				  <tr>
					<td>&nbsp;&nbsp;UBICACI&Oacute;N GEOGR&Aacute;FICA</td>
				  </tr>
				</table>
				<table width='100%' align='center' class='general'>
					<thead>
					  <tr>
						<th width='25%'>Departamento</th>
						<th width='25%'>Provincia</th>
						<th width='25%'>Distrito</th>
						<th width='25%'>Codigo Distrito</th>
					  </tr>
					</thead>
					<tbody>
					<tr>
						<td align='center' class='texto'><?php echo(pg_fetch_result($rsDet,0,"\"nom_dpto\"")) ?></td>
						<td align='center' class='texto'><?php echo(pg_fetch_result($rsDet,0,"\"nom_prov\"")) ?></td>
						<td align='center' class='texto'><?php echo(pg_fetch_result($rsDet,0,"\"nom_dist\"")) ?></td>
						<td align='center' class='texto'><?php echo(pg_fetch_result($rsDet,0,"\"cod_dist\"")) ?></td>
					</tr>
	
					</tbody>
				</table>
			</td>
		  </tr-->
		</table>
		<br>
		<table width="100%" class="marco_individual">
		  <tr>
			<td>
				<table width="100%" class="titulo_general">
					  <tr>
						<td>&nbsp;&nbsp;DATOS GENERALES</td>
					  </tr>
					  
				</table>

				<table width='100%' align='center' class='general'>
		<?php
        print "
        		<tr>
				<td width='50%' class='lista_titulo'>Total de infracciones por actos contra el pudor</td>
				<td width='50%' class='texto1'>".pg_fetch_result($rsDet,0,"\"act_pudor\"")."</td>
				</tr>

				<tr>
				<td width='50%' class='lista_titulo'>Total de infracciones por asociación ilícita</td>
				<td width='50%' class='texto1'>".pg_fetch_result($rsDet,0,"\"asoc_ilic\"")."</td>
			  	</tr>

        		<tr>
				<td width='50%' class='lista_titulo'>Total de infracciones por banda criminal</td>
				<td width='50%' class='texto1'>".pg_fetch_result($rsDet,0,"\"banda_crim\"")."</td>
				</tr>

				<tr>
				<td width='50%' class='lista_titulo'>Total de infracciones por exposición a peligro o abandono a personas en peligro</td>
				<td width='50%' class='texto1'>".pg_fetch_result($rsDet,0,"\"exp_pelig\"")."</td>
			  	</tr>

        		<tr>
				<td width='50%' class='lista_titulo'>Total de infracciones por extorsión</td>
				<td width='50%' class='texto1'>".pg_fetch_result($rsDet,0,"\"extorsion\"")."</td>
				</tr>

				<tr>
				<td width='50%' class='lista_titulo'>Total de infracciones por feminicidio</td>
				<td width='50%' class='texto1'>".pg_fetch_result($rsDet,0,"\"feminicid\"")."</td>
			  	</tr>

        		<tr>
				<td width='50%' class='lista_titulo'>Total de infracciones por homicidio calificado</td>
				<td width='50%' class='texto1'>".pg_fetch_result($rsDet,0,"\"hom_calif\"")."</td>
				</tr>

				<tr>
				<td width='50%' class='lista_titulo'>Total de infracciones por homicidio simple</td>
				<td width='50%' class='texto1'>".pg_fetch_result($rsDet,0,"\"hom_simple\"")."</td>
			  	</tr>

        		<tr>
				<td width='50%' class='lista_titulo'>Total de infracciones por hurto agravado</td>
				<td width='50%' class='texto1'>".pg_fetch_result($rsDet,0,"\"hurto_agra\"")."</td>
				</tr>

				<tr>
				<td width='50%' class='lista_titulo'>Total de infracciones por lesiones graves</td>
				<td width='50%' class='texto1'>".pg_fetch_result($rsDet,0,"\"les_graves\"")."</td>
			  	</tr>

        		<tr>
				<td width='50%' class='lista_titulo'>Total de infracciones por lesiones leves</td>
				<td width='50%' class='texto1'>".pg_fetch_result($rsDet,0,"\"les_leves\"")."</td>
				</tr>

				<tr>
				<td width='50%' class='lista_titulo'>Total de infracciones por marcaje o reglaje</td>
				<td width='50%' class='texto1'>".pg_fetch_result($rsDet,0,"\"marc_regl\"")."</td>
			  	</tr>

        		<tr>
				<td width='50%' class='lista_titulo'>Total de infracciones por parricidio</td>
				<td width='50%' class='texto1'>".pg_fetch_result($rsDet,0,"\"parricidio\"")."</td>
				</tr>

				<tr>
				<td width='50%' class='lista_titulo'>Total de infracciones por robo</td>
				<td width='50%' class='texto1'>".pg_fetch_result($rsDet,0,"\"robo\"")."</td>
			  	</tr>

        		<tr>
				<td width='50%' class='lista_titulo'>Total de infracciones por robo agravado</td>
				<td width='50%' class='texto1'>".pg_fetch_result($rsDet,0,"\"robo_agrav\"")."</td>
				</tr>

				<tr>
				<td width='50%' class='lista_titulo'>Total de infracciones por secuestro</td>
				<td width='50%' class='texto1'>".pg_fetch_result($rsDet,0,"\"secuestro\"")."</td>
			  	</tr>

        		<tr>
				<td width='50%' class='lista_titulo'>Total de infracciones por sicariato</td>
				<td width='50%' class='texto1'>".pg_fetch_result($rsDet,0,"\"sicariato\"")."</td>
				</tr>

				<tr>
				<td width='50%' class='lista_titulo'>Total de infracciones por tenencia ilegal de armas</td>
				<td width='50%' class='texto1'>".pg_fetch_result($rsDet,0,"\"ten_ile_ar\"")."</td>
			  	</tr>

        		<tr>
				<td width='50%' class='lista_titulo'>Total de infracciones por trafico Ilícito de drogas</td>
				<td width='50%' class='texto1'>".pg_fetch_result($rsDet,0,"\"tra_ili_dr\"")."</td>
				</tr>

				<tr>
				<td width='50%' class='lista_titulo'>Total de infracciones por trata de personas</td>
				<td width='50%' class='texto1'>".pg_fetch_result($rsDet,0,"\"tra_perso\"")."</td>
			  	</tr>

        		<tr>
				<td width='50%' class='lista_titulo'>Total de infracciones por violación sexual</td>
				<td width='50%' class='texto1'>".pg_fetch_result($rsDet,0,"\"vio_sexual\"")."</td>
				</tr>

				<tr>
				<td width='50%' class='lista_titulo'>Total de infracciones por violacion sexual de menor de edad</td>
				<td width='50%' class='texto1'>".pg_fetch_result($rsDet,0,"\"vio_sex_ed\"")."</td>
			  	</tr>

        		<tr>
				<td width='50%' class='lista_titulo'>Total de infracciones por violencia y resistencia a la autoridad</td>
				<td width='50%' class='texto1'>".pg_fetch_result($rsDet,0,"\"vio_res_au\"")."</td>
				</tr>

				<tr>
				<td width='50%' class='lista_titulo'>Total de infracciones por otros tipos de delitos</td>
				<td width='50%' class='texto1'>".pg_fetch_result($rsDet,0,"\"otros\"")."</td>
			  	</tr>

        		<tr>
				<td width='50%' class='lista_titulo'>Total de infracciones producidas a nivel distrital</td>
				<td width='50%' class='texto1'>".pg_fetch_result($rsDet,0,"\"total_inf\"")."</td>
				</tr>


			";
		?>
			</table>
			</td>
		  </tr>
		</table>
		<br>
		
		<table class='fuente_general' width="100%"><thead><tr><th><b>Fuente:</b>
			<br><?php echo pg_fetch_result($rsDet,0,"\"fuente\"");?></th></tr></thead>
		</table>
	<?php
	//$name=strtoupper(pg_fetch_result($rsDet,0,"\"tipoaerona\"").' - '.pg_fetch_result($rsDet,0,"\"label\""));
	$name='INFRACCIONES POR DISTRITO SEGÚN CJDR';
	$capa='INFRACCIONES POR DISTRITO SEGÚN CJDR';
	if (!isset($_GET['excel'])) {
		$ruta=$capa.'.phtml?excel=excel&capa='.$capa.'&ovalor='.$pvalor.'&olayer=peru_discapacidad_regiones'.'&ocampo=gid';
		include 'inc/consulta_pie.php';
	}
	if (isset($_SESSION['usuario'])) {
		grabar_log_accesos('ingreso', $cod_user, $name, $descripcion);
	}
	?>
		</td>
	  </tr>
	</table>
	</td>
  </tr>
</table>
</body>
</html>
<?php include_once("./analyticstracking.php");?>