<?php

if (isset($_GET['excel']) && ($_GET['excel']=='excel')) {
	header("Content-type:application/x-msexcel");
	$file=$_GET['capa'];
	header("Content-Disposition: attachment; filename=".$file.".xls");
	$imgtitulo='';
} else {
	$imgtitulo='<img src="imajes/desplegable.png" width="11" height="11">';
}

/*@session_start();
	if(empty($_SESSION['usuario'])){
        header('Location: ../index.php');
	}else{$cod_user = $_SESSION['usuario'];}*/
	include ('conexion_postgres.phtml');
	include ('injection/funciones.php');
	$player = 	limpiarCadena($_GET['olayer']);
	$pcampo = 	limpiarCadena($_GET['ocampo']);
	$gid = limpiarNumeros($_GET['ovalor']);
	
	$linkPG = Conectarse_POSTGRES(); 
	// Browse Data
	$sQueryS = " SELECT *  ";   
	$sQueryF = " FROM peru_internet_movil_movistar";
	$sQueryW = " WHERE gid = '" . $gid. "'";
	$sQuery = $sQueryS . $sQueryF . $sQueryW;
	$rsDet = pg_query( $linkPG , $sQuery );
	$titulo_ventana = 'INTERNET M&Oacute;VIL MOVISTAR ';
	$titulo = $titulo_ventana;
	
	
	include ('inc/consulta_cabecera.php');
?>
<table width="100%" border="0" cellspacing="0" cellpadding="10">
  <tr><td>
	<table width="100%" class="marco_general">
	  <tr><td>
		<table width="100%" class="marco_individual">
		  <tr>
			<td>
			<table width="100%" class="titulo_general">
			  <tr>
				<td>&nbsp;&nbsp;UBICACI&Oacute;N GEOGR&Aacute;FICA</td>
			  </tr>
			</table>
			<table width='100%' align='center' class='general'>
				<thead>
				  <tr>
					<th width='25%'>Departamento</th>
					<th width='25%'>Provincia</th>
					<th width='25%'>Distrito</th>
					<th width='25%'>Centro Poblado</th>
					<th width='25%'>Código CCPP</th>
				  </tr>
				</thead>
				<tbody>
<?php
		print "<tr>
				<td align='center' class='texto'>".pg_fetch_result($rsDet,0,"\"nom_dpto\"")."</td>
				<td align='center' class='texto'>".pg_fetch_result($rsDet,0,"\"nom_bprov\"")."</td>
				<td align='center' class='texto'>".pg_fetch_result($rsDet,0,"\"nombdist\"")."</td>
				<td align='center' class='texto'>".pg_fetch_result($rsDet,0,"\"ccpp\"")."</td>
				<td align='center' class='texto'>".pg_fetch_result($rsDet,0,"\"cod_ccpp\"")."</td>
			  </tr>";
?>
				</tbody>
			</table>
			</td>
		  </tr>
		</table>
		<br>
		<table width="100%" class="marco_individual">
		  <tr>
			<td>
			<table width="100%" class="titulo_general">
			  <tr>
				<td>&nbsp;&nbsp;FORMA DE MEDICIÓN</td>
			  </tr>
			</table>
			<table align='center' width="100%" class="listado" >
			
<?php

		//EMPRESA ENTEL
		print "<tr>";
		print "<td width='50%' class='lista_titulo' colspan='3' ><b >En campo</b></td>";
		print "<td class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"campo\"")."</td>";
		print "</tr>";

		print "<tr>";
		print "<td width='50%' class='lista_titulo' colspan='3' ><b >En gabinete</b></td>";
		print "<td class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"gabinete\"")."</td>";
		print "</tr>";
	
	?>
			</table>
			
			</br>
			</br>
			<table width="100%" class="titulo_general">
			   <tr>
				<td align=''>&nbsp;&nbsp;TECNOLOGÍA</td>
			  </tr>
			</table>
						<table width="100%" class="listado">
<?php
		//EMPRESA ENTEL
		print "<tr>";
		print "<td width='50%' class='lista_titulo' colspan='3' ><b >GSM</b></td>";
		print "<td class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"gsm\"")."</td>";
		print "</tr>";

		print "<tr>";
		print "<td width='50%' class='lista_titulo' colspan='3' ><b >GPRS</b></td>";
		print "<td class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"gprs\"")."</td>";
		print "</tr>";

		print "<tr>";
		print "<td width='50%' class='lista_titulo' colspan='3' ><b >EDGE</b></td>";
		print "<td class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"edge\"")."</td>";
		print "</tr>";

		print "<tr>";
		print "<td width='50%' class='lista_titulo' colspan='3' ><b >UMTS</b></td>";
		print "<td class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"umts\"")."</td>";
		print "</tr>";

		print "<tr>";
		print "<td width='50%' class='lista_titulo' colspan='3' ><b >HSDPA</b></td>";
		print "<td class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"hsdpa\"")."</td>";
		print "</tr>";

		print "<tr>";
		print "<td width='50%' class='lista_titulo' colspan='3' ><b >HSUPA</b></td>";
		print "<td class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"hsupa\"")."</td>";
		print "</tr>";

		print "<tr>";
		print "<td width='50%' class='lista_titulo' colspan='3' ><b >HSPA+</b></td>";
		print "<td class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"hspa\"")."</td>";
		print "</tr>";

		print "<tr>";
		print "<td width='50%' class='lista_titulo' colspan='3' ><b >WIMAX</b></td>";
		print "<td class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"wimax\"")."</td>";
		print "</tr>";

		print "<tr>";
		print "<td width='50%' class='lista_titulo' colspan='3' ><b >IDEN</b></td>";
		print "<td class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"iden\"")."</td>";
		print "</tr>";

		print "<tr>";
		print "<td width='50%' class='lista_titulo' colspan='3' ><b >LTE</b></td>";
		print "<td class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"lte\"")."</td>";
		print "</tr>";

		print "<tr>";
		print "<td width='50%' class='lista_titulo' colspan='3' ><b >LTE CA</b></td>";
		print "<td class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"lte_ca\"")."</td>";
		print "</tr>";

		print "<tr>";
		print "<td width='50%' class='lista_titulo' colspan='3' ><b >CDMA</b></td>";
		print "<td class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"cdma\"")."</td>";
		print "</tr>";

	
	?>
			</table>
			</td>
		  </tr>
		</table>
		<table width="100%" class="marco_individual">
		  <tr>
			<td>
			<table width="100%" class="titulo_general">
			  <tr>
				<td>&nbsp;&nbsp;SERVICIOS</td>
			  </tr>
			</table>
			<table align='center' width="100%" class="listado" >
			
<?php

//EMPRESA MOVISTAR	
		// 2G INICIO
		print "<tr>";
		print "<td align='center' width='50%' class='lista_titulo center' colspan='3'><b >Telefonía Móvil</b></td>";
		print "<td align='center' width='50%' class='lista_titulo center' colspan='2'><b >Telefonía Fija</b></td>";
		print "<td align='center' width='50%' class='lista_titulo center' colspan='2'><b >Acceso Internet Móvil</b></td>";
		print "<td align='center' width='50%' class='lista_titulo center' colspan=''><b ></b></td>";
		print "</tr>";

		print "<tr>";
		print "<td align='center' width='15%' class='lista_titulo center' ><b >Mensaje de voz</b></td>";

		print "<td align='center' width='15%' class='lista_titulo center' ><b >Mensaje de Texto</b></td>";

		print "<td align='center' width='15%' class='lista_titulo center' ><b >Mensaje Mutimedia</b></td>";

		print "<td align='center' width='15%' class='lista_titulo center' ><b >Abonados</b></td>";

		print "<td align='center' width='15%' class='lista_titulo center' ><b >Teléfono de uso público</b></td>";

		print "<td align='center' width='15%' class='lista_titulo center' ><b >Banda Estrecha X Mbps</b></td>";

		print "<td align='center' width='15%' class='lista_titulo center' ><b >Banda Ancha X Mbps</b></td>";

		print "<td align='center' width='10%' class='lista_titulo center' ><b >Otro</b></td>";

		print "</tr>";

		print "<tr>";
		print "<td class='lista_textosub center'>".pg_fetch_result($rsDet,0,"\"voz\"")."</td>";
		print "<td class='lista_textosub center'>".pg_fetch_result($rsDet,0,"\"sms\"")."</td>";
		print "<td class='lista_textosub center'>".pg_fetch_result($rsDet,0,"\"mms\"")."</td>";
		print "<td class='lista_textosub center'>".pg_fetch_result($rsDet,0,"\"abonados\"")."</td>";
		print "<td class='lista_textosub center'>".pg_fetch_result($rsDet,0,"\"tup\"")."</td>";
		print "<td class='lista_textosub center'>".pg_fetch_result($rsDet,0,"\"ba_es_mbps\"")."</td>";
		print "<td class='lista_textosub center'>".pg_fetch_result($rsDet,0,"\"ba_an_mbps\"")."</td>";
		print "<td class='lista_textosub center'>".pg_fetch_result($rsDet,0,"\"otro\"")."</td>";
		print "</tr>";
		// 2G FIN
	?>
			</table>
			</br>
			</br>

		<br>
		<table class='fuente_general' width="100%"><thead><tr><th><b>Fuente:</b>
			<br><?php echo(pg_fetch_result($rsDet,0,"\"fuente\"")); ?>
		</th></tr></thead></table>
	<?php
	$name='Internet Movil Movistar';
	$capa='peru_internet_movil_movistar';
	if (!isset($_GET['excel'])) {
		$ruta='consulta_telefonia_movil.phtml?excel=excel&capa='.$capa.'&ovalor='.$gid;
		include 'inc/consulta_pie.php';
	}
	if (isset($_SESSION['usuario'])) {
		grabar_log_accesos('ingreso', $cod_user, $name, $descripcion);
	}
	?>
</td></tr>
	</table>
	</td></tr>
</table>
</body>

</html>


<?php include_once("./analyticstracking.php");?>
