<?php

if (isset($_GET['excel']) && ($_GET['excel']=='excel')) {
	header("Content-type:application/x-msexcel");
	$file=$_GET['capa'];
	header("Content-Disposition: attachment; filename=".$file.".xls");
	$imgtitulo='';
} else {
	$imgtitulo='<img src="imajes/desplegable.png" width="11" height="11">';
}

/*@session_start();
	if(empty($_SESSION['usuario'])){
        header('Location: ../index.php');
	}else{$cod_user = $_SESSION['usuario'];}*/
	include ('conexion_postgres.phtml');
	include ('injection/funciones.php');
	// $player = 	limpiarCadena($_GET['olayer']);
	// $pcampo = 	limpiarCadena($_GET['ocampo']);
	$gid = limpiarNumeros($_GET['id']);
	
	$linkPG = Conectarse_POSTGRES(); 
	// Browse Data
	$sQueryS = " SELECT *  ";   
	$sQueryF = " FROM peru_pip_pb_anios";
	$sQueryW = " WHERE gid = '" . $gid. "'";
	$sQuery = $sQueryS . $sQueryF . $sQueryW;
	$rsDet = pg_query( $linkPG , $sQuery );
	$titulo_ventana = 'Proyectos en Ejecución - Plan Binacional';
	$titulo = $titulo_ventana;
	
	
	include ('inc/consulta_cabecera.php');
?>
<table width="100%" border="0" cellspacing="0" cellpadding="10">
  <tr><td>
	<table width="100%" class="marco_general">
	  <tr><td>
		<table width="100%" class="marco_individual">
		  <tr>
			<td>
	

			</td>
		  </tr>
		</table>
		<br>
		<table width="100%" class="marco_individual">
		  <tr>
			<td>
			<table width="100%" class="titulo_general">
			  <tr>
				<td>&nbsp;&nbsp;Proyectos en Ejecución - Plan Binacional</td>
			  </tr>
			</table>
			<table align='center' width="100%" class="listado" >
			
<?php
		print "<tr>";
		print "<td width='50%' class='lista_titulo' colspan='3' ><b >Nombre del departamento</b></td>";
		print "<td class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"nom_dpto\"")."</td>";
		print "</tr>";

		print "<tr>";
		print "<td width='50%' class='lista_titulo' colspan='3' ><b >Nombre de provincia</b></td>";
		print "<td class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"nom_prov\"")."</td>";
		print "</tr>";


		print "<tr>";
		print "<td width='50%' class='lista_titulo' colspan='3' ><b >Nombre de distrito</b></td>";
		print "<td class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"nom_dist\"")."</td>";
		print "</tr>";


		print "<tr>";
		print "<td width='50%' class='lista_titulo' colspan='3' ><b >Localidad</b></td>";
		print "<td class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"localidad\"")."</td>";
		print "</tr>";
		print "<tr>";
		print "<td width='50%' class='lista_titulo' colspan='3' ><b >Código</b></td>";
		print "<td class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"codigo\"")."</td>";
		print "</tr>";

		print "<tr>";
		print "<td width='50%' class='lista_titulo' colspan='3' ><b >Año de Suscripción</b></td>";
		print "<td class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"anio\"")."</td>";
		print "</tr>";

		print "<tr>";
		print "<td width='50%' class='lista_titulo' colspan='3' ><b >Nombre del Proyecto</b></td>";
		print "<td class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"proyecto\"")."</td>";
		print "</tr>";

	



		print "<tr>";
		print "<td width='50%' class='lista_titulo' colspan='3' ><b >Ejecutor</b></td>";
		print "<td class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"ejecutor\"")."</td>";
		print "</tr>";

		print "<tr>";
		print "<td width='50%' class='lista_titulo' colspan='3' ><b >Financiamiento Soles FB</b></td>";
		print "<td class='lista_textosub'>".number_format(pg_fetch_result($rsDet,0,"\"fs_fb\""),0)."</td>";
		print "</tr>";

		print "<tr>";
		print "<td width='50%' class='lista_titulo' colspan='3' ><b >Financiamiento Soles Otros</b></td>";
		print "<td class='lista_textosub'>".number_format(pg_fetch_result($rsDet,0,"\"fs_otros\""),0)."</td>";
		print "</tr>";

		print "<tr>";
		print "<td width='50%' class='lista_titulo' colspan='3' ><b >Financiamiento Soles Total</b></td>";
		print "<td class='lista_textosub'>".number_format(pg_fetch_result($rsDet,0,"\"fs_total\""),0)."</td>";
		print "</tr>";	

		print "<tr>";
		print "<td width='50%' class='lista_titulo' colspan='3' ><b >N° Beneficiarios</b></td>";
		print "<td class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"beneficiar\"")."</td>";
		print "</tr>";	

		print "<tr>";
		print "<td width='50%' class='lista_titulo' colspan='3' ><b >Longitud</b></td>";
		print "<td class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"x_coord\"")."</td>";
		print "</tr>";
		
		print "<tr>";
		print "<td width='50%' class='lista_titulo' colspan='3' ><b >Latitud</b></td>";
		print "<td class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"y_coord\"")."</td>";
		print "</tr>";	
	?>
			
		<br>
		<table class='fuente_general' width="100%"><thead><tr><th><b>Fuente:</b>
			<br><?php echo(pg_fetch_result($rsDet,0,"\"fuente\"")); ?>
		</th></tr></thead></table>
	<?php
	$name='Proyectos de Ejecucion';
	$capa='pb_proyectos_ejecucion';
	if (!isset($_GET['excel'])) {
		$ruta='consulta_telefonia_movil.phtml?excel=excel&capa='.$capa.'&ovalor='.$gid;
		include 'inc/consulta_pie.php';
	}
	if (isset($_SESSION['usuario'])) {
		grabar_log_accesos('ingreso', $cod_user, $name, $descripcion);
	}
	?>
</td></tr>
	</table>
	</td></tr>
</table>
</body>

</html>


<?php include_once("./analyticstracking.php");?>
