
<?php

if (isset($_GET['excel']) && ($_GET['excel']=='excel')){
	header("Content-type:application/x-msexcel");
	$file=$_GET['capa'];
	header("Content-Disposition: attachment; filename=".$file.".xls");
	$imgtitulo='';
} else{
	$imgtitulo='<img src="imajes/desplegable.png" width="11" height="11">';
}

/*@session_start();
	if(empty($_SESSION['usuario'])){
        header('Location: ../index.php');
	}else{$cod_user = $_SESSION['usuario'];}*/
	include ('conexion_postgres.phtml');
	include ('injection/funciones.php');
	$player = limpiarCadena($_GET['olayer']);
	$pcampo = limpiarCadena($_GET['ocampo']);
	$pvalor = limpiarNumeros($_GET['ovalor']);
	$linkPG = Conectarse_POSTGRES();
	// Browse Data
	$sQueryS = "SELECT *";
	$sQueryF = " FROM peru_conflictos_sociales_nuevo";
	$sQueryW = " WHERE gid = '" . $pvalor . "'";

	$sQuery = $sQueryS . $sQueryF . $sQueryW;
	$rsDet = pg_query( $linkPG , $sQuery );
	$titulo_ventana = 'CONFLICTOS SOCIALES - '. pg_fetch_result($rsDet,0,"\"tipo_natu\"");
	$titulo = 'CONFLICTOS SOCIALES - '. pg_fetch_result($rsDet,0,"\"tipo_natu\"");
	include ('inc/consulta_cabecera.php');
?>
<table width="100%" border="0" cellspacing="0" cellpadding="10">
  <tr><td>
	<table width="100%" class="marco_general">
	  <tr><td>
		<table width="100%" class="marco_individual">
		  <tr>
			<td>
			<div id="u1" style="width: 100%;">
					<h1>
						<table width="100%" class="titulo_general">
						  <tr>
							<td  colspan="7"><?php echo $imgtitulo;?>&nbsp;&nbsp;UBICACIÓN GEOGRÁFICA</td>
						  </tr>
						</table>
					</h1>
				<div>
				<table width='100%' align='center' class='general'>
					<thead>
					  <tr>
						<th width='25%'>Departamento</th>
						<th width='25%'>Provincia</th>
						<th width='25%'>Distrito</th>
						<th width='25%'>Codigo Distrito</th>
					  </tr>
					</thead>
					<tbody>
					<tr>
						<td align='center' class='texto'><?php echo(pg_fetch_result($rsDet,0,"\"nom_dpto\"")) ?></td>
						<td align='center' class='texto'><?php echo(pg_fetch_result($rsDet,0,"\"nom_prov\"")) ?></td>
						<td align='center' class='texto'><?php echo(pg_fetch_result($rsDet,0,"\"nom_dist\"")) ?></td>
						<td align='center' class='texto'><?php echo(pg_fetch_result($rsDet,0,"\"cod_dist\"")) ?></td>
					</tr>
	
					</tbody>
				</table>
			</td>
		  </tr>
		</table>
		<br>
		<table width="100%" class="marco_individual">
		  <tr>
			<td>
			<div id="u2" style="width: 100%;">
					<h1>
						<table width="100%" class="titulo_general">
						  <tr>
							<td  colspan="7"><?php echo $imgtitulo;?>&nbsp;&nbsp;DATOS GENERALES</td>
						  </tr>
						</table>
					</h1>
				<div>
			<table width='100%' align='center' class='general'>
		<?php
		print "<tr>
				<td width='50%' class='lista_titulo'>Nombre del Caso:</td>
				<td width='50%' class='texto1'>".pg_fetch_result($rsDet,0,"\"nom_caso\"")."</td>
			  </tr>
			  <tr>
				<td class='lista_titulo'>Ubicación del Conflicto:</td>
                <td class='texto1'>"
                    .pg_fetch_result($rsDet,0,"\"ubica1\""). " "
                    .pg_fetch_result($rsDet,0,"\"ubica2\""). 
                "</td>
			  </tr>

			  <tr>
				<td class='lista_titulo'>Estado del Caso:</td>
				<td class='texto1'>".pg_fetch_result($rsDet,0,"\"estado\"")."</td>
              </tr>
              
              <tr>
              <td class='lista_titulo'>Problemática:</td>
              <td class='texto1'>"
                  .pg_fetch_result($rsDet,0,"\"problem1\""). " "
                  .pg_fetch_result($rsDet,0,"\"problem2\""). " "
                  .pg_fetch_result($rsDet,0,"\"problem3\""). " "
                  .pg_fetch_result($rsDet,0,"\"problem4\""). " "
                  .pg_fetch_result($rsDet,0,"\"problem5\""). " "
                  .pg_fetch_result($rsDet,0,"\"problem6\""). " "
                  .pg_fetch_result($rsDet,0,"\"problem7\""). " "
                  .pg_fetch_result($rsDet,0,"\"problem8\""). " "
                  .pg_fetch_result($rsDet,0,"\"problem9\""). " "
                  .pg_fetch_result($rsDet,0,"\"problem10\""). " "
                  .pg_fetch_result($rsDet,0,"\"problem11\""). " "
                  .pg_fetch_result($rsDet,0,"\"problem12\""). " "
                  .pg_fetch_result($rsDet,0,"\"problem13\""). " "
                  .pg_fetch_result($rsDet,0,"\"problem14\""). " "
                  .pg_fetch_result($rsDet,0,"\"problem15\""). " "
                  .pg_fetch_result($rsDet,0,"\"problem16\""). 
              "</td>
            </tr>


            <tr>
            <td class='lista_titulo'>Situación Actual Interna:</td>
            <td class='texto1'>"
                .pg_fetch_result($rsDet,0,"\"situac1\""). " "
                .pg_fetch_result($rsDet,0,"\"situac2\""). " "
                .pg_fetch_result($rsDet,0,"\"situac3\""). " "
                .pg_fetch_result($rsDet,0,"\"situac4\""). " "
                .pg_fetch_result($rsDet,0,"\"situac5\""). " "
                .pg_fetch_result($rsDet,0,"\"situac6\""). " "
                .pg_fetch_result($rsDet,0,"\"situac7\""). " "
                .pg_fetch_result($rsDet,0,"\"situac8\""). " "
                .pg_fetch_result($rsDet,0,"\"situac9\""). " "
                .pg_fetch_result($rsDet,0,"\"situac10\""). " "
                .pg_fetch_result($rsDet,0,"\"situac11\""). " "
                .pg_fetch_result($rsDet,0,"\"situac12\""). " "
                .pg_fetch_result($rsDet,0,"\"situac13\""). " "
                .pg_fetch_result($rsDet,0,"\"situac14\""). " "
                .pg_fetch_result($rsDet,0,"\"situac15\""). 
            "</td>
          </tr>

          <tr>
				<td class='lista_titulo'>Código del Caso:</td>
				<td class='texto1'>".pg_fetch_result($rsDet,0,"\"cod_cas\"")."</td>
              </tr>
			";
		?>
			</table>
			</td>
		  </tr>
		</table>
		<br>

		<?php 

			// Browse Data
			$qConflictos = "select
							pd.nom_dist,
							pd.cod_dist,
							count(pcs.gid) as cantidad
						from peru_distritos pd
						left join peru_conflictos_sociales_nuevo pcs on pcs.cod_dist = pd.cod_dist 
						where pd.cod_prov = '".pg_fetch_result($rsDet,0,"\"cod_prov\"").
						"' group by pd.nom_dist, pd.cod_dist
						order by pd.cod_dist;";
			$dConflictos = pg_query( $linkPG , $qConflictos );
			$numrowsConflictos = pg_num_rows($dConflictos);

		?>	

		<table width="100%" class="marco_individual">
		  <tr>
			<td>
			<div id="u3" style="width: 100%;">
					<h1>
						<table width="100%" class="titulo_general">
						  <tr>
							<td  colspan="7"><?php echo $imgtitulo;?>&nbsp;&nbsp;CONFLICTOS SOCIALES PROVINCIA DE <?php echo(pg_fetch_result($rsDet,0,"\"nom_prov\"")) ?></td>
						  </tr>
						</table>
					</h1>
			 <div>
		
				
				
			<table width='100%' align='center' class='general'>
		<?php
		$i = 0;
		$total_conflictos_prov = 0;
		while($i<$numrowsConflictos){
			if(pg_fetch_result($dConflictos,$i,"\"cod_dist\"")==pg_fetch_result($rsDet,0,"\"cod_dist\"")){
				$classet='class="titulo11"';
				$classcell= 'class="titulo11"';
			} else {
				$classet='class="textosub"';
				$classcell= 'class="texto1"';
			}

			print "<tr>
				<td width='50%' style='text-align: left;' ".$classet.">".(string) ($i+1)."-".pg_fetch_result($dConflictos,$i,"\"nom_dist\"")."</td>
				<td width='50%' ".$classcell."  align='center'>".pg_fetch_result($dConflictos,$i,"\"cantidad\"")."</td>
			  </tr>
			";
			$total_conflictos_prov += pg_fetch_result($dConflictos,$i,"\"cantidad\"");
			$i++;
		}

		print "
			<tr>
				<td class='titulosub'>Total</td>
				<td class='titulosub'>".$total_conflictos_prov."</td>
			</tr>";
		
		?>
			</table>
			</td>
		  </tr>
		</table>


		<br>
		<?php 

			// Browse Data
			$qConflictosDpto = "select
					pp.nom_prov,
					pp.cod_prov,
					count(pcs.gid) as cantidad
				from peru_provincias pp
				left join peru_conflictos_sociales_nuevo pcs on pcs.cod_prov = pp.cod_prov
				where pp.cod_dpto = '".pg_fetch_result($rsDet,0,"\"cod_dpto\"").
				"' group by pp.nom_prov, pp.cod_prov
				order by pp.cod_prov;";
			$dConflictosDpto = pg_query( $linkPG , $qConflictosDpto );
			$numrowsConflictosDpto = pg_num_rows($dConflictosDpto);

		?>	

		<table width="100%" class="marco_individual">
		  <tr>
			<td>

			<div id="u4" style="width: 100%;">
					<h1>
						<table width="100%" class="titulo_general">
						  <tr>
							<td  colspan="7"><?php echo $imgtitulo;?>&nbsp;&nbsp;CONFLICTOS SOCIALES DEPARTAMENTO DE <?php echo(pg_fetch_result($rsDet,0,"\"nom_dpto\"")) ?></td>
						  </tr>
						</table>
					</h1>
			<div>
			
					  
			<table width='100%' align='center' class='general'>
		<?php
		$i = 0;
		$total_conflictos_dpto = 0;
		while($i<$numrowsConflictosDpto){
			if(pg_fetch_result($dConflictosDpto,$i,"\"cod_prov\"")==pg_fetch_result($rsDet,0,"\"cod_prov\"")){
				$classet='class="titulo11"';
				$classcell= 'class="titulo11"';
			} else {
				$classet='class="textosub"';
				$classcell= 'class="texto1"';
			}

			print "<tr>
				<td width='50%' style='text-align: left;' ".$classet.">".(string) ($i+1)."-".pg_fetch_result($dConflictosDpto,$i,"\"nom_prov\"")."</td>
				<td width='50%' ".$classcell." align='center'>".pg_fetch_result($dConflictosDpto,$i,"\"cantidad\"")."</td>
			  </tr>
			";
			$total_conflictos_dpto += pg_fetch_result($dConflictosDpto,$i,"\"cantidad\"");
			$i++;
		}

		print "
			<tr>
				<td class='titulosub'>Total</td>
				<td class='titulosub'>".$total_conflictos_dpto."</td>
			</tr>";
		
		?>
			</table>
			</td>
		  </tr>
		</table>





		<br>

		
		<table class='fuente_general' width="100%"><thead><tr><th><b>Fuente:</b>
			<br><?php echo pg_fetch_result($rsDet,0,"\"fuente\"");?></th></tr></thead>
		</table>
	<?php
	//$name=strtoupper(pg_fetch_result($rsDet,0,"\"tipoaerona\"").' - '.pg_fetch_result($rsDet,0,"\"label\""));
	$name='CONFLICTOS SOCIALES - '. pg_fetch_result($rsDet,0,"\"tipo_natu\"");
	$capa='consulta_conflictos_sociales';
	if (!isset($_GET['excel'])) {
		$ruta=$capa.'.phtml?excel=excel&capa='.$capa.'&ovalor='.$pvalor.'&olayer=peru_conflictos_sociales'.'&ocampo=gid';
		include 'inc/consulta_pie.php';
	}
	if (isset($_SESSION['usuario'])) {
		grabar_log_accesos('ingreso', $cod_user, $name, $descripcion);
	}
	?>
		</td>
	  </tr>
	</table>
	</td>
  </tr>
</table>


<script language="javascript" type="text/javascript">
	$(document).ready(function(){
		$("#u1").h2c_acordeon();
		$("#u2").h2c_acordeon();
		$("#u3").h2c_acordeon();
		$("#u4").h2c_acordeon();
		
	});
</script>

</body>
</html>
<?php include_once("./analyticstracking.php");?>


