<?php

if (isset($_GET['excel']) && ($_GET['excel']=='excel')) {
	header("Content-type:application/x-msexcel");
	$file=$_GET['capa'];
	header("Content-Disposition: attachment; filename=".$file.".xls");
	$imgtitulo='';
} else {
	$imgtitulo='<img src="imajes/desplegable.png" width="11" height="11">';
}
function valorsino($campo){
				if($campo=='1'){$valor='S&iacute;';}elseif($campo=='2'){$valor='No';}elseif($campo=='0'){$valor='Sin datos';}
				return $valor;
			}
/*@session_start();
	if(empty($_SESSION['usuario'])){
        header('Location: ../index.php');
		}else{$cod_user = $_SESSION['usuario'];}*/
	include ('conexion_postgres.phtml');
	include ('injection/funciones.php');
	$player = limpiarCadena($_GET['olayer']);
	$pcampo = limpiarCadena($_GET['ocampo']);
    $pvalor = limpiarNumeros($_GET['ovalor']);
	$linkPG = Conectarse_POSTGRES();
	// Browse Data
	$sQueryS = "SELECT *";
	//$sQueryF = " FROM unidades_min_produccion_mayo2022";
	$sQueryF = " FROM vw_peru_tumbes_zonas_accesibilidad";
	$sQueryW = " WHERE \"gid\" = '" . $pvalor . "'";

	$sQuery = $sQueryS . $sQueryF . $sQueryW;
	$rsDet = pg_query( $linkPG , $sQuery );
	$titulo_ventana = 'ZONAS DE ACCESIBILIDAD';
	$titulo = $titulo_ventana;
	include ('inc/consulta_cabecera.php');
?>
<table width="100%" border="0" cellspacing="0" cellpadding="10">
  <tr><td>
	<table width="100%" class="marco_general">
	  <tr><td>
		<table width="100%" class="marco_individual">
		  <tr>
			<td>
			<table width="100%" class="titulo_general">
			  <tr>
				<td>&nbsp;&nbsp;UBICACI&Oacute;N GEOGR&Aacute;FICA</td>
			  </tr>
			</table>
			<table width='100%' align='center' class='general'>
				<thead>
				<?php print" <tr>
					<th width='20%'>DEPARTAMENTO</th>
					<th width='20%'>PROVINCIA</th>
					<th width='20%'>DISTRITO</th>
					<th width='20%'>UBIGEO</th>
				  </tr>";?>
				</thead>
				<tbody>
	<?php
			print "<tr>
					<td align='center' class='texto'>".pg_fetch_result($rsDet,0,"\"nom_dpto\"")."</td>
					<td align='center' class='texto'>".pg_fetch_result($rsDet,0,"\"nom_prov\"")."</td>
					<td align='center' class='texto'>".pg_fetch_result($rsDet,0,"\"nom_dist\"")."</td>
					<td align='center' class='texto'>".pg_fetch_result($rsDet,0,"\"cod_dist\"")."</td>
				  </tr>";
	?>
				</tbody>
			</table>
			</td>
		  </tr>
		</table>
		<br>
        <table width="100%" class="marco_individual">
		  <tr>
			<td>
			<table width="100%" class="titulo_general">
			  <tr>
				<td>&nbsp;&nbsp;DATOS ZONA DE ACCESIBILIDAD</td>
			  </tr>
			</table>
			<table width="100%" class="listado">
	<?php
		print "<tr>
				<td width='50%' class='lista_titulo'>Nivel de Accesibilidad</td>
				<td align='' class='texto'>".pg_fetch_result($rsDet,0,"\"niv_acce\"")."</td>
			  </tr>
			  <tr>
				<td class='lista_titulo'>% de la red vial asfaltada con respecto al total de la red vial en el distrito</td>
				<td align='' class='texto'>".pg_fetch_result($rsDet,0,"\"por_asf\"")."</td>
			  </tr>
			  <tr>
				<td class='lista_titulo'>% de la red vial afirmada con respecto al total de la red vial en el distrito</td>
				<td align='' class='texto'>".pg_fetch_result($rsDet,0,"\"por_afi\"")."</td>
              </tr>
              <tr>
                <td class='lista_titulo'>Dirección de la ubicación del reservorio</td>
                <td class='texto'>".pg_fetch_result($rsDet,0,"\"n_acces\"")."</td>
              </tr>
              <tr>
                <td class='lista_titulo'>Número de total de obstáculos del distrito</td>
                <td class='texto'>".pg_fetch_result($rsDet,0,"\"n_obst\"")."</td>
              </tr>
			  <tr>
			  <td class='lista_titulo'>Número de accesos (entradas y salidas) entre 1 a 3</td>
			  <td align='' class='texto'>".pg_fetch_result($rsDet,0,"\"acce_1a3\"")."</td>
			</tr>
			<tr>
			  <td class='lista_titulo'>Número de accesos (entradas y salidas) entre 4 a más</td>
			  <td class='texto'>".pg_fetch_result($rsDet,0,"\"acce_4a8\"")."</td>
			</tr>
			<tr>
				<td width='50%' class='lista_titulo'>% de la red vial de trocha carrozable con respecto al total de la red vial en el distrito</td>
				<td align='' class='texto'>".pg_fetch_result($rsDet,0,"\"por_tro\"")."</td>
			  </tr>
			  <tr>
				<td class='lista_titulo'>Superficie en hectáreas (Has.) del distrito</td>
				<td align='' class='texto'>".pg_fetch_result($rsDet,0,"\"area_d_ha\"")."</td>
			  </tr>
			  <tr>
				<td class='lista_titulo'>Superficie en kilómetros cuadrados (km2) del distrito</td>
				<td align='' class='texto'>".pg_fetch_result($rsDet,0,"\"area_d_km\"")."</td>
              </tr>
              <tr>
                <td class='lista_titulo'>Longitud de la red vial asfaltada en kilómetros (km)</td>
                <td class='texto'>".pg_fetch_result($rsDet,0,"\"s_asf_km\"")."</td>
              </tr>
              <tr>
                <td class='lista_titulo'>Longitud de la red vial afirmada en kilómetros (km)</td>
                <td class='texto'>".pg_fetch_result($rsDet,0,"\"s_afir_km\"")."</td>
              </tr>
			  <tr>
			  <td class='lista_titulo'>Longitud de la red vial de trocha carrozable en kilómetros (km)</td>
			  <td align='' class='texto'>".pg_fetch_result($rsDet,0,"\"s_tro_km\"")."</td>
			</tr>
			<tr>
			  <td class='lista_titulo'>Longitud total de la red vial en kilómetros (km)</td>
			  <td class='texto'>".pg_fetch_result($rsDet,0,"\"long_t_km\"")."</td>
			</tr>
			<tr>
				<td width='50%' class='lista_titulo'>Número de puentes en el distrito</td>
				<td align='' class='texto'>".pg_fetch_result($rsDet,0,"\"n_punt\"")."</td>
			  </tr>
			  <tr>
				<td class='lista_titulo'>Número de badenes en el distrito</td>
				<td align='' class='texto'>".pg_fetch_result($rsDet,0,"\"n_bade\"")."</td>
			  </tr>
			  <tr>
				<td class='lista_titulo'>% de área de pendiente de 0 a 15 %con respecto al total del área del distrito</td>
				<td align='' class='texto'>".pg_fetch_result($rsDet,0,"\"por_p_0a15\"")."</td>
              </tr>
              <tr>
                <td class='lista_titulo'>% de área de pendiente de 15 a 25 % con respecto al total del área del distrito</td>
                <td class='texto'>".pg_fetch_result($rsDet,0,"\"po_p_15a25\"")."</td>
              </tr>
              <tr>
                <td class='lista_titulo'>% de área de pendiente de 25 a 50 % con respecto al total del área del distrito </td>
                <td class='texto'>".pg_fetch_result($rsDet,0,"\"po_p_25a50\"")."</td>
              </tr>
			  <tr>
			  <td class='lista_titulo'>% de área de pendiente de 50 a 75 % con respecto al total del área del distrito</td>
			  <td align='' class='texto'>".pg_fetch_result($rsDet,0,"\"po_p_50a75\"")."</td>
			</tr>
			<tr>
			  <td class='lista_titulo'>% de área de pendiente mayor a 75 % con respecto al total del área del distrito</td>
			  <td class='texto'>".pg_fetch_result($rsDet,0,"\"po_p_mas75\"")."</td>
			</tr>
			<tr>
				<td width='50%' class='lista_titulo'>Valor de la ponderación de variables que da como resultado la vialidad </td>
				<td align='' class='texto'>".pg_fetch_result($rsDet,0,"\"vialidad\"")."</td>
			  </tr>
			  <tr>
				<td class='lista_titulo'>Número de badenes entre 1 a 3</td>
				<td align='' class='texto'>".pg_fetch_result($rsDet,0,"\"bade_1a3\"")."</td>
			  </tr>
			  <tr>
				<td class='lista_titulo'>Número de badenes entre 4 a más</td>
				<td align='' class='texto'>".pg_fetch_result($rsDet,0,"\"bade_4a8\"")."</td>
              </tr>
              <tr>
                <td class='lista_titulo'>Número de puentes entre 1 a 3</td>
                <td class='texto'>".pg_fetch_result($rsDet,0,"\"punt_1a3\"")."</td>
              </tr>
              <tr>
                <td class='lista_titulo'>Número de puentes entre 4 a más</td>
                <td class='texto'>".pg_fetch_result($rsDet,0,"\"punt_4a8\"")."</td>
              </tr>
			  <tr>
			  <td class='lista_titulo'>Densidad de la red vial en kilómetros por kilómetros cuadrados (km/km2)</td>
			  <td align='' class='texto'>".pg_fetch_result($rsDet,0,"\"densid_km\"")."</td>
			</tr>
			<tr>
			  <td class='lista_titulo'>Valor de la ponderación de variables que da como resultado la permeabilidad</td>
			  <td class='texto'>".pg_fetch_result($rsDet,0,"\"permeab\"")."</td>
			</tr>
			<tr>
			  <td class='lista_titulo'>Valor de la ponderación de variables que da como resultado la accesibilidad</td>
			  <td class='texto'>".pg_fetch_result($rsDet,0,"\"accesib\"")."</td>
			</tr>
			";
	    ?>
			</table>
			</td>
		  </tr>
		</table>  

		<table class='fuente_general' width="100%"><thead><tr><th><b>Fuente:</b>
			<br><?php echo(pg_fetch_result($rsDet,0,"\"fuente\""))?><?php echo(pg_fetch_result($rsDet,0,"\"fuente1\""));?>
		</th></tr></thead></table>
	<?php
	$name='CONADIS - Población con discapacidad';
	$capa='peru_discapacidad_pobla_discap_';
	if (!isset($_GET['excel'])) {
		$ruta=$capa.'.phtml?excel=excel&capa='.$capa.'&ovalor='.$pvalor.'&olayer=peru_conadis'.'&ocampo=gid';
		
		include 'inc/consulta_pie.php';
	}
	if (isset($_SESSION['usuario'])) {
		grabar_log_accesos('ingreso', $cod_user, $name, $descripcion);
	}
	?>
		</td></tr>
	</table>
	</td></tr>
</table>
</body>
</html>
<?php include_once("./analyticstracking.php");?>
