
<?php

if (isset($_GET['excel']) && ($_GET['excel']=='excel')){
	header("Content-type:application/x-msexcel");
	$file=$_GET['capa'];
	header("Content-Disposition: attachment; filename=".$file.".xls");
	$imgtitulo='';
} else{
	$imgtitulo='<img src="imajes/desplegable.png" width="11" height="11">';
}

/*@session_start();
	if(empty($_SESSION['usuario'])){
        header('Location: ../index.php');
	}else{$cod_user = $_SESSION['usuario'];}*/
	include ('conexion_postgres.phtml');
	include ('injection/funciones.php');
	$player = limpiarCadena($_GET['olayer']);
	$pcampo = limpiarCadena($_GET['ocampo']);
	$pvalor = limpiarNumeros($_GET['ovalor']);
	$linkPG = Conectarse_POSTGRES();
	// Browse Data
	$sQueryS = "SELECT *";
	$sQueryF = " FROM peru_locales_educativos";
	$sQueryW = " WHERE gid = '" . $pvalor . "'";

	$sQuery = $sQueryS . $sQueryF . $sQueryW;
	$rsDet = pg_query( $linkPG , $sQuery );
	$titulo_ventana = 'Locales Educativos 2019';
	$titulo = 'Locales Educativos 2019';
	include ('inc/consulta_cabecera.php');
?>
<table width="100%" border="0" cellspacing="0" cellpadding="10">
  <tr><td>
	<table width="100%" class="marco_general">
	  <tr><td>
		<table width="100%" class="marco_individual">
		  <tr>
			<td>
				<table width="100%" class="titulo_general">
				  <tr>
					<td>&nbsp;&nbsp;UBICACI&Oacute;N GEOGR&Aacute;FICA</td>
				  </tr>
				</table>
				<table width='100%' align='center' class='general'>
					<thead>
					  <tr>
						<th width='25%'>Departamento</th>
						<th width='25%'>Provincia</th>
						<th width='25%'>Distrito</th>
						<th width='25%'>Codigo Distrito</th>
					  </tr>
					</thead>
					<tbody>
					<tr>
						<td align='center' class='texto'><?php echo(pg_fetch_result($rsDet,0,"\"nom_dpto\"")) ?></td>
						<td align='center' class='texto'><?php echo(pg_fetch_result($rsDet,0,"\"nom_prov\"")) ?></td>
						<td align='center' class='texto'><?php echo(pg_fetch_result($rsDet,0,"\"nom_dist\"")) ?></td>
						<td align='center' class='texto'><?php echo(pg_fetch_result($rsDet,0,"\"cod_dist\"")) ?></td>
					</tr>
	
					</tbody>
				</table>
			</td>
		  </tr>
		</table>
		<br>
		<table width="100%" class="marco_individual">
		  <tr>
			<td>
				<table width="100%" class="titulo_general">
					  <tr>
						<td>&nbsp;&nbsp;DATOS GENERALES</td>
					  </tr>
				</table>
			<table width='100%' align='center' class='general'>
		<?php
        print "
        <tr>
        <td width='50%' class='lista_titulo'>Centro Poblado</td>
        <td width='50%' class='texto1'>".pg_fetch_result($rsDet,0,"\"cen_pob\"")."</td>
      </tr>
        <tr>
				<td width='50%' class='lista_titulo'>Código de local educativo</td>
				<td width='50%' class='texto1'>".pg_fetch_result($rsDet,0,"\"cod_local\"")."</td>
			  </tr>
			  <tr>
				<td class='lista_titulo'>Código(s) modular(es)</td>
                <td class='texto1'>".pg_fetch_result($rsDet,0,"\"cods_mods\"")."</td>
			  </tr>
			  <tr>
				<td class='lista_titulo'>Gestión(es) Educativas</td>
				<td class='texto1'>".pg_fetch_result($rsDet,0,"\"gestion_es\"")."</td>
              </tr>
              <tr>
                <td class='lista_titulo'>Nombre(s) de la(s) institución(es) educativa(s)</td>
                <td class='texto1'>".pg_fetch_result($rsDet,0,"\"nombres_ie\"")."</td>
              </tr>
              <tr>
                <td class='lista_titulo'>Región Educativa</td>
                <td class='texto1'>".pg_fetch_result($rsDet,0,"\"reg_edu\"")." </td>
              </tr>

              <tr>
                <td class='lista_titulo'>Órgano Intermedio de Ejecución</td>
                <td class='texto1'>".pg_fetch_result($rsDet,0,"\"org_i_ejec\"")."</td>
              </tr>

              <tr>
                <td class='lista_titulo'>Dirección</td>
               <td class='texto1'>".pg_fetch_result($rsDet,0,"\"direccion\"")."</td>
              </tr>

              <tr>
                <td class='lista_titulo'>Área</td>
                <td class='texto1'>".pg_fetch_result($rsDet,0,"\"area\"")."</td>
              </tr>


			";
		?>
			</table>
			</td>
		  </tr>
		</table>
		<br>

        <table width="100%" class="marco_individual">
		  <tr>
			<td>
				<table width="100%" class="titulo_general">
					  <tr>
						<td>&nbsp;&nbsp;AULAS Y SU ESTADO DE CONSERVACIÓN</td>
					  </tr>
				</table>
			<table width='100%' align='center' class='general'>
		<?php
        print "
            <tr>
                <td width='50%' class='lista_titulo'>Número de Aulas en Uso</td>
                <td width='50%' class='texto1'>".pg_fetch_result($rsDet,0,"\"aucons_1\"")."</td>
            </tr>
            <tr>
				<td width='50%' class='lista_titulo'>Observación</td>
				<td width='50%' class='texto1'>".pg_fetch_result($rsDet,0,"\"obs1\"")."</td>
			  </tr>
			  <tr>
				<td class='lista_titulo'>Número de aulas en uso en buen estado de conservación</td>
                <td class='texto1'>".pg_fetch_result($rsDet,0,"\"aucons_2\"")."</td>
			  </tr>
			  <tr>
				<td class='lista_titulo'>Número de aulas en uso en regular estado de conservación</td>
				<td class='texto1'>".pg_fetch_result($rsDet,0,"\"aucons_3\"")."</td>
              </tr>
              <tr>
                <td class='lista_titulo'>Número de aulas en uso en mal estado de conservación</td>
                <td class='texto1'>".pg_fetch_result($rsDet,0,"\"aucons_4\"")."</td>
              </tr>
              <tr>
                <td class='lista_titulo'>Número de Aulas Sin Uso</td>
                <td class='texto1'>".pg_fetch_result($rsDet,0,"\"aucons_5\"")." </td>
              </tr>

              <tr>
                <td class='lista_titulo'>Número de aulas sin uso en buen estado de conservación</td>
                <td class='texto1'>".pg_fetch_result($rsDet,0,"\"aucons_6\"")."</td>
              </tr>

              <tr>
                <td class='lista_titulo'>Número de aulas sin uso en regular estado de conservación</td>
               <td class='texto1'>".pg_fetch_result($rsDet,0,"\"aucons_7\"")."</td>
              </tr>

              <tr>
                <td class='lista_titulo'>Número de aulas sin uso en mal estado de conservación</td>
                <td class='texto1'>".pg_fetch_result($rsDet,0,"\"aucons_8\"")."</td>
              </tr>

              <tr>
                <td class='lista_titulo'>Número de aulas de gestión privada</td>
                <td class='texto1'>".pg_fetch_result($rsDet,0,"\"agpr_1\"")."</td>
              </tr>

              <tr>
                <td class='lista_titulo'>Número de aulas de gestión privada en uso en buen estado de conservación</td>
                <td class='texto1'>".pg_fetch_result($rsDet,0,"\"agpr_2\"")."</td>
              </tr>

              <tr>
                <td class='lista_titulo'>Número de aulas de gestión privada en uso en regular estado de conservación</td>
                <td class='texto1'>".pg_fetch_result($rsDet,0,"\"agpr_3\"")."</td>
              </tr>

              <tr>
                <td class='lista_titulo'>Número de aulas de gestión privada en uso en mal estado de conservación</td>
                <td class='texto1'>".pg_fetch_result($rsDet,0,"\"agpr_4\"")."</td>
              </tr>

              <tr>
                <td class='lista_titulo'>Número de aulas de gestión privada en uso en pésimo estado de conservación</td>
                <td class='texto1'>".pg_fetch_result($rsDet,0,"\"agpr_5\"")."</td>
              </tr>

              <tr>
                <td class='lista_titulo'>Número de aulas de gestión privada sin uso</td>
                <td class='texto1'>".pg_fetch_result($rsDet,0,"\"agpr_6\"")."</td>
              </tr>


			";
		?>
			</table>
			</td>
		  </tr>
		</table>

        <br>

        <table width="100%" class="marco_individual">
		  <tr>
			<td>
				<table width="100%" class="titulo_general">
					  <tr>
						<td>&nbsp;&nbsp;SERVICIOS EN EL LOCAL EDUCATIVO</td>
					  </tr>
				</table>
			<table width='100%' align='center' class='general'>
		<?php
        print "
            <tr>
                <td width='50%' class='lista_titulo'>¿El local educativo cuenta con internet?</td>
                <td width='50%' class='texto1'>".pg_fetch_result($rsDet,0,"\"serv_1\"")."</td>
            </tr>
            <tr>
				<td width='50%' class='lista_titulo'>La energía eléctrica del local educativo proviene de:</td>
				<td width='50%' class='texto1'>".pg_fetch_result($rsDet,0,"\"serv_2\"")."</td>
			  </tr>
			  <tr>
				<td class='lista_titulo'>El agua que usa del local educativo proviene de:</td>
                <td class='texto1'>".pg_fetch_result($rsDet,0,"\"serv_3\"")."</td>
			  </tr>
			  <tr>
				<td class='lista_titulo'>Con respecto al desagüe del local educativo:</td>
				<td class='texto1'>".pg_fetch_result($rsDet,0,"\"serv_4\"")."</td>
              </tr>
             


			";
		?>
			</table>
			</td>
		  </tr>
		</table>
		
		<table class='fuente_general' width="100%"><thead><tr><th><b>Fuente:</b>
			<br><?php echo pg_fetch_result($rsDet,0,"\"fuente\"");?></th></tr></thead>
		</table>
	<?php
	//$name=strtoupper(pg_fetch_result($rsDet,0,"\"tipoaerona\"").' - '.pg_fetch_result($rsDet,0,"\"label\""));
	$name='Locales Educativos 2019';
	$capa='consulta_actores_politicos';
	if (!isset($_GET['excel'])) {
		$ruta=$capa.'.phtml?excel=excel&capa='.$capa.'&ovalor='.$pvalor.'&olayer=peru_locales_educativos'.'&ocampo=gid';
		include 'inc/consulta_pie.php';
	}
	if (isset($_SESSION['usuario'])) {
		grabar_log_accesos('ingreso', $cod_user, $name, $descripcion);
	}
	?>
		</td>
	  </tr>
	</table>
	</td>
  </tr>
</table>
</body>
</html>
<?php include_once("./analyticstracking.php");?>


