<!--***************************************************************************************
Organizaci&oacute;n: 	Presidencia del Consejo de Ministros - PCM
Gerencia	: 	Secretar&iacute;a de Descentralizaci&oacute;n
Sistema		: 	Sistema Nacional de Informaci&oacute;n Geogr&aacute;fica - SAYWITE
Coordinador/Desarrollador TIC: Vitaly Uriel Cespedes Reynaga vitalyuri@hotmail.com/vitalyuri@gmail.com/969228151
Periodo		: 	Septiembre 2012 - 2013
***************************************************************************************-->
<style type="text/css">
<!--
.Estilo1 {color: #FFFFFF; font-size: 14px;}
.Estilo2 {font-family: Arial, Helvetica, sans-serif;color: #333333; font-size: 13px; padding-bottom:5px}
-->
</style>

<table width="100%" align="center" class="tabla1">
  <tr>
	<td>
	<table width="100%" align="center" class="tabla2">
</br>

	  <tr>
		<td bgcolor="#125565"><div align="center" class="Estilo1">CONDICIONES DE USO <br>SISTEMA NACIONAL GEORREFERENCIADO - SAYHUITE</div></td>
	  </tr>
	  	  <tr>
		<td><div align="justify" class="Estilo2">
		 Sayhuite es una herramienta provista por la Presidencia del Consejo de Ministros (PCM) y administrada por la Secretar&iacute;a de Gobierno Digital (SEGDI), Antes de usarla debe tener en consideraci&oacute;n lo siguiente
		</div>
<ul><li>
    <div align="justify" class="Estilo2">Los datos presentados por la herramienta han sido provistos por las Entidades del Estado propietarias de la informaci&oacute;n. Debido a que las capas de informaci&oacute;n presentan diferentes frecuencias de actualizaci&oacute;n, se recomienda verificar la fecha de actualizaci&oacute;n haciendo click derecho sobre el nombre de la capa de inter&eacute;s.</div>
  </li>
  <li>
    <div align="justify" class="Estilo2">El uso de los datos est&aacute; condicionado por las consideraciones definidas por las entidades productoras de la informaci&oacute;n, por lo que se recomienda leer los alcances provistos por la herramienta.</div>
  </li>
  <li>
    <div align="justify" class="Estilo2">Los l&iacute;mites de departamentos, provincias y distritos mostrados, han sido provistos por el Instituto Nacional de Estad&iacute;stica e Inform&aacute;tica (INEI), tienen car&aacute;cter referencial en tanto se contin&uacute;e con el proceso de saneamiento de l&iacute;mites territoriales, conforme a lo establecido en la Quinta Disposici&oacute;n Transitoria y Final de la Ley N&#176; 27795, Ley de Demarcaci&oacute;n y Organizaci&oacute;n Territorial.</div>
  </li>
  <li><div align="justify" class="Estilo2">Los centros poblados mostrados por la herramienta tienen una localizaci&oacute;n referencial, pudiendo existir diferencias con otras fuentes de informaci&oacute;n, se recomienda tener presente este alcance para evitar confusiones en su uso.</div></li>
  <li><div align="justify" class="Estilo2">La precisi&oacute;n de la informaci&oacute;n est&aacute; definida por su escala y los alcances sobre uso que se muestran en el aplicativo. Se recomienda tener en cuenta estas caracter&iacute;sticas cuando usen tales datos.</div></li>
    <li><div align="justify" class="Estilo2">La delimitaci&oacute;n de los territorios de los pueblos ind&iacute;genas u originarios tienen car&aacute;cter referencial en tanto estos sean definidos por el Ministerio de Cultura. Dicha base georreferenciada tiene una cobertura del 85% de las comunidades nativas de la Amazon&iacute;a peruana.</div></li>
</ul>
<p><div align="justify" class="Estilo2">En caso de  comentarios, s&iacute;rvase escribir al correo <a href="mailto:info@sayhuite.gob.pe">info@sayhuite.gob.pe</a>.</div>
<br><div align="justify" class="Estilo2">He le&iacute;do las condiciones de uso y acepto todas las  disposiciones descritas anteriormente.</div></p></td>
	  </tr>
	</table>
	</td>
  </tr>
</table>