<!--***************************************************************************************
Organizaci&oacute;n: 	Presidencia del Consejo de Ministros - PCM
Gerencia	: 	Secretar&iacute;a de Descentralizaci&oacute;n
Sistema		: 	Sistema Nacional de Informaci&oacute;n Geogr&aacute;fica - SAYWITE
Coordinador/Desarrollador TIC: Vitaly Uriel Cespedes Reynaga vitalyuri@hotmail.com/vitalyuri@gmail.com/969228151
Periodo		: 	Septiembre 2012 - 2013
***************************************************************************************-->
<html>
<head>
<link href="programas/css/estilos.css" rel="stylesheet" type="text/css">
<script src="../usuarios/js/jquery-3.2.1.min.js"></script>
<script src="../usuarios/js/jquery-ui.js"></script>
<body>

<script>

function TableS(data){
	var html;
	console.log(data);
	html='<table width="100%" align="center" class="marco_individual" ><tr></td><table id="example" class="display" cellspacing="0" border="1" width="100%"><thead><tr><th>TEMATICO</th><th>SUBTEMATICO</th><th>CAPA</th><th>DEFINICION</th></tr></thead><tfoot><tr><th>TEMATICO</th><th>SUBTEMATICO</th><th>CAPA</th><th>DEFINICION</th></tr></tfoot><tbody>';
	
	for(var i=0;i<data.length;i++){
		html+='<tr>';
			html+='<td ">'+data[i].tem+'</td>';
			html+='<td >'+data[i].sub+'</td>';
			html+='<td >'+data[i].label+'</td>';
			html+='<td>'+data[i].def+'</td>';

		html+='</tr>';
	}
	
	html+='</tbody></table></td></tr></table>';
	
	$('#tableData').html(html);
}

$(document).ready(function() {
//filtro nombre de usuario y se agrega el correo
	
	$('#CAPA_NAME').keyup(function() {
	  $.getJSON("acceso/nom-cap.php?val=" + $(this).val()+"&tem="+$("#tematico").val(), function (data) {
								TableS(data);
								console.log(data);
								});
	});
 
	

});
</script>
<style type="text/css">
<!--
.Estilo1 {color: #FFFFFF; font-size: 14px;}
.Estilo2 {font-family: Arial, Helvetica, sans-serif;color: #333333; font-size: 13px; padding-bottom:5px}
-->
#ui-id-1{
	z-index:5005;
}
</style>
<table width="100%" align="center" class="tabla1">
  <tr>
	<td>
	<table width="100%" align="center" class="tabla2">
	  <tr>
		<td bgcolor="#125565"><div align="center" class="Estilo1">GRUPO TEM&Aacute;TICO Y CAPAS <br>DEL SISTEMA NACIONAL GEORREFERENCIADO - SAYHUITE</div></td>
	  </tr>
	  <tr>
	  <td>
	  <label>Temático: </label>
	
		
		<label>Capa:</label>
		<input type="text" id="CAPA_NAME" name="CAPA_NAME">
		<td>
		
	  </tr>
	  <tr>
		<td>
			<div id="tableData"></div>
		</td>
	  </tr>
	</table>
	</td>
  </tr>
</table>
<body>
</html>