<?php

if (isset($_GET['excel']) && ($_GET['excel']=='excel')) {
	header("Content-type:application/x-msexcel");
	$file=$_GET['capa'];
	header("Content-Disposition: attachment; filename=".$file.".xls");
	$imgtitulo='';
} else {
	$imgtitulo='<img src="imajes/desplegable.png" width="11" height="11">';
}
function valorsino($campo){
				if($campo=='1'){$valor='S&iacute;';}elseif($campo=='2'){$valor='No';}elseif($campo=='0'){$valor='Sin datos';}
				return $valor;
			}
/*@session_start();
	if(empty($_SESSION['usuario'])){
        header('Location: ../index.php');
		}else{$cod_user = $_SESSION['usuario'];}*/
	include ('conexion_postgres.phtml');
	include ('injection/funciones.php');
	$player = limpiarCadena($_GET['olayer']);
	$pcampo = limpiarCadena($_GET['ocampo']);
    $pvalor = limpiarNumeros($_GET['ovalor']);
	$linkPG = Conectarse_POSTGRES();
	// Browse Data
	$sQueryS = "SELECT *";
	//$sQueryF = " FROM unidades_min_produccion_mayo2022";
	$sQueryF = " FROM vw_peru_tumbes_reservorios";
	$sQueryW = " WHERE \"gid\" = '" . $pvalor . "'";

	$sQuery = $sQueryS . $sQueryF . $sQueryW;
	$rsDet = pg_query( $linkPG , $sQuery );
	$titulo_ventana = 'RESERVORIOS';
	$titulo = $titulo_ventana;
	include ('inc/consulta_cabecera.php');
?>
<table width="100%" border="0" cellspacing="0" cellpadding="10">
  <tr><td>
	<table width="100%" class="marco_general">
	  <tr><td>
		<table width="100%" class="marco_individual">
		  <tr>
			<td>
			<table width="100%" class="titulo_general">
			  <tr>
				<td>&nbsp;&nbsp;UBICACI&Oacute;N GEOGR&Aacute;FICA</td>
			  </tr>
			</table>
			<table width='100%' align='center' class='general'>
				<thead>
				<?php print" <tr>
					<th width='20%'>DEPARTAMENTO</th>
					<th width='20%'>PROVINCIA</th>
					<th width='20%'>DISTRITO</th>
					<th width='20%'>UBIGEO</th>
				  </tr>";?>
				</thead>
				<tbody>
	<?php
			print "<tr>
					<td align='center' class='texto'>".pg_fetch_result($rsDet,0,"\"nom_dpto\"")."</td>
					<td align='center' class='texto'>".pg_fetch_result($rsDet,0,"\"nom_prov\"")."</td>
					<td align='center' class='texto'>".pg_fetch_result($rsDet,0,"\"nom_dist\"")."</td>
					<td align='center' class='texto'>".pg_fetch_result($rsDet,0,"\"cod_dist\"")."</td>
				  </tr>";
	?>
				</tbody>
			</table>
			</td>
		  </tr>
		</table>
		<br>
        <table width="100%" class="marco_individual">
		  <tr>
			<td>
			<table width="100%" class="titulo_general">
			  <tr>
				<td>&nbsp;&nbsp;DATOS DEL RESERVORIO</td>
			  </tr>
			</table>
			<table width="100%" class="listado">
	<?php
		print "<tr>
				<td width='50%' class='lista_titulo'>Nombre de Reservorio</td>
				<td align='' class='texto'>".pg_fetch_result($rsDet,0,"\"nombre\"")."</td>
			  </tr>
			  <tr>
				<td class='lista_titulo'>Nombre del centro de servicios</td>
				<td align='' class='texto'>".pg_fetch_result($rsDet,0,"\"nomb_ccss\"")."</td>
			  </tr>
			  <tr>
				<td class='lista_titulo'>Empresa que administra el reservorio</td>
				<td align='' class='texto'>".pg_fetch_result($rsDet,0,"\"administra\"")."</td>
              </tr>
              <tr>
                <td class='lista_titulo'>Dirección de la ubicación del reservorio</td>
                <td class='texto'>".pg_fetch_result($rsDet,0,"\"direccion\"")."</td>
              </tr>
              <tr>
                <td class='lista_titulo'>Tipo de reservorio según sus características físicas</td>
                <td class='texto'>".pg_fetch_result($rsDet,0,"\"tipo\"")."</td>
              </tr>
			  <tr>
			  <td class='lista_titulo'>Volumen del reservorio en metros cúbicos (m3)</td>
			  <td align='' class='texto'>".pg_fetch_result($rsDet,0,"\"volumen\"")."</td>
			</tr>
			<tr>
			  <td class='lista_titulo'>Accesibilidad</td>
			  <td class='texto'>".pg_fetch_result($rsDet,0,"\"accesib\"")."</td>
			</tr>
			";
	    ?>
			</table>
			</td>
		  </tr>
		</table>  

		<table class='fuente_general' width="100%"><thead><tr><th><b>Fuente:</b>
			<br><?php echo(pg_fetch_result($rsDet,0,"\"fuente\""))?><?php echo(pg_fetch_result($rsDet,0,"\"fuente1\""));?>
		</th></tr></thead></table>
	<?php
	$name='CONADIS - Población con discapacidad';
	$capa='peru_discapacidad_pobla_discap_';
	if (!isset($_GET['excel'])) {
		$ruta=$capa.'.phtml?excel=excel&capa='.$capa.'&ovalor='.$pvalor.'&olayer=peru_conadis'.'&ocampo=gid';
		
		include 'inc/consulta_pie.php';
	}
	if (isset($_SESSION['usuario'])) {
		grabar_log_accesos('ingreso', $cod_user, $name, $descripcion);
	}
	?>
		</td></tr>
	</table>
	</td></tr>
</table>
</body>
</html>
<?php include_once("./analyticstracking.php");?>
