	<script language="javascript" type="text/javascript" src="../tab/jquery-1.3.2.min.js"></script>
	<script language="javascript" type="text/javascript" src="../tab/h2c_acordeon.js"></script>
	<link href="../tab/h2c_acordeon.css" rel="stylesheet" type="text/css">
	<link href="css/estilos.css" rel="stylesheet" type="text/css">
	<script language="javascript" type="text/javascript" >


<link href="../css/general.css" rel="stylesheet" type="text/css">
<link href="../css/estilos.css" rel="stylesheet" type="text/css">
<script type="text/javascript" src="../jquery.tablesorter/jquery-latest.js"></script>
<script type="text/javascript" src="../jquery.tablesorter/jquery.tablesorter.js"></script>
<link rel="stylesheet" href="../jquery.tablesorter/themes/blue/style.css" type="text/css" />
<script language="javascript" type="text/javascript" >
$(document).ready(function()
	{
		$("#myTableu1").tablesorter();
		$("#myTableu2").tablesorter();
		$("#myTableu3").tablesorter();
		$("#myTableu4").tablesorter();
		$("#myTableu5").tablesorter();
		$("#myTableu6").tablesorter();
		$("#myTableu7").tablesorter();
		$("#myTableu8").tablesorter();
		$("#myTableu9").tablesorter();
		$("#myTableu10").tablesorter();
		$("#myTableu11").tablesorter();
		$("#myTableu12").tablesorter();
		$("#myTableu13").tablesorter();
		$("#myTableu14").tablesorter();
		$("#myTableu15").tablesorter();
		$("#myTableu16").tablesorter();
		$("#myTableu17").tablesorter();
		$("#myTableu18").tablesorter();
		$("#myTableu19").tablesorter();
		$("#myTableu20").tablesorter();
		$("#myTableu21").tablesorter();
		$("#myTableu22").tablesorter();
       $("#myTableu22").tablesorter();
	}
);
</script>
<?php
/***************************************************************************************
Organización: 	Presidencia del Consejo de Ministros - PCM
Gerencia	: 	Secretaría de Descentralización
Sistema		: 	Sistema Nacional de Información Geográfica - SAYWITE
Coordinador/Desarrollador TIC: Vitaly Uriel Cespedes Reynaga vitalyuri@hotmail.com/vitalyuri@gmail.com/969228151
Periodo		: 	Septiembre 2012 - 2013
***************************************************************************************/
@session_start();
	//include ('conexion_postgres.phtml');
	$linkPG = Conectarse_POSTGRES();
	include ('injection/funciones.php');
	// Browse Data 
	$rsDet = pg_query( $linkPG , "select * from def_tematico where estado = 1;");
	$numcrupostematicos=pg_num_rows($rsDet);
	$titulo = 'Definicionde capas tematicas';
?>
<table  border="0" width="1500px" cellspacing="0" cellpadding="10">
  <tr>
  <td>
	<table width="100%" class="marco_general">
	  <tr><td>
	  	<table width="100%" cellpadding="10" cellspacing="0" bgcolor="#B86D26">
		  <tr>
			<td colspan="7" class="titulo_reporte">Definicionde capas tematicas</td>
		  </tr></table>
		<?php
          $i=0;
          while($i<$numcrupostematicos){
            $j = $i+1;
          	$u='u'.$j;
          	 echo('<table class="marco_individual">
		  <tr>
			<td>
				<div id='.$u.' style="width: 100%;">
					<h1><table width="100%" class="titulo_general">
						  <tr>
							<td>&nbsp;&nbsp;GRUPO TEMATICO '.pg_fetch_result($rsDet,$i,"\"tematico\"").'</td>
						  </tr>
						</table></h1>
					<div>
						<table width="94%" align="center" class="tablesorter" border="1" id="myTable'.$u.'">
							<thead>
							  <tr>
							   <th>N</th>
								<th>Sub tematico</th>
								<th>Capa</th>
								<th>Responsable</th>
								<th>Actualización</th>
								<th>Definición</th>
								<th>escala</th>
								<th>pagweb</th>
								<th>fuente</th>
								<th>annio</th>
								<th>linkmetadatos</th>
								<th>WMS</th>
								<th>Capa</th>
								<th>Con definici&oacute;n</th>
								<th>Total campos</th>
							  </tr>
							</thead>
							<tbody>');
					 $consCapa=pg_query($linkPG,"select c.*,i.* from def_capa c left join def_capa_informacion i on c.idcapa=i.idcapa 
					 	           where c.idtematico=".pg_fetch_result($rsDet,$i,"\"idtematico\"")."
					 	                 order by subtematico,capa;");
							  $k=0;
							  while($k<pg_num_rows($consCapa)){
							  	$l=$k+1;
							  	
							  		$clase='class="lista_titulo"';
							  	
							  	 echo('<tr ><td '.$clase.' align="center">'.$l.'</td>
										<td align="center" class="lista_titulo">'.pg_fetch_result($consCapa,$k,"\"subtematico\"").'</td>
										<td align="center" '.$clase.'>'.pg_fetch_result($consCapa,$k,"\"capa\"").'</td>
										<td align="center" '.$clase.'>'.pg_fetch_result($consCapa,$k,"\"resp_capa\"").'</td>
										<td align="center" '.$clase.'>'.pg_fetch_result($consCapa,$k,"\"cod_user\"").'</td>
										<td '.$clase.' align="center">'.substr(pg_fetch_result($consCapa,$k,"\"definicion\""),0,20).'...</td>
										<td '.$clase.' align="center">'.pg_fetch_result($consCapa,$k,"\"escala\"").'</td>
										<td '.$clase.' align="center">'.pg_fetch_result($consCapa,$k,"\"pagweb\"").'</td>
										<td '.$clase.' align="center">'.substr(pg_fetch_result($consCapa,$k,"\"fuente\""),0,20).'</td>
										<td '.$clase.' align="center">'.pg_fetch_result($consCapa,$k,"\"annio\"").'</td>
										<td '.$clase.' align="center">'.substr(pg_fetch_result($consCapa,$k,"\"linkmetadatos\""),0,20).'</td>
										<td '.$clase.' align="center">'.substr(pg_fetch_result($consCapa,$k,"\"wms\""),0,20).'</td>
										<td '.$clase.' align="center">'.pg_fetch_result($consCapa,$k,"\"capaxml\"").'</td>');
										$consulta_campos=pg_query($linkPG,"SELECT COLUMN_NAME as nombre_campo,DATA_TYPE as tipo_campo FROM information_schema.COLUMNS WHERE TABLE_NAME = '".pg_fetch_result($consCapa,$k,"\"nom_tabla\"")."';");
	$rowsc = pg_num_rows($consulta_campos);
	   $consulta_campos_registrados=pg_query($linkPG,"select count(1) as cantidad from def_dic_tabla where nom_tabla = '".pg_fetch_result($consCapa,$k,"\"nom_tabla\"")."' and def_campo<>''and nom_campo<>'def_tabla'");
	   $rowscr = pg_fetch_result($consulta_campos_registrados,0,"\"cantidad\"");
							  echo('<td '.$clase.' align="center">'.$rowscr.'</td><td '.$clase.' align="center">'.$rowsc.'</td></tr>');
							  	$k++;
							  }
						echo('</tbody>
						</table>
					</div>
				</div>
			</td>
		  </tr>
		</table>');
          	$i++;
          }

		pg_free_result($rsDet);
		pg_free_result($consCapa);
		pg_close($linkPG); 
		?>
		
		</br>
		
		</td></tr>
	</table>
</body>
<script language="javascript" type="text/javascript">
	$(document).ready(function(){
		$("#u1").h2c_acordeon();
		$("#u2").h2c_acordeon();
		$("#u3").h2c_acordeon();
		$("#u4").h2c_acordeon();
		$("#u5").h2c_acordeon();
		$("#u6").h2c_acordeon();
		$("#u7").h2c_acordeon();
		$("#u8").h2c_acordeon();
		$("#u9").h2c_acordeon();
		$("#u10").h2c_acordeon();
		$("#u11").h2c_acordeon();
		$("#u12").h2c_acordeon();
		$("#u13").h2c_acordeon();
		$("#u14").h2c_acordeon();
		$("#u15").h2c_acordeon();
		$("#u16").h2c_acordeon();
		$("#u17").h2c_acordeon();
		$("#u18").h2c_acordeon();
		$("#u19").h2c_acordeon();
		$("#u20").h2c_acordeon();
		$("#u21").h2c_acordeon();
		$("#u22").h2c_acordeon();
		$("#u23").h2c_acordeon();
		$("#u24").h2c_acordeon();
	});
</script>
</html>