<?php

if (isset($_GET['excel']) && ($_GET['excel']=='excel')) {
	header("Content-type:application/x-msexcel");
	$file=$_GET['capa'];
	header("Content-Disposition: attachment; filename=".$file.".xls");
	$imgtitulo='';
} else {
	$imgtitulo='<img src="imajes/desplegable.png" width="11" height="11">';
}


	include ('conexion_postgres.phtml');
	include ('injection/funciones.php');
	$player = limpiarCadena($_GET['olayer']);
	$pcampo = limpiarCadena($_GET['ocampo']);
	$pvalor = limpiarNumeros($_GET['ovalor']);
	$linkPG = Conectarse_POSTGRES();

	$gid = $pvalor;
	// Browse Data
	$sQueryS = "SELECT *";
	$sQueryF = " FROM peru_litologia_0104";
	$sQueryW = " WHERE \"gid\" = '" . $gid . "'";

	$sQuery = $sQueryS . $sQueryF . $sQueryW;
	$rsDet = pg_query( $linkPG , $sQuery );
	
	$titulo_ventana = 'REPORTE DE LITOLOG&Iacute;A ';
		$titulo = 'REPORTE DE LITOLOG&Iacute;A ';
	//$titulo = $name;
	include ('inc/consulta_cabecera.php');
?>

<table width="100%" border="0" cellspacing="0" cellpadding="10">
  <tr><td>
	<table width="100%" class="marco_general">
	  <tr><td>
		<table class="marco_individual">
		  <tr>
			<td>
				<div id="u1" style="width: 100%;">
					<h1><table width="100%" class="titulo_general">
						  <tr>
							<td><?php echo $imgtitulo;?>&nbsp;&nbsp;UBICACI&Oacute;N GEOGR&Aacute;FICA</td>
						  </tr>
						</table></h1>
					<div>
						<table width='100%' align='center' class='general'>
						<thead>
						  <tr>
							<th width="20%">DEPARTAMENTO</th>
							<th width="20%">PROVINCIA</th>
						
						  </tr>
						</thead>
						<tbody>
						  <tr>
						<?php
							print "<td align='center' class='texto'>".pg_fetch_result($rsDet,0,"\"nom_dpto\"")."</td>";
							print "<td align='center' class='texto'>".pg_fetch_result($rsDet,0,"\"nom_prov\"")."</td>";
							
							
						?> 		  
						  </tr>
						</tbody>
						</table>
					</div>
				</div>
			</td>
		  </tr>
		</table>
		<br>
		<table width="100%" class="marco_individual">
		  <tr>
			<td>
				<div id="u2" style="width: 100%;">
					<h1><table width="100%" class="titulo_general">
						  <tr>
							<td><?php echo $imgtitulo;?>&nbsp;&nbsp;DATOS DE LITOLOG&Iacute;A </td>
						  </tr>
						</table></h1>
					<div>
					<table width='100%' align='center' class='general'>
					 
					
						<?php
							print "<tr>";
							print "<td width='50%' class='lista_titulo'><b>Tipo de Roca</b></td>";
							print "<td width='50%' class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"tipo_roca\"")."&nbsp;</td>";
							print "</tr>";
							print "<tr>";
							print "<td class='lista_titulo'><b>Litolog&iacute;a</b></td>";
							print "<td class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"litologia\"")."&nbsp;</td>";
							print "</tr>";
							print "<tr>";
							print "<td class='lista_titulo'><b>Descripci&oacute;n de la Litolog&iacute;a</b></td>";
							print "<td class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"descrip_1\"")."&nbsp;</td>";
							print "</tr>";
							print "<tr>";
							print "<td class='lista_titulo'><b>Era</b></td>";
							print "<td class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"era\"")."&nbsp;</td>";
							print "</tr>";
							print "<tr >";
							print "<td class='lista_titulo'><b>Sistema</b></td>";
							print "<td class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"sistema\"")."&nbsp;</td>";
							print "</tr>";
							print "<tr>";
							print "<td class='lista_titulo'><b>Serie</b></td>";
							print "<td class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"serie\"")."&nbsp;</td>";
							print "</tr>";
							
							
						?>
								
					</table>				
					</div>
				</div>
			</td>
		  </tr>
		</table>
		<br>
		
		
		<?php 
	if(getComDesc($player)!=''){
			include ('inc/descarga.php');	
	}
		?>
		<br>
		<table class='fuente_general' width="100%"><thead><tr><th>Fuentes:
		<br><?php echo pg_fetch_result($rsDet,0,"\"fuente\"").'<br>';?></th></tr></thead>
		</table>
	<?php

	$capa='consulta_litologia_0104';
	if (!isset($_GET['excel'])) {
		//$ruta=$capa.'.phtml?excel=excel&capa='.$capa.'&ovalor='.$pvalor.'&name = '.$name;
		$ruta=$capa.'.phtml?excel=excel&capa='.$capa.'&ovalor='.$pvalor.'&olayer='.$player.'&niv_descarga='.$niv_descarga.'&descarga='.$descarga;
		include 'inc/consulta_pie.php';
	}
	if (isset($_SESSION['usuario'])) {
		grabar_log_accesos('ingreso', $cod_user, $name, $descripcion);
	}
	?>
		</td></tr>
	</table>
	</td></tr>
</table>
</body>
<script language="javascript" type="text/javascript">
	$(document).ready(function(){
	$("#u1").h2c_acordeon();
	$("#u2").h2c_acordeon();
	$("#u3").h2c_acordeon();
	$("#u4").h2c_acordeon();
	$("#u5").h2c_acordeon();
	$("#u6").h2c_acordeon();
	});
</script>
</html> 
