<?php
/***************************************************************************************
Organización: 	Presidencia del Consejo de Ministros - PCM
Gerencia	: 	Secretaría de Descentralización
Sistema		: 	Sistema Nacional de Información Geográfica - SAYWITE
Coordinador/Desarrollador TIC: Vitaly Uriel Cespedes Reynaga vitalyuri@hotmail.com/vitalyuri@gmail.com/969228151
Periodo		: 	Septiembre 2012 - 2013
***************************************************************************************/

if (isset($_GET['excel']) && ($_GET['excel']=='excel')) {
	header("Content-type:application/x-msexcel");
	$file=$_GET['capa'];
	header("Content-Disposition: attachment; filename=".$file.".xls");
	$imgtitulo='';
} else {
	$imgtitulo='<img src="imajes/desplegable.png" width="11" height="11">';
}
	
	include ('conexion_postgres.phtml');
	include ('injection/funciones.php');
	$player = limpiarCadena($_GET['olayer']);
	$pcampo = limpiarCadena($_GET['ocampo']);
	$pvalor = limpiarNumeros($_GET['ovalor']);
	$linkPG = Conectarse_POSTGRES();
	// Browse Data
	$sQueryS = " SELECT *";   
	$sQueryF = " FROM peru_serv_certif_competencia ";
	$sQueryW = " WHERE \"cod_dist\" = '" . $pvalor . "'";

	$sQuery = $sQueryS . $sQueryF . $sQueryW;   
	$rsDet = pg_query( $linkPG , $sQuery );

	$rsDet = pg_query( $linkPG , $sQuery );
	
		$titulo_ventana = 'SERVICIO DE CERTIFICACI&Oacute;N Y COMPETENCIAS - DISTRITO '.pg_fetch_result($rsDet,0,"\"nom_dist\"");
		$titulo = 'SERVICIO DE CERTIFICACI&Oacute;N Y COMPETENCIAS - </br> DISTRITO '.pg_fetch_result($rsDet,0,"\"nom_dist\"");
	
	include ('inc/consulta_cabecera.php');
?>
<table width="100%" border="0" cellspacing="0" cellpadding="10">
  <tr><td>
	<table width="100%" class="marco_general">
	  <tr><td>
		<table class="marco_individual">
		  <tr>
			<td>
				<div id="u1" style="width: 100%;">
					<h1><table width="100%" class="titulo_general">
						  <tr>
							<td><?php echo $imgtitulo;?>&nbsp;&nbsp;UBICACI&Oacute;N GEOGR&Aacute;FICA</td>
						  </tr>
						</table></h1>
					<div>
						<table width='100%' align='center' class='general'>
						<thead>
						  <tr>
							<th width="20%">Ubigeo</th>
							<th width="20%">Departamento</th>
							<th width="20%">Provincia</th>
							<th width="20%">Distrito</th>
							
		
						  </tr>
						</thead>
						<tbody>
						  <tr>
						<?php
							print "<td align='center' class='texto'>".pg_fetch_result($rsDet,0,"\"cod_dist\"")."</td>";
							print "<td align='center' class='texto'>".pg_fetch_result($rsDet,0,"\"nom_dpto\"")."</td>";
							print "<td align='center' class='texto'>".pg_fetch_result($rsDet,0,"\"nom_prov\"")."</td>";
							print "<td align='center' class='texto'>".pg_fetch_result($rsDet,0,"\"nom_dist\"")."</td>";
							
						?> 		  
						  </tr>
						</tbody>
						</table>
					</div>
				</div>
			</td>
		  </tr>
		</table>
		<br>
		<table width="100%" class="marco_individual">
		  <tr>
			<td>
				<div id="u2" style="width: 100%;">
					<h1><table width="100%" class="titulo_general">
						  <tr>
							<td><?php echo $imgtitulo;?>&nbsp;&nbsp;REPORTE </td>
						  </tr>
						</table></h1>
					<div>
					<table width='100%' align='center' class='general'>
					 
					
						<?php
	
								print "<tr>"; print "<td width='50%' class='lista_titulo'><b>CURSOS :	</b></td>"; print "<td width='50%' class='lista_textosub'>Total de beneficiarios</td>"; print "</tr>";
								if (pg_fetch_result($rsDet,0,"\"b1\"")>0){print "<tr>"; print "<td width='50%' class='lista_titulo'><b>	ACONDICIONAMIENTO DE MATERIA PRIMA PARA LA PRODUCCIÓN DE CONSERVAS	</b></td>"; print "<td width='50%' class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"b1\"")."&nbsp;</td>"; print "</tr>";}
								if (pg_fetch_result($rsDet,0,"\"b2\"")>0){print "<tr>"; print "<td width='50%' class='lista_titulo'><b>	ALBAÑILERIA DE EDIFICACIONES	</b></td>"; print "<td width='50%' class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"b2\"")."&nbsp;</td>"; print "</tr>";}
								if (pg_fetch_result($rsDet,0,"\"b3\"")>0){print "<tr>"; print "<td width='50%' class='lista_titulo'><b>	ATENCIÓN EN SALON DE COMIDA  BEBIDAS / EVENTOS	</b></td>"; print "<td width='50%' class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"b3\"")."&nbsp;</td>"; print "</tr>";}
								if (pg_fetch_result($rsDet,0,"\"b4\"")>0){print "<tr>"; print "<td width='50%' class='lista_titulo'><b>	BORDADO PARA CONFECCIÓN TEXTIL	</b></td>"; print "<td width='50%' class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"b4\"")."&nbsp;</td>"; print "</tr>";}
								if (pg_fetch_result($rsDet,0,"\"b5\"")>0){print "<tr>"; print "<td width='50%' class='lista_titulo'><b>	CAJA EN ESTABLECIMIENTOS COMERCIALES	</b></td>"; print "<td width='50%' class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"b5\"")."&nbsp;</td>"; print "</tr>";}
								if (pg_fetch_result($rsDet,0,"\"b6\"")>0){print "<tr>"; print "<td width='50%' class='lista_titulo'><b>	COCINA	</b></td>"; print "<td width='50%' class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"b6\"")."&nbsp;</td>"; print "</tr>";}
								if (pg_fetch_result($rsDet,0,"\"b7\"")>0){print "<tr>"; print "<td width='50%' class='lista_titulo'><b>	CONSTRUCCION DE REDES INTERNAS DE GAS NATURAL RESIDENCIAL Y COMERCIAL	</b></td>"; print "<td width='50%' class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"b7\"")."&nbsp;</td>"; print "</tr>";}
								if (pg_fetch_result($rsDet,0,"\"b8\"")>0){print "<tr>"; print "<td width='50%' class='lista_titulo'><b>	CORTE DE PIEZAS  PARA CONFECCIÓN DE PRENDAS DE VESTIR	</b></td>"; print "<td width='50%' class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"b8\"")."&nbsp;</td>"; print "</tr>";}
								if (pg_fetch_result($rsDet,0,"\"b9\"")>0){print "<tr>"; print "<td width='50%' class='lista_titulo'><b>	COSECHA ­ RECOLECCIÓN DE HORTALIZAS	</b></td>"; print "<td width='50%' class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"b9\"")."&nbsp;</td>"; print "</tr>";}
								if (pg_fetch_result($rsDet,0,"\"b10\"")>0){print "<tr>"; print "<td width='50%' class='lista_titulo'><b>	COSTURA DE PRENDA DE VESTIR	</b></td>"; print "<td width='50%' class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"b10\"")."&nbsp;</td>"; print "</tr>";}
								if (pg_fetch_result($rsDet,0,"\"b11\"")>0){print "<tr>"; print "<td width='50%' class='lista_titulo'><b>	EMPAQUE DE FRUTAS Y HORTALIZAS	</b></td>"; print "<td width='50%' class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"b11\"")."&nbsp;</td>"; print "</tr>";}
								if (pg_fetch_result($rsDet,0,"\"b12\"")>0){print "<tr>"; print "<td width='50%' class='lista_titulo'><b>	ENCOFRADO CON MADERA EN EDIFICACIONES	</b></td>"; print "<td width='50%' class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"b12\"")."&nbsp;</td>"; print "</tr>";}
								if (pg_fetch_result($rsDet,0,"\"b13\"")>0){print "<tr>"; print "<td width='50%' class='lista_titulo'><b>	EVALUACIÓN Y APLICACIÓN FITOSANITARIA	</b></td>"; print "<td width='50%' class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"b13\"")."&nbsp;</td>"; print "</tr>";}
								if (pg_fetch_result($rsDet,0,"\"b14\"")>0){print "<tr>"; print "<td width='50%' class='lista_titulo'><b>	FABRICACIÓN DE CALZADO	</b></td>"; print "<td width='50%' class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"b14\"")."&nbsp;</td>"; print "</tr>";}
								if (pg_fetch_result($rsDet,0,"\"b15\"")>0){print "<tr>"; print "<td width='50%' class='lista_titulo'><b>	FIERRERÍA DE EDIFICACIONES	</b></td>"; print "<td width='50%' class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"b15\"")."&nbsp;</td>"; print "</tr>";}
								if (pg_fetch_result($rsDet,0,"\"b16\"")>0){print "<tr>"; print "<td width='50%' class='lista_titulo'><b>	HOUSEKEEPING	</b></td>"; print "<td width='50%' class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"b16\"")."&nbsp;</td>"; print "</tr>";}
								if (pg_fetch_result($rsDet,0,"\"b17\"")>0){print "<tr>"; print "<td width='50%' class='lista_titulo'><b>	INSTALACIONES ELÉCTRICAS EN EDIFICACIONES	</b></td>"; print "<td width='50%' class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"b17\"")."&nbsp;</td>"; print "</tr>";}
								if (pg_fetch_result($rsDet,0,"\"b18\"")>0){print "<tr>"; print "<td width='50%' class='lista_titulo'><b>	JARDINERÍA	</b></td>"; print "<td width='50%' class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"b18\"")."&nbsp;</td>"; print "</tr>";}
								if (pg_fetch_result($rsDet,0,"\"b19\"")>0){print "<tr>"; print "<td width='50%' class='lista_titulo'><b>	LAVANDERÍA	</b></td>"; print "<td width='50%' class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"b19\"")."&nbsp;</td>"; print "</tr>";}
								if (pg_fetch_result($rsDet,0,"\"b20\"")>0){print "<tr>"; print "<td width='50%' class='lista_titulo'><b>	MAESTRO DE OBRA DE EDIFICACIONES	</b></td>"; print "<td width='50%' class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"b20\"")."&nbsp;</td>"; print "</tr>";}
								if (pg_fetch_result($rsDet,0,"\"b21\"")>0){print "<tr>"; print "<td width='50%' class='lista_titulo'><b>	MANEJO DE CULTIVO DE FRUTAS	</b></td>"; print "<td width='50%' class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"b21\"")."&nbsp;</td>"; print "</tr>";}
								if (pg_fetch_result($rsDet,0,"\"b22\"")>0){print "<tr>"; print "<td width='50%' class='lista_titulo'><b>	MANEJO DE SISTEMAS DE RIEGO TECNIFICADO	</b></td>"; print "<td width='50%' class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"b22\"")."&nbsp;</td>"; print "</tr>";}
								if (pg_fetch_result($rsDet,0,"\"b23\"")>0){print "<tr>"; print "<td width='50%' class='lista_titulo'><b>	OPERACIONES DE ALMACÉN	</b></td>"; print "<td width='50%' class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"b23\"")."&nbsp;</td>"; print "</tr>";}
								if (pg_fetch_result($rsDet,0,"\"b24\"")>0){print "<tr>"; print "<td width='50%' class='lista_titulo'><b>	PANADERIA	</b></td>"; print "<td width='50%' class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"b24\"")."&nbsp;</td>"; print "</tr>";}
								if (pg_fetch_result($rsDet,0,"\"b25\"")>0){print "<tr>"; print "<td width='50%' class='lista_titulo'><b>	PASTELERIA	</b></td>"; print "<td width='50%' class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"b25\"")."&nbsp;</td>"; print "</tr>";}
								if (pg_fetch_result($rsDet,0,"\"b26\"")>0){print "<tr>"; print "<td width='50%' class='lista_titulo'><b>	PULPEADO DE FRUTAS	</b></td>"; print "<td width='50%' class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"b26\"")."&nbsp;</td>"; print "</tr>";}
								if (pg_fetch_result($rsDet,0,"\"b27\"")>0){print "<tr>"; print "<td width='50%' class='lista_titulo'><b>	RECEPCIÓN DE HOTEL/HOSTAL	</b></td>"; print "<td width='50%' class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"b27\"")."&nbsp;</td>"; print "</tr>";}
								if (pg_fetch_result($rsDet,0,"\"b28\"")>0){print "<tr>"; print "<td width='50%' class='lista_titulo'><b>	REPRESENTANTE DE VENTAS	</b></td>"; print "<td width='50%' class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"b28\"")."&nbsp;</td>"; print "</tr>";}
								if (pg_fetch_result($rsDet,0,"\"b29\"")>0){print "<tr>"; print "<td width='50%' class='lista_titulo'><b>	SERVICIO DE LIMPIEZA	</b></td>"; print "<td width='50%' class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"b29\"")."&nbsp;</td>"; print "</tr>";}
								if (pg_fetch_result($rsDet,0,"\"b30\"")>0){print "<tr>"; print "<td width='50%' class='lista_titulo'><b>	TEJIDO A MANO CON FIBRA DE CAMÉLIDOS SUDAMERICANOS Y OTRAS FIBRAS NATURALES	</b></td>"; print "<td width='50%' class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"b30\"")."&nbsp;</td>"; print "</tr>";}
								if (pg_fetch_result($rsDet,0,"\"b31\"")>0){print "<tr>"; print "<td width='50%' class='lista_titulo'><b>	TEJIDO A MANO EN FIBRA DE OVINO Y CAMÉLIDOS SUDAMERICANOS	</b></td>"; print "<td width='50%' class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"b31\"")."&nbsp;</td>"; print "</tr>";}
								if (pg_fetch_result($rsDet,0,"\"b32\"")>0){print "<tr>"; print "<td width='50%' class='lista_titulo'><b>	TRABAJO AL SERVICIO DEL HOGAR	</b></td>"; print "<td width='50%' class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"b32\"")."&nbsp;</td>"; print "</tr>";}
								if (pg_fetch_result($rsDet,0,"\"b33\"")>0){print "<tr>"; print "<td width='50%' class='lista_titulo'><b>	VENTA DE TANGIBLES	</b></td>"; print "<td width='50%' class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"b33\"")."&nbsp;</td>"; print "</tr>";}
								if (pg_fetch_result($rsDet,0,"\"b34\"")>0){print "<tr>"; print "<td width='50%' class='lista_titulo'><b>	VENTAS EN LA PARTICULARIDAD EN VENTAS DE TANGIBLE	</b></td>"; print "<td width='50%' class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"b34\"")."&nbsp;</td>"; print "</tr>";}

						?>
								
					</table>				
					</div>
				</div>
			</td>
		  </tr>
		</table>
		<br>
		
		
		<?php 
	if(getComDesc($player)!=''){
			include ('inc/descarga.php');	
	}
		?>
		<br>
		<table class='fuente_general' width="100%"><thead><tr><th>Fuentes:
		<br><?php echo pg_fetch_result($rsDet,0,"\"fuente\"").'<br>';?></th></tr></thead>
		</table>
	<?php

	$capa='consulta_serv_certif_competencia';
	if (!isset($_GET['excel'])) {
		//$ruta=$capa.'.phtml?excel=excel&capa='.$capa.'&ovalor='.$pvalor.'&name = '.$name;
		$ruta=$capa.'.phtml?excel=excel&capa='.$capa.'&ovalor='.$pvalor.'&olayer='.$player.'&niv_descarga='.$niv_descarga.'&descarga='.$descarga;
		include 'inc/consulta_pie.php';
	}
	if (isset($_SESSION['usuario'])) {
		grabar_log_accesos('ingreso', $cod_user, $name, $descripcion);
	}
	?>
		</td></tr>
	</table>
	</td></tr>
</table>
</body> 
<script language="javascript" type="text/javascript">
	$(document).ready(function(){
		$("#u1").h2c_acordeon();
		$("#u2").h2c_acordeon();
		$("#u3").h2c_acordeon();
		$("#u4").h2c_acordeon();
		$("#u5").h2c_acordeon();
		$("#u6").h2c_acordeon();
	});
</script>
</html>
<?php include_once("./analyticstracking.php");?>