
<?php

if (isset($_GET['excel']) && ($_GET['excel']=='excel')){
	header("Content-type:application/x-msexcel");
	$file=$_GET['capa'];
	header("Content-Disposition: attachment; filename=".$file.".xls");
	$imgtitulo='';
} else{
	$imgtitulo='<img src="imajes/desplegable.png" width="11" height="11">';
}

/*@session_start();
	if(empty($_SESSION['usuario'])){
        header('Location: ../index.php');
	}else{$cod_user = $_SESSION['usuario'];}*/
	include ('conexion_postgres.phtml');
	include ('injection/funciones.php');
	$player = 	limpiarCadena($_GET['olayer']);
	$pcampo = 	limpiarCadena($_GET['ocampo']);
	$pvalor = limpiarCadena(limpiarNumeros($_GET['ovalor']));
	$linkPG = Conectarse_POSTGRES();
	// Browse Data
	$sQueryS = "SELECT *";
	$sQueryF = " FROM vw_peru_actores_politicos_posicion";
	$sQueryW = " WHERE ubigeo = '" . $pvalor . "'";

	$sQuery = $sQueryS . $sQueryF . $sQueryW;
	$rsDet = pg_query( $linkPG , $sQuery );
	$titulo_ventana = 'Actores Políticos';
	$titulo = 'Actores Políticos';
	include ('inc/consulta_cabecera.php');
?>
<table width="100%" border="0" cellspacing="0" cellpadding="10">
  <tr><td>
	<table width="100%" class="marco_general">
	  <tr><td>
		<table width="100%" class="marco_individual">
		  <!--tr>
			<td>
				<table width="100%" class="titulo_general">
				  <tr>
					<td>&nbsp;&nbsp;UBICACI&Oacute;N GEOGR&Aacute;FICA</td>
				  </tr>
				</table>
				<table width='100%' align='center' class='general'>
					<thead>
					  <tr>
						<th width='25%'>Departamento</th>
						<th width='25%'>Provincia</th>
						<th width='25%'>Distrito</th>
						<th width='25%'>Codigo Distrito</th>
					  </tr>
					</thead>
					<tbody>
					<tr>
						<td align='center' class='texto'><?php echo(pg_fetch_result($rsDet,0,"\"nom_dpto\"")) ?></td>
						<td align='center' class='texto'><?php echo(pg_fetch_result($rsDet,0,"\"nom_prov\"")) ?></td>
						<td align='center' class='texto'><?php echo(pg_fetch_result($rsDet,0,"\"nom_dist\"")) ?></td>
						<td align='center' class='texto'><?php echo(pg_fetch_result($rsDet,0,"\"cod_dist\"")) ?></td>
					</tr>
	
					</tbody>
				</table>
			</td>
		  </tr-->
		</table>
		<br>
		<table width="100%" class="marco_individual">
		  <tr>
			<td>
				<table width="100%" class="titulo_general">
					  <tr>
						<td>&nbsp;&nbsp;DATOS GENERALES</td>
					  </tr>
				</table>
			<table width='100%' align='center' class='general'>
		<?php
        print "
        <tr>
        <td width='50%' class='lista_titulo'>Apellidos y Nombres:</td>
        <td width='50%' class='texto1'>".pg_fetch_result($rsDet,0,"\"ape_nom\"")."</td>
      </tr>
        <tr>
				<td width='50%' class='lista_titulo'>Cargo:</td>
				<td width='50%' class='texto1'>".pg_fetch_result($rsDet,0,"\"cargo\"")."</td>
			  </tr>
			  <tr>
				<td class='lista_titulo'>Agrupación Política de Candidato:</td>
                <td class='texto1'>".pg_fetch_result($rsDet,0,"\"agp\"")."</td>
			  </tr>
			  <tr>
				<td class='lista_titulo'>Actual Situación Política (Independiente, Militante):</td>
				<td class='texto1'>".pg_fetch_result($rsDet,0,"\"asp\"")."</td>
              </tr>
              <tr>
                <td class='lista_titulo'>Si es Militante, de Qué Grupo Político:</td>
                <td class='texto1'>".pg_fetch_result($rsDet,0,"\"m\"")."</td>
              </tr>
              <tr>
                <td class='lista_titulo'>Porcentaje de Elección:</td>
                <td class='texto1'>".number_format(pg_fetch_result($rsDet,0,"\"pe\""),2)." %</td>
              </tr>

              <tr>
                <td class='lista_titulo'>Calificación de Legitimidad de Origen (Alto, Medio, Bajo):</td>
                <td class='texto1'>".pg_fetch_result($rsDet,0,"\"cl\"")."</td>
              </tr>

              <tr>
                <td class='lista_titulo'>Cuestionamientos por Gestión o Corrupción (Si, No):</td>
               <td class='texto1'>".pg_fetch_result($rsDet,0,"\"cues\"")."</td>
              </tr>

              <tr>
                <td class='lista_titulo'>Si es Sí (Cuál  Cuáles):</td>
                <td class='texto1'>"
                    .pg_fetch_result($rsDet,0,"\"siessi\"").
                    "<br>"
                    .pg_fetch_result($rsDet,0,"\"siessi1\"").
                "</td>
              </tr>

              <tr>
                <td class='lista_titulo'>Posición en General Frente al Ejecutivo (3 Categorías):</td>
                <td class='texto1'>".pg_fetch_result($rsDet,0,"\"pg\"")."</td>
              </tr>

              <tr>
              <td class='lista_titulo'>Posición Actual Frente al Conflicto (3 Categorías):</td>
              <td class='texto1'>".pg_fetch_result($rsDet,0,"\"pfc\"")."</td>
            </tr>


			";
		?>
			</table>
			</td>
		  </tr>
		</table>
		<br>
		
		<table class='fuente_general' width="100%"><thead><tr><th><b>Fuente:</b>
			<br><?php echo pg_fetch_result($rsDet,0,"\"fuente\"");?></th></tr></thead>
		</table>
	<?php
	//$name=strtoupper(pg_fetch_result($rsDet,0,"\"tipoaerona\"").' - '.pg_fetch_result($rsDet,0,"\"label\""));
	$name='Actores Políticos';
	$capa='consulta_actores_politicos';
	if (!isset($_GET['excel'])) {
		$ruta=$capa.'.phtml?excel=excel&capa='.$capa.'&ovalor='.$pvalor.'&olayer=peru_actores_politicos'.'&ocampo=gid';
		include 'inc/consulta_pie.php';
	}
	if (isset($_SESSION['usuario'])) {
		grabar_log_accesos('ingreso', $cod_user, $name, $descripcion);
	}
	?>
		</td>
	  </tr>
	</table>
	</td>
  </tr>
</table>
</body>
</html>
<?php include_once("./analyticstracking.php");?>


