
<?php

if (isset($_GET['excel']) && ($_GET['excel']=='excel')){
	header("Content-type:application/x-msexcel");
	$file=$_GET['capa'];
	header("Content-Disposition: attachment; filename=".$file.".xls");
	$imgtitulo='';
} else{
	$imgtitulo='<img src="imajes/desplegable.png" width="11" height="11">';
}

/*@session_start();
	if(empty($_SESSION['usuario'])){
        header('Location: ../index.php');
	}else{$cod_user = $_SESSION['usuario'];}*/
	include ('conexion_postgres.phtml');
	include ('injection/funciones.php');
	$player = 	limpiarCadena($_GET['olayer']);
	$pcampo = 	limpiarCadena($_GET['ocampo']);
	$pvalor = limpiarCadena(limpiarNumeros($_GET['ovalor']));
	$linkPG = Conectarse_POSTGRES();
	// Browse Data
	$sQueryS = "SELECT *";
	$sQueryF = " FROM ".$player;
	$sQueryW = " WHERE gid = '" . $pvalor . "'";

	$sQuery = $sQueryS . $sQueryF . $sQueryW;
	$rsDet = pg_query( $linkPG , $sQuery );
	$titulo_ventana = 'Centros de Servicios al Contribuyente';
	$titulo = 'Centros de Servicios al Contribuyente';
	include ('inc/consulta_cabecera.php');
?>
<table width="100%" border="0" cellspacing="0" cellpadding="10">
  <tr><td>
	<table width="100%" class="marco_general">
	  <tr><td>
		<table width="100%" class="marco_individual">
		  <!--tr>
			<td>
				<table width="100%" class="titulo_general">
				  <tr>
					<td>&nbsp;&nbsp;UBICACI&Oacute;N GEOGR&Aacute;FICA</td>
				  </tr>
				</table>
				<table width='100%' align='center' class='general'>
					<thead>
					  <tr>
						<th width='25%'>Departamento</th>
						<th width='25%'>Provincia</th>
						<th width='25%'>Distrito</th>
						<th width='25%'>Codigo Distrito</th>
					  </tr>
					</thead>
					<tbody>
					<tr>
						<td align='center' class='texto'><?php echo(pg_fetch_result($rsDet,0,"\"nom_dpto\"")) ?></td>
						<td align='center' class='texto'><?php echo(pg_fetch_result($rsDet,0,"\"nom_prov\"")) ?></td>
						<td align='center' class='texto'><?php echo(pg_fetch_result($rsDet,0,"\"nom_dist\"")) ?></td>
						<td align='center' class='texto'><?php echo(pg_fetch_result($rsDet,0,"\"cod_dist\"")) ?></td>
					</tr>
	
					</tbody>
				</table>
			</td>
		  </tr-->
		</table>
		<br>
		<table width="100%" class="marco_individual">
		  <tr>
			<td>
				<table width="100%" class="titulo_general">
					  <tr>
						<td>&nbsp;&nbsp;DATOS DEL CENTRO DE SERVICIO</td>
					  </tr>
				</table>
			<table width='100%' align='center' class='general'>
		<?php
        print "
        <tr>
        <td width='50%' class='lista_titulo'>Centro de Servicio:</td>
        <td width='50%' class='texto1'>".pg_fetch_result($rsDet,0,"\"cent_serv\"")."</td>
      </tr>
        <tr>
				<td width='50%' class='lista_titulo'>Dirección del Centro de Servicio:</td>
				<td width='50%' class='texto1'>".pg_fetch_result($rsDet,0,"\"direcc\"")."</td>
			  </tr>
			  <tr>
				<td class='lista_titulo'>Plano de ubicación:</td>
                <td class='texto1'>  <a href='".pg_fetch_result($rsDet,0,"\"url\"")."' target='_blank'>Url</a> </td>
				
			  </tr>
			  <tr>
				<td class='lista_titulo'>Horario de atención de lunes a viernes:</td>
				<td class='texto1'>".pg_fetch_result($rsDet,0,"\"at_lun_vie\"")."</td>
              </tr>
              <tr>
                <td class='lista_titulo'>Horario de atención sábado:</td>
                <td class='texto1'>".pg_fetch_result($rsDet,0,"\"aten_sab\"")."</td>
              </tr>
              <tr>
                <td class='lista_titulo'>Horario de atención domingo:</td>
                <td class='texto1'>".pg_fetch_result($rsDet,0,"\"aten_dom\"")."</td>
              </tr>

              <tr>
                <td class='lista_titulo'>Servicio de trámite:</td>
                <td class='texto1'>".pg_fetch_result($rsDet,0,"\"tramite\"")."</td>
              </tr>

              <tr>
                <td class='lista_titulo'>Servicio de orientación:</td>
               <td class='texto1'>".pg_fetch_result($rsDet,0,"\"orientac\"")."</td>
              </tr>

			  <tr>
                <td class='lista_titulo'>Servicio de cabinas:</td>
               <td class='texto1'>".pg_fetch_result($rsDet,0,"\"cabinas\"")."</td>
              </tr>

			  <tr>
			  <td class='lista_titulo'>Servicio de Mesa de Partes:</td>
			 <td class='texto1'>".pg_fetch_result($rsDet,0,"\"mes_partes\"")."</td>
			</tr>

              <tr>
              <td class='lista_titulo'>obs:</td>
              <td class='texto1'>".pg_fetch_result($rsDet,0,"\"obs\"")."</td>
            </tr>


			";
		?>
			</table>
			</td>
		  </tr>
		</table>
		<br>
		
		<table class='fuente_general' width="100%"><thead><tr><th><b>Fuente:</b>
			<br><?php echo pg_fetch_result($rsDet,0,"\"fuente\"");?></th></tr></thead>
		</table>
	<?php
	//$name=strtoupper(pg_fetch_result($rsDet,0,"\"tipoaerona\"").' - '.pg_fetch_result($rsDet,0,"\"label\""));
	$name='Centros de Servicios al Contribuyente';
	$capa=$player;
	if (!isset($_GET['excel'])) {
		$ruta=$capa.'.phtml?excel=excel&capa='.$capa.'&ovalor='.$pvalor.'&olayer='.$player.'&ocampo=gid';
		include 'inc/consulta_pie.php';
	}
	if (isset($_SESSION['usuario'])) {
		grabar_log_accesos('ingreso', $cod_user, $name, $descripcion);
	}
	?>
		</td>
	  </tr>
	</table>
	</td>
  </tr>
</table>
</body>
</html>
<?php include_once("./analyticstracking.php");?>


