<?php

if (isset($_GET['excel']) && ($_GET['excel']=='excel')) {
	header("Content-type:application/x-msexcel");
	$file=$_GET['capa'];
	header("Content-Disposition: attachment; filename=".$file.".xls");
	$imgtitulo='';
} else {
	$imgtitulo='<img src="imajes/desplegable.png" width="11" height="11">';
}

// @session_start();

// 	if(empty($_SESSION['usuario'])){
//         header('Location: ../index.php');
// 		}else{$cod_user = $_SESSION['usuario'];}

	include ('conexion_postgres.phtml');
	include ('injection/funciones.php');
	$player = limpiarCadena($_GET['olayer']);
	$pcampo = limpiarCadena($_GET['ocampo']);
	$pvalor = limpiarNumeros($_GET['ovalor']);
	$linkPG = Conectarse_POSTGRES();
	if($pvalor==''){
		$gid = $_GET['codigo'];
	}else {
		$gid = $pvalor;
	}
	// Browse Data
	$sQueryS = "SELECT *";
	$sQueryF = " FROM peru_establecimientos_salud";
	$sQueryW = " WHERE \"est_coduni\" = '" . $gid. "' limit 1";
	$sQuery = $sQueryS . $sQueryF . $sQueryW;
	$rsDet = pg_query( $linkPG , $sQuery );
	$titulo_ventana = 'INFORMACI&Oacute;N DE ESTABLECIMIENTO DE SALUD';
	$titulo = 'INFORMACI&Oacute;N DE ESTABLECIMIENTOS DE SALUD - DISTRITO - '. pg_fetch_result($rsDet,0,"\"nom_dist\"");
	include ('inc/consulta_cabecera.php');
?>
<table width="100%" border="0" cellspacing="0" cellpadding="10">
  <tr><td>
	<table width="100%" class="marco_general">
	  <tr><td>
		<table class="marco_individual">
		  <tr>
			<td>
				<div id="u1" style="width: 100%;">
					<h1>
						<table width="100%" class="titulo_general">
						  <tr>
							<td colspan="7"><?php echo $imgtitulo;?>&nbsp;&nbsp;UBICACI&Oacute;N GEOGR&Aacute;FICA</td>
						  </tr>
						</table>
					</h1>
				<div>
					<table width='100%' align='center' class='general'>
						<thead>
							<th width='20%'><?php echo( getTablaCampo('peru_instituciones_salud','nom_dpto'));?></th>
							<th width='20%'><?php echo( getTablaCampo('peru_instituciones_salud','nom_prov'));?></th>
							<th width='20%'><?php echo( getTablaCampo('peru_instituciones_salud','nom_dist'));?></th>
						</thead>
						<tbody>
						<?php
							print "<tr>
									<td align='center' class='numero1'>".pg_fetch_result($rsDet,0,"\"nom_dpto\"")."</td>
									<td align='center' class='numero1'>".pg_fetch_result($rsDet,0,"\"nom_prov\"")."</td>
									<td align='center' class='numero1'>".pg_fetch_result($rsDet,0,"\"nom_dist\"")."</td>
								</tr>";
						?>
						</tbody>
					</table>
				</div>
				</div>
			</td>
		  </tr>
		</table>
		<br>
		<table width="100%" class="marco_individual">
		  <tr>
			<td>
				<div id="u2" style="width: 100%;">
					<h1>
						<table width="100%" class="titulo_general">
						  <tr>
							<td  colspan="7"><?php echo $imgtitulo;?>&nbsp;&nbsp;DATOS DE  <?php echo(pg_fetch_result($rsDet,0,"\"desc_eess\"")); ?></td>
						  </tr>
						</table>
					</h1>
				<div>
					<table width='100%' align='center' class='listado'>
						<?php
		  		print "<tr>";
				print "<td width='50%' class='lista_titulo'>".getTablaCampo('peru_instituciones_salud','est_nombre')."</td>";
				print "<td width='50%' class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"est_nombre\"")."</td>";
		  		print "</tr>";
		  		print "<tr>";
				print "<td width='50%' class='lista_titulo'>".getTablaCampo('peru_instituciones_salud','est_direcc')."</td>";
				print "<td width='50%' class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"est_direcc\"")."</td>";
		  		print "</tr>";
				print "<tr>";
				print "<td width='50%' class='lista_titulo'>".getTablaCampo('peru_instituciones_salud','cod_ipress')."</td>";
				print "<td width='50%' class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"cod_ipress\"")."</td>";
		  		print "</tr>";
                print "<tr>";
				print "<td width='50%' class='lista_titulo'>".getTablaCampo('peru_instituciones_salud','ctg_codigo')."</td>";
				print "<td width='50%' class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"ctg_codigo\"")."</td>";
		  		print "</tr>";
		  		print "<tr>";
				print "<td width='50%' class='lista_titulo'>".getTablaCampo('peru_instituciones_salud','tipo_estab')."</td>";
				print "<td width='50%' class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"tipo_estab\"")."</td>";
		  		print "</tr>";
				print "<tr>";
				print "<td width='50%' class='lista_titulo'>Nombre de la subcategor&iacute;a (Clasificaci&oacute;n)</td>";
				print "<td width='50%' class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"desc_eess\"")."</td>";
		  		print "</tr>";
                print "<tr>";
				print "<td width='50%' class='lista_titulo'>".getTablaCampo('peru_instituciones_salud','est_estado')."</td>";
				print "<td width='50%' class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"est_estado\"")."</td>";
		  		print "</tr>";
		  		print "<tr>";
				print "<td width='50%' class='lista_titulo'>".getTablaCampo('peru_instituciones_salud','est_condic')."</td>";
				print "<td width='50%' class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"est_condic\"")."</td>";
		  		print "</tr>";
				print "<tr>";
				print "<td width='50%' class='lista_titulo'>".getTablaCampo('peru_instituciones_salud','conect')."</td>";
				print "<td width='50%' class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"conect\"")."</td>";
		  		print "</tr>";
				print "<tr>";
				print "<td width='50%' class='lista_titulo'>".getTablaCampo('peru_instituciones_salud','tecno')."</td>";
				print "<td width='50%' class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"tecno\"")."</td>";
		  		print "</tr>";
				print "<tr>";
				print "<td width='50%' class='lista_titulo'>".getTablaCampo('peru_instituciones_salud','operador')."</td>";
				print "<td width='50%' class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"operador\"")."</td>";
		  		print "</tr>";

				print "<tr>";
				print "<td width='50%' class='lista_titulo'>Cuenta con servicio de Telemedicina</td>";
				print "<td width='50%' class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"eess_telem\"")."</td>";
				print "</tr>";

				print "<tr>";
				print "<td width='50%' class='lista_titulo'>".getTablaCampo('peru_instituciones_salud','disa_nombr')."</td>";
				print "<td width='50%' class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"disa_nombr\"")."</td>";
		  		print "</tr>";

                print "<tr>";
				print "<td width='50%' class='lista_titulo'>".getTablaCampo('peru_instituciones_salud','redtdscl')."</td>";
				print "<td width='50%' class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"redtdscl\"")."</td>";
		  		print "</tr>";
		  		print "<tr>";
				print "<td width='50%' class='lista_titulo'>".getTablaCampo('peru_instituciones_salud','mretdscl')."</td>";
				print "<td width='50%' class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"mretdscl\"")."</td>";
		  		print "</tr>";
				print "<tr>";
				print "<td width='50%' class='lista_titulo'>".getTablaCampo('peru_instituciones_salud','institucio')."</td>";
				print "<td width='50%' class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"institucio\"")."</td>";
		  		print "</tr>";
                print "<tr>";
				print "<td width='50%' class='lista_titulo'>".getTablaCampo('peru_instituciones_salud','est_telf')."</td>";
				print "<td width='50%' class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"est_telf\"")."</td>";
		  		print "</tr>";
                print "<tr>";
				print "<td width='50%' class='lista_titulo'>Grupo objetivo del establecimiento</td>";
				print "<td width='50%' class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"est_grupoo\"")."</td>";
		  		print "</tr>";
                print "<tr>";
				print "<td width='50%' class='lista_titulo'>".getTablaCampo('peru_instituciones_salud','est_ambien')."</td>";
				print "<td width='50%' class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"est_ambien\"")."</td>";
		  		print "</tr>";
                print "<tr>";
				print "<td width='50%' class='lista_titulo'>".getTablaCampo('peru_instituciones_salud','est_horari')."</td>";
				print "<td width='50%' class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"est_horari\"")."</td>";
		  		print "</tr>";
?>
					</table>
				</div>
				</div>
			</td>
		  </tr>
		</table>
		<br>
		<table width="100%" class="marco_individual">
		  <tr>
			<td>
				<div id="u3" style="width: 100%;">
					<h1>
						<table width="100%" class="titulo_general">
							<tr>
								<td colspan="7"><?php echo $imgtitulo;?>&nbsp;&nbsp;ESTABLECIMIENTOS DE SALUD - DISTRITO <?php print pg_fetch_result($rsDet,0,"\"nom_dist\"");?></td>
							</tr>
						</table>
					</h1>
				<div>

			<?php
				echo('<table width="100%" align="center" class="general">
						<tr><td width="50%" class="titulosub">Nombre establecimiento</td>');
				$cabecera_tabla = '<td width="10%" class="titulosub">Hospital</td>
						<td width="10%" class="titulosub">Instituto</td>
						<td width="10%" class="titulosub">Centro de Salud</td>
						<td width="10%" class="titulosub">Puesto de Salud</td>
						<td width="10%" class="titulosub">Otros</td></tr>';
	//lista de centros de atencion por distrito
				echo($cabecera_tabla);
				$distQuery		=	"select est_coduni, est_nombre, cod_eess, cod_dist from peru_establecimientos_salud where cod_dist ='".pg_fetch_result($rsDet,0,"\"cod_dist\"")."'  group by 1,2,3,4 order by cod_dist";
				$rsDetDist 		= 	pg_query($linkPG , $distQuery);
				$numrowsDist 	= 	pg_num_rows($rsDetDist);
				$i=0;
				$j=1;
				while($i<$numrowsDist){
				if(pg_fetch_result($rsDetDist,$i,"\"est_coduni\"")==pg_fetch_result($rsDet,0,"\"est_coduni\"")){
					$classet='class="titulo11"';
					$classe='align="center" class="titulo11"';
				} else {
					$classet='class="titulo111"';
					$classe='class="textosub"';
				}
				if (isset($_GET['excel']) && ($_GET['excel']=='excel')) {
					$enlace=$j;
				} else {
					$enlace='<a href="consulta_instituciones_salud.phtml?olayer='.$_GET["olayer"].'&ocampo='.$pcampo.'&ovalor='.pg_fetch_result($rsDetDist,$i,"\"est_coduni\"").'">'.$j.'</a>';
				}
					echo('<tr><td '.$classet.'>'.$enlace.'-  '.pg_fetch_result($rsDetDist,$i,"\"est_nombre\"").'</td>');
					$cod_clasif = pg_fetch_result($rsDetDist,$i,"\"cod_eess\"");
		for($checking=1;$checking<=5;$checking++){
			if($checking==1){
					if($cod_clasif==1){
						$imagen = '<img src="imajes/check.png"" width="15" height="15"/>';
					} else {
						$imagen='';
					}
				}else if($checking==2){
					if($cod_clasif==2){
						$imagen = '<img src="imajes/check.png"" width="15" height="15"/>';
					} else {
						$imagen='';
					}
				}else if($checking==3){
					if($cod_clasif==3){
						$imagen = '<img src="imajes/check.png"" width="15" height="15"/>';
					} else {
						$imagen='';
					}
				}else if($checking==4){
					if($cod_clasif==4){
						$imagen = '<img src="imajes/check.png"" width="15" height="15"/>';
					} else {
						$imagen='';
					}
				}else if($checking==5){
					if($cod_clasif==99){
						$imagen = '<img src="imajes/check.png"" width="15" height="15"/>';
					} else {
						$imagen='';
					}
				}
				echo('<td '.$classe.'>'.$imagen.'</td>');
		}

		$i++;
		$j++;
		echo('</tr>');
	}
	echo('<tr><td class="titulosub">Total</td>');
	for($q=1;$q<=5;$q++){
		if($q ==1){
			$classe='class="titulo11"';
			$where = ' and cod_eess  in (1)';
		} else  if($q ==2){
			$classe='class="titulo11"';
			$where = ' and cod_eess  in (2)';
		} else 	if($q ==3){
			$classe='class="titulo11"';
			$where = ' and cod_eess  in (3)';
		} else if($q ==4){
			$classe='class="titulo11"';
			$where = ' and cod_eess  in (4)';
		}
		 else if($q ==5){
			$classe='class="titulo11"';
			$where = ' and cod_eess  in (99)';
		}
		$cantidad= "select count(distinct(est_coduni)) as cantidad from peru_establecimientos_salud where cod_dist ='".pg_fetch_result($rsDet,0,"\"cod_dist\"")."' ".$where." ;";
		$rsDetCantidad = pg_query($linkPG , $cantidad);
		$total=pg_fetch_result($rsDetCantidad,0,"\"cantidad\"");
		echo('<td class="titulosub">'.$total.'</td>');
	}
	echo('</tr>');
?>
						</table>
					</div>
				</div>
			</td>
		  </tr>
		</table>
		<br>
		<table width="100%" class="marco_individual">
		  <tr>
			<td colspan="7">
				<div id="u4" style="width: 100%;">
					<h1><table width="100%" class="titulo_general">
						  <tr>
							<td><?php echo $imgtitulo;?>&nbsp;&nbsp;ESTABLECIMIENTOS DE SALUD - PROVINCIA <?php print pg_fetch_result($rsDet,0,"\"nom_prov\"");?></td>
						  </tr>
						</table></h1>
					<div>
					<?php
	echo('<table width="100%" align="center" class="general">
						<tr><td width="50%" class="titulosub">Nombre Distritos</td>');
	echo($cabecera_tabla);
//lista de distritos de la provincia
	$provQuery="select count(cod_dist) as cantdist, nom_dist,cod_dist from peru_establecimientos_salud where cod_prov ='".pg_fetch_result($rsDet,0,"\"cod_prov\"")."' group by cod_dist,nom_dist";
	$rsDetprov = pg_query($linkPG , $provQuery);
    $numrowsprov = pg_num_rows($rsDetprov);
	$m=0;
	$n=1;
	$total_hospital		=	0;
	$total_instituto	=	0;
	$total_centro		=	0;
	$total_puesto		=	0;
	$total_otros		=	0;

	while($m<$numrowsprov){
	if(pg_fetch_result($rsDetprov,$m,"\"cod_dist\"")==pg_fetch_result($rsDet,0,"\"cod_dist\"")){
			$classet='class="titulo11"';
			$classe='align="center" class="titulo11"';
	} else {
			$classet='class="titulo111"';
			$classe='class="textosub"';
	}
	echo('<tr><td '.$classet.'>'.$n.'- '.pg_fetch_result($rsDetprov,$m,"\"nom_dist\"").'</td>');
	for($d=1;$d<=5; $d++){
		if($d ==1){
			$whered = ' and cod_eess  in (1)';
		} else  if($d ==2){
			$whered = ' and cod_eess  in (2)';
		} else 	if($d ==3){
			$whered = ' and cod_eess  in (3)';
		} else if($d ==4){
			$whered = ' and cod_eess  in (4)';
		}else if($d ==5){
			$whered = ' and cod_eess  in (99)';
		}
		$consultaDisxP = "select count(distinct(est_coduni)) as cantidaddistxprov
									from peru_establecimientos_salud
									where 	cod_dist ='".pg_fetch_result($rsDetprov,$m,"\"cod_dist\"")."' ".$whered.";";
		$cantiDiss = pg_query($linkPG , $consultaDisxP);
		echo('<td '.$classe.'>'.pg_fetch_result($cantiDiss,0,"\"cantidaddistxprov\"").'</td>');
			if($d==1){
				$total_hospital = $total_hospital + pg_fetch_result($cantiDiss,0,"\"cantidaddistxprov\"");
			}else if($d==2){
				$total_instituto = $total_instituto + pg_fetch_result($cantiDiss,0,"\"cantidaddistxprov\"");
			}else if($d==3){
				$total_centro = $total_centro + pg_fetch_result($cantiDiss,0,"\"cantidaddistxprov\"");
			}else if($d==4){
				$total_puesto = $total_puesto + pg_fetch_result($cantiDiss,0,"\"cantidaddistxprov\"");
			}else if($d==5){
				$total_otros = $total_otros + pg_fetch_result($cantiDiss,0,"\"cantidaddistxprov\"");
			}
	}
	$m++;
	$n++;
	echo('</tr>');
}
echo('<tr><td class="titulosub">Total</td><td class="titulosub">'.$total_hospital.'</td><td class="titulosub">'.$total_instituto.'</td><td class="titulosub">'.$total_centro.'</td><td class="titulosub">'.$total_puesto.'</td><td class="titulosub">'.$total_otros.'</td>');

echo('</tr>');
?>
						</table>
					</div>
				</div>
			</td>
		  </tr>
		</table>
		<br>
		<table width="100%" class="marco_individual">
		  <tr>
			<td >
				<div id="u5" style="width: 100%;">
					<h1><table width="100%" class="titulo_general">
						  <tr>
							<td colspan="7"><?php echo $imgtitulo;?>&nbsp;&nbsp;ESTABLECIMIENTOS DE SALUD - DEPARTAMENTO <?php print pg_fetch_result($rsDet,0,"\"nom_dpto\"");?></td>
						  </tr>
						</table></h1>
					<div>
<?php
//lista de  provincias a nivel regional
echo('<table width="100%" align="center" class="general">
						<tr><td width="50%" class="titulosub">Nombre Provincia</td>');

echo($cabecera_tabla);
	$depQuery="select count(cod_prov) as cantprov, nom_prov,cod_prov from peru_establecimientos_salud where cod_dpto ='".pg_fetch_result($rsDet,0,"\"cod_dpto\"")."' group by cod_prov,nom_prov";
	$rsDetprovxdep = pg_query($linkPG , $depQuery);
    $numrowsprov = pg_num_rows($rsDetprovxdep);
$r=0;
$s=1;
$total_hospitalv	=	0;
$total_institutov	=	0;
$total_centrov		=	0;
$total_puestov		=	0;
$total_otrosv		=	0;
while($r<$numrowsprov){
	if(pg_fetch_result($rsDetprovxdep,$r,"\"cod_prov\"")==pg_fetch_result($rsDet,0,"\"cod_prov\"")){
		$classet='class="titulo11"';
		$classe='align="center" class="titulo11"';
	} else {
		$classet='class="titulo111"';
		$classe='class="textosub"';
	}
	echo('<tr><td '.$classet.'>'.$s.'- '.pg_fetch_result($rsDetprovxdep,$r,"\"nom_prov\"").'</td>');
	for($v=1;$v<=5; $v++){
		if($v ==1){
			$whered = ' and cod_eess  in (1)';
		} else  if($v ==2){
			$whered = ' and cod_eess  in (2)';
		} else 	if($v ==3){
			$whered = ' and cod_eess  in (3)';
		} else if($v ==4){
			$whered = ' and cod_eess  in (4)';
		} else if($v ==5){
			$whered = ' and cod_eess  in (99)';
		}
		$consultaDisxP = "select count(distinct(est_coduni)) as cantdistxprov
							from peru_establecimientos_salud
							where cod_prov ='".pg_fetch_result($rsDetprovxdep,$r,"\"cod_prov\"")."' ".$whered.";";
		$cantiDiss = pg_query($linkPG , $consultaDisxP);
		echo('<td '.$classe.'>'.pg_fetch_result($cantiDiss,0,"\"cantdistxprov\"").'</td>');
		if($v==1){
			$total_hospitalv = $total_hospitalv + pg_fetch_result($cantiDiss,0,"\"cantdistxprov\"");
		}else if($v==2){
			$total_institutov = $total_institutov + pg_fetch_result($cantiDiss,0,"\"cantdistxprov\"");
		}else if($v==3){
			$total_centrov = $total_centrov + pg_fetch_result($cantiDiss,0,"\"cantdistxprov\"");
		}else if($v==4){
			$total_puestov = $total_puestov + pg_fetch_result($cantiDiss,0,"\"cantdistxprov\"");
		}else if($v==5){
			$total_otrosv = $total_otrosv + pg_fetch_result($cantiDiss,0,"\"cantdistxprov\"");
		}
	}
	$r++;
	$s++;
	echo('</tr>');
}
echo('<tr><td class="titulosub">Total</td><td class="titulosub">'.$total_hospitalv.'</td><td class="titulosub">'.$total_institutov.'</td><td class="titulosub">'.$total_centrov.'</td><td class="titulosub">'.$total_puestov.'</td><td class="titulosub">'.$total_otrosv.'</td></tr>');
?>
					</table>
					</div>
				</div>
			</td>
		  </tr></table>
		<?php
	if(getComDesc($player)!=''){
			include ('inc/descarga.php');
	}
		?>
		</br>


		<?php

		$no_imag = pg_fetch_result($rsDet,0,"\"no_imag\"");
		$no_imag2 = pg_fetch_result($rsDet,0,"\"no_imag2\"");
		$no_imag3 = pg_fetch_result($rsDet,0,"\"no_imag3\"");
		$part1 =  '<td valign="top"><img src="./repository/est_salud/';
		$part2 = '"></td>';
		?>

			<table class="marco_individual">
		  <tr>
			<td>
				<div id="u1" style="width: 100%;">
					<h1>
						<table width="100%" class="titulo_general">
						  <tr>
							<td colspan="7"><?php echo $imgtitulo;?>&nbsp;&nbsp;Im&aacute;genes establecimiento de salud</td>
						  </tr>
						</table>
					</h1>
				<div>
					<table width="100%" align='center' class="general">
						<tr>

							<?php

							function exi ($url){
								if ($url !='' && file_exists('./repository/est_salud/'.$url)) {
								    return true;
								} else {
								    return false;
								}
							}



							if (exi($no_imag) && exi($no_imag2) && exi($no_imag3)){
								if (exi($no_imag)){ echo $part1.$no_imag.$part2; }
								if (exi($no_imag2)){ echo $part1.$no_imag2.$part2 ;}
								if (exi($no_imag3)){ echo $part1.$no_imag3.$part2 ;}
							} else {
								echo '<h5>No se encontraron imágenes</h5>';
							}
							?>
						</tr>
					</table>
				</div>
				</div>
			</td>
		  </tr>
		</table>

		</br>
		<table class='fuente_general' width="100%"><thead><tr><th><b>Fuente:</b>
			<br><?php echo pg_fetch_result($rsDet,0,"\"fuente\"");?></th></tr></thead>
		</table>
	<?php
	$name=strtoupper(pg_fetch_result($rsDet,0,"\"clasificac\"").' '.pg_fetch_result($rsDet,0,"\"est_nombre\""));
	$capa='consulta_instituciones_salud';
	if (!isset($_GET['excel'])) {
		$ruta=$capa.'.phtml?excel=excel&capa='.$capa.'&ovalor='.$pvalor.'&olayer='.$player.'&niv_descarga='.$niv_descarga.'&descarga='.$descarga;
		include 'inc/consulta_pie.php';
	}

		if (isset($_SESSION['usuario'])) {
		grabar_log_accesos('ingreso', $cod_user, $name, $descripcion);
	}

		?>
		</td>
	</tr>
</table>
</td>
	</tr>
</table>
</body>
<script language="javascript" type="text/javascript">
	$(document).ready(function(){
		$("#u1").h2c_acordeon();
		$("#u2").h2c_acordeon();
		$("#u3").h2c_acordeon();
		$("#u4").h2c_acordeon();
		$("#u5").h2c_acordeon();
		$("#u6").h2c_acordeon();
	});
</script>

</html>
