<?php

if (isset($_GET['excel']) && ($_GET['excel']=='excel')){
	header("Content-type:application/x-msexcel");
	$file=$_GET['capa'];
	header("Content-Disposition: attachment; filename=".$file.".xls");
	$imgtitulo='';
} else{
	$imgtitulo='<img src="imajes/desplegable.png" width="11" height="11">';
}

/*@session_start();
	if(empty($_SESSION['usuario'])){
        header('Location: ../index.php');
	}else{$cod_user = $_SESSION['usuario'];}*/
	include ('conexion_postgres.phtml');
	include ('injection/funciones.php');
	$player = limpiarCadena($_GET['olayer']);
	$pcampo = limpiarCadena($_GET['ocampo']);
	$pvalor = limpiarNumeros($_GET['ovalor']);
	$linkPG = Conectarse_POSTGRES();
    // Browse Data
    // select pec.cod_des_op, pec.tot_vot,pec.desc_op, pd.cod_dist, pd.nom_dist, pd.cod_prov , pd.nom_prov, pd.cod_dpto, pd.nom_dpto,pd.the_geom from peru_elecciones_congresales pec
	//   	inner join peru_distritos pd on pd.cod_dist = pec.cod_dist where pd.cod_dist = '010101';
	$sQueryS = "select * from vw_peru_comisarias_pnp";
	$sQueryW = "  where gid = " . $pvalor;

	$sQuery = $sQueryS . $sQueryW;
	$rsDet = pg_query( $linkPG , $sQuery );
	$titulo_ventana = 'Comisarías PNP';
	$titulo = 'Comisarías PNP';
	include ('inc/consulta_cabecera.php');
?>
<table width="100%" border="0" cellspacing="0" cellpadding="10">
  <tr><td>
	<table width="100%" class="marco_general">
	  <tr><td>
		<table width="100%" class="marco_individual">
		  <tr>
			<td>
				<table width="100%" class="titulo_general">
				  <tr>
					<td>&nbsp;&nbsp;UBICACI&Oacute;N GEOGR&Aacute;FICA</td>
				  </tr>
				</table>
				<table width='100%' align='center' class='general'>
					<thead>
					  <tr>
						<th width='25%'>Departamento</th>
						<th width='25%'>Provincia</th>
						<th width='25%'>Distrito</th>
						<th width='25%'>Codigo Distrito</th>
					  </tr>
					</thead>
					<tbody>
					<tr>
						<td align='center' class='texto'><?php echo(pg_fetch_result($rsDet,0,"\"nom_dpto\"")) ?></td>
						<td align='center' class='texto'><?php echo(pg_fetch_result($rsDet,0,"\"nom_prov\"")) ?></td>
						<td align='center' class='texto'><?php echo(pg_fetch_result($rsDet,0,"\"nom_dist\"")) ?></td>
						<td align='center' class='texto'><?php echo(pg_fetch_result($rsDet,0,"\"cod_dist\"")) ?></td>
					</tr>
	
					</tbody>
				</table>
			</td>
		  </tr>
		</table>
		<br>
		<table width="100%" class="marco_individual">
		  <tr>
			<td>
				<table width="100%" class="titulo_general">
					  <tr>
						<td>&nbsp;&nbsp;DATOS DE LA COMISARÍA</td>
					  </tr>
				</table>
			<table width='100%' align='center' class='general'>

                    <tr>
						<td width='50%' class='texto1'>Población (hab.)</td>
						<td width='50%' class='texto1' style='text-align:right;'><?php echo(pg_fetch_result($rsDet,0,"\"pob_2020\"")) ?></td>
					</tr>
                    <tr>
						<td width='50%' class='texto1'>Macro región policial</td>
						<td width='50%' class='texto1' style='text-align:right;'><?php  echo(pg_fetch_result($rsDet,0,"\"macroregio\"")) ?></td>
					</tr>
                    <tr>
						<td width='50%' class='texto1'>Región</td>
						<td width='50%' class='texto1' style='text-align:right;'><?php  echo(pg_fetch_result($rsDet,0,"\"region\"")) ?></td>
					</tr>
                    <tr>
						<td width='50%' class='texto1'>División policial</td>
						<td width='50%' class='texto1' style='text-align:right;'><?php  echo(pg_fetch_result($rsDet,0,"\"div_pol\"")) ?></td>
					</tr>
                    <tr>
						<td width='50%' class='texto1'>Nombre de la Comisaría</td>
						<td width='50%' class='texto1' style='text-align:right;'><?php  echo(pg_fetch_result($rsDet,0,"\"nom_comisa\"")) ?></td>
					</tr>
                    <tr>
						<td width='50%' class='texto1'>Tipo de Comisaría</td>
						<td width='50%' class='texto1' style='text-align:right;'><?php  echo(pg_fetch_result($rsDet,0,"\"tipo\"")) ?></td>
					</tr>


                    <tr>
						<td width='50%' class='texto1'>Descripción del tipo de Comisaría</td>
						<td width='50%' class='texto1' style='text-align:right;'><?php  echo(pg_fetch_result($rsDet,0,"\"desc_tipo\"")) ?></td>
					</tr>

                    <tr>
						<td width='50%' class='texto1'>¿A Cuánta población atiende la Comisaría/Unidad especializada dentro de su Jurisdicción?</td>
						<td width='50%' class='texto1' style='text-align:right;'><?php  echo(pg_fetch_result($rsDet,0,"\"inf109\"")) ?></td>
					</tr>

                    <tr>
						<td width='50%' class='texto1'>¿Cuántos policías están asignados en la Comisaría? - Total</td>
						<td width='50%' class='texto1' style='text-align:right;'><?php  echo(pg_fetch_result($rsDet,0,"\"inf110_tot\"")) ?></td>
					</tr>

                    <tr>
						<td width='50%' class='texto1'>¿Cuántos policías realizan labores administrativas? - Total</td>
						<td width='50%' class='texto1' style='text-align:right;'><?php  echo(pg_fetch_result($rsDet,0,"\"inf111_adm\"")) ?></td>
					</tr>
                  
                    <tr>
						<td width='50%' class='texto1'>¿Cuántos policías realizan patrullaje motorizado (Autos, Camionetas, Motos Lineales u Otros)? - Total</td>
						<td width='50%' class='texto1' style='text-align:right;'><?php  echo(pg_fetch_result($rsDet,0,"\"inf112_mot\"")) ?></td>
					</tr>

                    <tr>
						<td width='50%' class='texto1'>¿Cuántos policías realizan patrullaje a pie? - Total</td>
						<td width='50%' class='texto1' style='text-align:right;'><?php  echo(pg_fetch_result($rsDet,0,"\"inf113_pie\"")) ?></td>
					</tr>

                    <tr>
						<td width='50%' class='texto1'>¿Cuántos policías realizan investigación de delitos y faltas? - Total</td>
						<td width='50%' class='texto1' style='text-align:right;'><?php  echo(pg_fetch_result($rsDet,0,"\"i114_in_df\"")) ?></td>
					</tr>


                    <tr>
						<td width='50%' class='texto1'>¿Cuántos policías realizan investigación de accidentes de tránsito? - Total</td>
						<td width='50%' class='texto1' style='text-align:right;'><?php  echo(pg_fetch_result($rsDet,0,"\"i115_in_at\"")) ?></td>
					</tr>


                    <tr>
						<td width='50%' class='texto1'>¿Cuántos policías realizan investigación de violencia familiar? - Total</td>
						<td width='50%' class='texto1' style='text-align:right;'><?php  echo(pg_fetch_result($rsDet,0,"\"i116_in_vf\"")) ?></td>
					</tr>


                    <tr>
						<td width='50%' class='texto1'>¿Cuántos policías realizan labores en la Ofina de Participación Ciudadana (OPC)? - Total</td>
						<td width='50%' class='texto1' style='text-align:right;'><?php  echo(pg_fetch_result($rsDet,0,"\"inf117_opc\"")) ?></td>
					</tr>


                    <tr>
						<td width='50%' class='texto1'>¿Cuántos policías realizan labores de servicio de guardia? - Total</td>
						<td width='50%' class='texto1' style='text-align:right;'><?php  echo(pg_fetch_result($rsDet,0,"\"inf118_pg\"")) ?></td>
					</tr>


                    <tr>
						<td width='50%' class='texto1'>¿Cuántos policías realizan labores de supervisión y control? - Total</td>
						<td width='50%' class='texto1' style='text-align:right;'><?php  echo(pg_fetch_result($rsDet,0,"\"inf119_sc\"")) ?></td>
					</tr>

                    <tr>
						<td width='50%' class='texto1'>¿Cuántos policías realizan otro tipo de actividades? - Total</td>
						<td width='50%' class='texto1' style='text-align:right;'><?php  echo(pg_fetch_result($rsDet,0,"\"inf120_o\"")) ?></td>
					</tr>

                    <tr>
						<td width='50%' class='texto1'>El material de construcción predominante en las paredes del local de la Comisaría/ Unidad especializada es de:</td>
						<td width='50%' class='texto1' style='text-align:right;'><?php  echo(pg_fetch_result($rsDet,0,"\"inf212\"")) ?></td>
					</tr>

                    <tr>
						<td width='50%' class='texto1'>El material de construcción predominante en los pisos del local de la Comisaría/ Unidad especializada es de:</td>
						<td width='50%' class='texto1' style='text-align:right;'><?php  echo(pg_fetch_result($rsDet,0,"\"inf213\"")) ?></td>
					</tr>

                    <tr>
						<td width='50%' class='texto1'>El material de construcción predominante en los techos del local de la Comisaría/ Unidad especializada es de:</td>
						<td width='50%' class='texto1' style='text-align:right;'><?php  echo(pg_fetch_result($rsDet,0,"\"inf214\"")) ?></td>
					</tr>

                    <tr>
						<td width='50%' class='texto1'>¿La Comisaría/Unidad especializada tiene energía eléctrica mediante red pública?</td>
						<td width='50%' class='texto1' style='text-align:right;'><?php  echo(pg_fetch_result($rsDet,0,"\"inf216\"")) ?></td>
					</tr>

                    <tr>
						<td width='50%' class='texto1'>¿El local de la Comisaría/Unidad especializada tiene acceso al servicio eléctrico todos los días de la semana?</td>
						<td width='50%' class='texto1' style='text-align:right;'><?php  echo(pg_fetch_result($rsDet,0,"\"inf217\"")) ?></td>
					</tr>

                    <tr>
						<td width='50%' class='texto1'>¿Cuántas horas al día?</td>
						<td width='50%' class='texto1' style='text-align:right;'><?php  echo(pg_fetch_result($rsDet,0,"\"inf217a\"")) ?></td>
					</tr>


                    <tr>
						<td width='50%' class='texto1'>¿Cuántos días a la semana tiene este servicio?</td>
						<td width='50%' class='texto1' style='text-align:right;'><?php  echo(pg_fetch_result($rsDet,0,"\"inf217b\"")) ?></td>
					</tr>


                    <tr>
						<td width='50%' class='texto1'>¿Cuántas horas al día?</td>
						<td width='50%' class='texto1' style='text-align:right;'><?php  echo(pg_fetch_result($rsDet,0,"\"inf217c\"")) ?></td>
					</tr>

                    <tr>
						<td width='50%' class='texto1'>El abastecimiento de agua en el local de la Comisaría/Unidad especializada, procede de:</td>
						<td width='50%' class='texto1' style='text-align:right;'><?php  echo(pg_fetch_result($rsDet,0,"\"inf225\"")) ?></td>
					</tr>

                    <tr>
						<td width='50%' class='texto1'>¿El local de la Comisaría/Unidad especializada tiene acceso al servicio de agua potable todos los días de la semana?</td>
						<td width='50%' class='texto1' style='text-align:right;'><?php  echo(pg_fetch_result($rsDet,0,"\"inf226\"")) ?></td>
					</tr>

                    <tr>
						<td width='50%' class='texto1'>¿Cuántas horas al día?</td>
						<td width='50%' class='texto1' style='text-align:right;'><?php  echo(pg_fetch_result($rsDet,0,"\"inf226a\"")) ?></td>
					</tr>


                    <tr>
						<td width='50%' class='texto1'>¿Cuántos días a la semana tiene este servicio?</td>
						<td width='50%' class='texto1' style='text-align:right;'><?php  echo(pg_fetch_result($rsDet,0,"\"inf226b\"")) ?></td>
					</tr>


                    <tr>
						<td width='50%' class='texto1'>¿Cuántas horas al día?</td>
						<td width='50%' class='texto1' style='text-align:right;'><?php  echo(pg_fetch_result($rsDet,0,"\"inf226c\"")) ?></td>
					</tr>


                    <tr>
						<td width='50%' class='texto1'>El/los Baño(S) que tiene El local de la Comisaría/Unidad especializada está(n) Conectado(s) a:</td>
						<td width='50%' class='texto1' style='text-align:right;'><?php  echo(pg_fetch_result($rsDet,0,"\"inf230\"")) ?></td>
					</tr>


                    <tr>
						<td width='50%' class='texto1'>Recodificación de materiales de las paredes</td>
						<td width='50%' class='texto1' style='text-align:right;'><?php  echo(pg_fetch_result($rsDet,0,"\"material_p\"")) ?></td>
					</tr>


                    <tr>
						<td width='50%' class='texto1'>Recodificación de materiales de los pisos</td>
						<td width='50%' class='texto1' style='text-align:right;'><?php  echo(pg_fetch_result($rsDet,0,"\"piso\"")) ?></td>
					</tr>


                    <tr>
						<td width='50%' class='texto1'>Recodificación de material del techo</td>
						<td width='50%' class='texto1' style='text-align:right;'><?php  echo(pg_fetch_result($rsDet,0,"\"techo\"")) ?></td>
					</tr>


                    <tr>
						<td width='50%' class='texto1'>Servicio de luz a la semana</td>
						<td width='50%' class='texto1' style='text-align:right;'><?php  echo(pg_fetch_result($rsDet,0,"\"luz_1\"")) ?></td>
					</tr>

                    <tr>
						<td width='50%' class='texto1'>Número de horas a la semana que la Comisaria tiene servicio de luz</td>
						<td width='50%' class='texto1' style='text-align:right;'><?php  echo(pg_fetch_result($rsDet,0,"\"hor_luz_se\"")) ?></td>
					</tr>

                    <tr>
						<td width='50%' class='texto1'>Recodificación del número de horas a la semana que la Comisaria tiene servicio de luz</td>
						<td width='50%' class='texto1' style='text-align:right;'><?php  echo(pg_fetch_result($rsDet,0,"\"luz\"")) ?></td>
					</tr>


                    <tr>
						<td width='50%' class='texto1'>Servicio de agua a la semana</td>
						<td width='50%' class='texto1' style='text-align:right;'><?php  echo(pg_fetch_result($rsDet,0,"\"agua_1\"")) ?></td>
					</tr>

                    <tr>
						<td width='50%' class='texto1'>Número de horas a la semana que la Comisaria tiene servicio de agua</td>
						<td width='50%' class='texto1' style='text-align:right;'><?php  echo(pg_fetch_result($rsDet,0,"\"ho_agua_se\"")) ?></td>
					</tr>

                    <tr>
						<td width='50%' class='texto1'>Recodificación del número de horas a la semana que la Comisaria tiene servicio de agua</td>
						<td width='50%' class='texto1' style='text-align:right;'><?php  echo(pg_fetch_result($rsDet,0,"\"agua\"")) ?></td>
					</tr>

                    <tr>
						<td width='50%' class='texto1'>Indicador de infraestructura</td>
						<td width='50%' class='texto1' style='text-align:right;'><?php  echo(pg_fetch_result($rsDet,0,"\"infraestru\"")) ?></td>
					</tr>
	
			</table>
			</td>
		  </tr>
		</table>
		<br>
		
		<table class='fuente_general' width="100%"><thead><tr><th><b>Fuente:</b>
			<br><?php echo pg_fetch_result($rsDet,0,"\"fuente\"");?></th></tr></thead>
		</table>
	<?php
	//$name=strtoupper(pg_fetch_result($rsDet,0,"\"tipoaerona\"").' - '.pg_fetch_result($rsDet,0,"\"label\""));
	$name='Comisarías PNP';
	$capa='consulta_comisarias_pnp';
	if (!isset($_GET['excel'])) {
		$ruta=$capa.'.phtml?excel=excel&capa='.$capa.'&ovalor='.$pvalor.'&olayer=peru_comisarias_pnp'.'&ocampo=gid';
		include 'inc/consulta_pie.php';
	}
	if (isset($_SESSION['usuario'])) {
		grabar_log_accesos('ingreso', $cod_user, $name, $descripcion);
	}
	?>
		</td>
	  </tr>
	</table>
	</td>
  </tr>
</table>
</body>
</html>
<?php include_once("./analyticstracking.php");?>


