<?php

if (isset($_GET['excel']) && ($_GET['excel']=='excel')) {
	header("Content-type:application/x-msexcel");
	$file=$_GET['capa'];
	header("Content-Disposition: attachment; filename=".$file.".xls");
	$imgtitulo='';
} else {
	$imgtitulo='<img src="imajes/desplegable.png" width="11" height="11">';
}

/*@session_start();
	if(empty($_SESSION['usuario'])){
        header('Location: ../index.php');
	}else{$cod_user = $_SESSION['usuario'];}*/
	include ('conexion_postgres.phtml');
	include ('injection/funciones.php');
	$player = 	limpiarCadena($_GET['olayer']);
	$pcampo = 	limpiarCadena($_GET['ocampo']);
	$gid = limpiarNumeros($_GET['ovalor']);
	
	$linkPG = Conectarse_POSTGRES(); 
	// Browse Data
	$sQueryS = " SELECT *  ";   
	$sQueryF = " FROM vw_peru_econ_proy_cartera_pys_inversion_minera_Jul2023";
	$sQueryW = " WHERE gid = '" . $gid. "'";
	$sQuery = $sQueryS . $sQueryF . $sQueryW;
	$rsDet = pg_query( $linkPG , $sQuery );
	$titulo_ventana = 'Proyectos mineros en exploración';
	$titulo = $titulo_ventana;
	
	
	include ('inc/consulta_cabecera.php');
?>
<table width="100%" border="0" cellspacing="0" cellpadding="10">
  <tr><td>
	<table width="100%" class="marco_general">
	  <tr><td>
		<table width="100%" class="marco_individual">
		  <tr>
			<td>
			<table width="100%" class="titulo_general">
			  <tr>
				<td>&nbsp;&nbsp;DATOS DEL PROYECTO MINERO</td>
			  </tr>
			</table>
			<table width='100%' align='center' class='general'>
				<thead>
				  <tr>
					<th width='16%'>Nombre del proyecto minero</th>
					<th width='16%'>Empresa</th>
					<th width='16%'>Mineral predominante</th>
					<th width='16%'>Etapa</th>
					<th width='16%'>LONGITUD X</th>
					<th width='16%'>LATITUD Y</th>
				  </tr>
				</thead>
				<tbody>
<?php
		print "<tr>
				<td align='center' class='texto'>".pg_fetch_result($rsDet,0,"\"proyecto\"")."</td>
				<td align='center' class='texto'>".pg_fetch_result($rsDet,0,"\"operador\"")."</td>
				<td align='center' class='texto'>".pg_fetch_result($rsDet,0,"\"producto_p\"")."</td>
				<td align='center' class='texto'>".pg_fetch_result($rsDet,0,"\"etapa_de_a\"")."</td>
				<td align='center' class='texto'>".pg_fetch_result($rsDet,0,"\"longitud\"")."</td>
				<td align='center' class='texto'>".pg_fetch_result($rsDet,0,"\"latitud\"")."</td>
			  </tr>";
?>
				</tbody>
			</table>
			</td>
		  </tr>
		</table>			
		<br>
		<table class='fuente_general' width="100%"><thead><tr><th><b>Fuente:</b>
			<br><?php echo(pg_fetch_result($rsDet,0,"\"fuente\"")); ?>
		</th></tr></thead></table>
	<?php
	$name='Cobertura Movil BITEL';
	$capa='peru_infra_cobertura_movil_bitel';
	if (!isset($_GET['excel'])) {
		$ruta='consulta_telefonia_movil.phtml?excel=excel&capa='.$capa.'&ovalor='.$gid;
		include 'inc/consulta_pie.php';
	}
	if (isset($_SESSION['usuario'])) {
		grabar_log_accesos('ingreso', $cod_user, $name, $descripcion);
	}
	?>
</td></tr>
	</table>
	</td></tr>
</table>
</body>

</html>


<?php include_once("./analyticstracking.php");?>
