<?php

if (isset($_GET['excel']) && ($_GET['excel']=='excel')) {
	header("Content-type:application/x-msexcel");
	$file=$_GET['capa'];
	header("Content-Disposition: attachment; filename=".$file.".xls");
	$imgtitulo='';
} else {
	$imgtitulo='<img src="imajes/desplegable.png" width="11" height="11">';
}

/*@session_start();

	if(empty($_SESSION['usuario'])){
        header('Location: ../index.php');
		}else{$cod_user = $_SESSION['usuario'];}*/
		
	include ('conexion_postgres.phtml');
	include ('injection/funciones.php');
	$player = limpiarCadena($_GET['olayer']);
	$pcampo = limpiarCadena($_GET['ocampo']);
	$pvalor = limpiarNumeros($_GET['ovalor']);
	$linkPG = Conectarse_POSTGRES();
	if($pvalor==''){
		$gid = $_GET['codigo'];
	}else {
		$gid = $pvalor;
	}
	// Browse Data
	$sQueryS = "SELECT *";
	$sQueryF = " FROM data_inventario_turistico";
	$sQueryW = " WHERE \"cod_dist\" = '" . $gid. "'";
	$sQuery = $sQueryS . $sQueryF . $sQueryW;   
	$rsDet = pg_query( $linkPG , $sQuery );
	$titulo_ventana = 'INFORMACI&Oacute;N DE INVENTARIO TUR&Iacute;STICO';
	$titulo = 'INFORMACI&Oacute;N DE INVENTARIO TUR&Iacute;STICO ';
	include ('inc/consulta_cabecera.php');
	
?>
<table width="100%" border="0" cellspacing="0" cellpadding="10">
  <tr><td>
	<table width="100%" class="marco_general">
	  <tr><td>
		<table class="marco_individual">
		  <tr>
			<td>
				<div id="u1" style="width: 100%;">
					<h1><table width="100%" class="titulo_general">
						  <tr>
							<td><?php echo $imgtitulo;?>&nbsp;&nbsp;UBICACI&Oacute;N GEOGR&Aacute;FICA</td>
						  </tr>
						</table>
					</h1>
				<div>
					<table width='100%' align='center' class='general'>
						<thead>
							<th width='25%'><?php echo(getTablaCampo('data_inventario_turistico','nom_dpto'));?></th>
							<th width='25%'><?php echo(getTablaCampo('data_inventario_turistico','nom_prov'));?></th>
							<th width='25%'><?php echo(getTablaCampo('data_inventario_turistico','nom_dist'));?></th>
							<th width='25%'><?php echo(getTablaCampo('data_inventario_turistico','cod_dist'));?></th>
						</thead>
						<tbody>
						<?php
							print "<tr>
									<td align='center' class='texto'>".pg_fetch_result($rsDet,0,"\"nom_dpto\"")."</td>
									<td align='center' class='texto'>".pg_fetch_result($rsDet,0,"\"nom_prov\"")."</td>
									<td align='center' class='texto'>".pg_fetch_result($rsDet,0,"\"nom_dist\"")."</td>
									<td align='center' class='texto'>".pg_fetch_result($rsDet,0,"\"cod_dist\"")."</td>
								  </tr>";
						?>
						</tbody>
					</table>
				</div>
				</div>
			</td>
		  </tr>
		</table>
		<br>
		<table width="100%" class="marco_individual">
		  <tr>
			<td>
				<div id="u2" style="width: 100%;">
					<h1>
						<table width="100%" class="titulo_general">
						  <tr>
							<td><?php echo $imgtitulo;?>&nbsp;&nbsp;DATOS INVENTARIO DE RECURSOS TUR&Iacute;STICOS EN EL DISTRITO <?php echo pg_fetch_result($rsDet,0,"\"nom_dist\"") ?> </td>
						  </tr>
						</table>
					</h1>
				<div>
					<table width='100%' align='center' class='listado'>
						<?php 
		  		print "<tr>";
					print "<td class='lista_titulo'>Nro.</td><td  class='lista_titulo'>".getTablaCampo('data_inventario_turistico','atractivo')."</td>";
					print "<td  class='lista_titulo'>".getTablaCampo('data_inventario_turistico','categoria')."</td>";
					print "<td  class='lista_titulo'>".getTablaCampo('data_inventario_turistico','tipo')."</td>";
					print "<td  class='lista_titulo'>".getTablaCampo('data_inventario_turistico','subtipo')."</td>";
					print "<td  class='lista_titulo'>".getTablaCampo('data_inventario_turistico','jerar')."</td>";
					//print "<td  class='lista_titulo'>".getTablaCampo('data_inventario_turistico','link_ficha')."</td>";
		  		print "</tr>";
				$i=0;
				while($i<pg_num_rows($rsDet)){
				    $j=$i+1;
					$link_ficha = pg_fetch_result($rsDet,$i,"\"link_ficha\"");
					print "<tr>";
					print "<td class='lista_textosub'>".$j."</td>";
					print "<td class='lista_textosub'>".pg_fetch_result($rsDet,$i,"\"atractivo\"")."</td>";
					print "<td class='lista_textosub'>".pg_fetch_result($rsDet,$i,"\"categoria\"")."</td>";
					print "<td class='lista_textosub'>".pg_fetch_result($rsDet,$i,"\"tipo\"")."</td>";
					print "<td class='lista_textosub'>".pg_fetch_result($rsDet,$i,"\"subtipo\"")."</td>";
					print "<td class='lista_textosub'>".pg_fetch_result($rsDet,$i,"\"jerar\"")."</td>";
					//print "<td class='lista_textosub'>Ver <a href=\"".$link_ficha."\" target=\"blank\">link</a></td>";
				    print "</tr>";
					$i++;
				}			
?>
					</table>
				</div>
				</div>
			</td>
		  </tr>
		</table>
		<br>
		
		<br>

		<table class='fuente_general' width="100%"><thead><tr><th><b>Fuente:</b>
			<br><?php echo pg_fetch_result($rsDet,0,"\"fuente\"");?></th></tr></thead>
		</table>
	<?php
	$name=strtoupper(pg_fetch_result($rsDet,0,"\"categoria\"").' '.pg_fetch_result($rsDet,0,"\"tipo\""));
	$capa='consulta_inv_tur';
	if (!isset($_GET['excel'])) {
		$ruta=$capa.'.phtml?excel=excel&capa='.$capa.'&ovalor='.$pvalor;
		include 'inc/consulta_pie.php';
	}
	if (isset($_SESSION['usuario'])) {
		grabar_log_accesos('ingreso', $cod_user, $name, $descripcion);
	}
	?>
		</td></tr>
	</table>
	</td></tr>
</table>
</body>
<script language="javascript" type="text/javascript">
	$(document).ready(function(){
		$("#u1").h2c_acordeon();
		$("#u2").h2c_acordeon();
		$("#u3").h2c_acordeon();
		$("#u4").h2c_acordeon();
		$("#u5").h2c_acordeon();
	});
</script>

</html>