<?php
/***************************************************************************************
Organización: 	Presidencia del Consejo de Ministros - PCM
Gerencia	: 	Secretaría de Descentralización
Sistema		: 	Sistema Nacional de Información Geográfica - SAYWITE
Coordinador/Desarrollador TIC: Vitaly Uriel Cespedes Reynaga vitalyuri@hotmail.com/vitalyuri@gmail.com/969228151
Periodo		: 	Septiembre 2012 - 2013
***************************************************************************************/

if (isset($_GET['excel']) && ($_GET['excel']=='excel')) {
	header("Content-type:application/x-msexcel");
	$file=$_GET['capa'];
	header("Content-Disposition: attachment; filename=".$file.".xls");
	$imgtitulo='';
} else {
	$imgtitulo='<img src="imajes/desplegable.png" width="11" height="11">';
}
	
	include ('conexion_postgres.phtml');
	include ('injection/funciones.php');
	$player = limpiarCadena($_GET['olayer']);
	$pcampo = limpiarCadena($_GET['ocampo']);
	$pvalor = limpiarNumeros($_GET['ovalor']);
	$linkPG = Conectarse_POSTGRES();
	// Browse Data
	$sQueryS = " SELECT *";   
	$sQueryF = " FROM data_pma_fenomenos_prov ";
	$sQueryW = " WHERE \"cod_prov\" = '" . $pvalor . "'";

	$sQuery = $sQueryS . $sQueryF . $sQueryW;   
	$rsDet = pg_query( $linkPG , $sQuery );

	$rsDet = pg_query( $linkPG , $sQuery );
	$niv_rec_fn=pg_fetch_result($rsDet,0,"\"n_via_fn18\"");
				switch ($niv_rec_fn) {
				case 1:
					$niv_rec_fn_='Bajo';
					break;
				case 2:
					$niv_rec_fn_='Medio';
					break;
				case 3:
					  $niv_rec_fn_='Alto';
					break;
				case 4:
					$niv_rec_fn_='Muy alto';
					break;
				}	
		$titulo_ventana = 'MAPA DE VULNERABILIDAD A LA INSEGURIDAD ALIMENTARIA ANTE LA RECURRENCIA DE FEN&Oacute;MENOS DE ORIGEN NATURAL, 2018 - PROVINCIA '.pg_fetch_result($rsDet,0,"\"nom_prov\"");
		$titulo = 'MAPA DE VULNERABILIDAD A LA INSEGURIDAD ALIMENTARIA ANTE LA RECURRENCIA DE FEN&Oacute;MENOS DE ORIGEN NATURAL, 2018 - </br> PROVINCIA '.pg_fetch_result($rsDet,0,"\"nom_prov\"");
	
	include ('inc/consulta_cabecera.php');
?>
<table width="100%" border="0" cellspacing="0" cellpadding="10">
  <tr><td>
	<table width="100%" class="marco_general">
	  <tr><td>
		<table class="marco_individual">
		  <tr>
			<td>
				<div id="u1" style="width: 100%;">
					<h1><table width="100%" class="titulo_general">
						  <tr>
							<td><?php echo $imgtitulo;?>&nbsp;&nbsp;UBICACI&Oacute;N GEOGR&Aacute;FICA</td>
						  </tr>
						</table></h1>
					<div>
						<table width='100%' align='center' class='general'>
						<thead>
						  <tr>
							<th width="20%">Ubigeo</th>
							<th width="20%">Departamento</th>
							<th width="20%">Provincia</th>
							
						  </tr>
						</thead>
						<tbody>
						  <tr>
						<?php
							print "<td align='center' class='texto'>".pg_fetch_result($rsDet,0,"\"cod_prov\"")."</td>";
							print "<td align='center' class='texto'>".pg_fetch_result($rsDet,0,"\"nom_dpto\"")."</td>";
							print "<td align='center' class='texto'>".pg_fetch_result($rsDet,0,"\"nom_prov\"")."</td>";
							
						?> 		  
						  </tr>
						</tbody>
						</table>
					</div>
				</div>
			</td>
		  </tr>
		</table>
		<br>
		<table width="100%" class="marco_individual">
		  <tr>
			<td>
				<div id="u2" style="width: 100%;">
					<h1><table width="100%" class="titulo_general">
						  <tr>
							<td><?php echo $imgtitulo;?>&nbsp;&nbsp;DATOS DEL MAPA </td>
						  </tr>
						</table></h1>
					<div>
					<table width='100%' align='center' class='general'>
					 
					
						<?php
							print "<tr>";
							print "<td width='50%' class='lista_titulo'><b>Provincia</b></td>";
							print "<td width='50%' class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"nom_prov\"")."&nbsp;</td>";
							print "</tr>";
							print "<tr>";
							print "<td class='lista_titulo'><b>&Iacute;ndice de Vulnerabilidad a la Inseguridad Alimentaria ante la recurrencia de fen&oacute;menos de origen natural 2018</b></td>";
							print "<td class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"i_via_fn18\"")."&nbsp;</td>";
							print "</tr>";
							print "<tr>";
							print "<td class='lista_titulo'><b>Nivel de Vulnerabilidad a la Inseguridad Alimentaria ante la recurrencia de fen&oacute;menos de origen natural 2018</b></td>";
							print "<td class='lista_textosub'>".$niv_rec_fn."&nbsp;</td>";
							print "</tr>";
							print "<tr>";
							print "<td class='lista_titulo'><b>Poblaci&oacute;n 2017 (Hab.)</b></td>";
							print "<td class='lista_textosub'>".number_format(pg_fetch_result($rsDet,0,"\"pob2017\""),0)."&nbsp;</td>";
							print "</tr>";
							print "<tr >";
							print "<td class='lista_titulo'><b>Poblaci&oacute;n rural seg&uacute;n encuesta</b></td>";
							print "<td class='lista_textosub'>".number_format(pg_fetch_result($rsDet,0,"\"pob_rur\""),0)."&nbsp;</td>";
							print "</tr>";
							print "<tr >";
							print "<td class='lista_titulo'><b>&Iacute;ndice de peligro clim&aacute;tico, 2003-2018</b></td>";
							print "<td class='lista_textosub'>".number_format(pg_fetch_result($rsDet,0,"\"i_pc_0318\""),0)."&nbsp;</td>";
							print "</tr>";				
							print "<tr>";
							print "<td class='lista_titulo'><b>&Iacute;ndice de vulnerabilidad a la Inseguridad Alimentaria, 2018</b></td>";
							print "<td class='lista_textosub'>".number_format(pg_fetch_result($rsDet,0,"\"i_via18\""),0)."&nbsp;</td>";
							print "</tr>";
							print "<tr>";
							print "<td class='lista_titulo'><b>Ranking</b></td>";
							print "<td class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"ranking\"")."&nbsp;</td>";
							print "</tr>";			
							print "<tr>";
							print "<td class='lista_titulo'><b>Altitud promedio (msnm)</b></td>";
							print "<td class='lista_textosub'>".number_format(pg_fetch_result($rsDet,0,"\"altitud\""),0)."&nbsp;</td>";
							print "</tr>";
		
						?>
								
					</table>				
					</div>
				</div>
			</td>
		  </tr>
		</table>
		<br>
		
		
		<?php 
	if(getComDesc($player)!=''){
			include ('inc/descarga.php');	
	}
		?>
		<br>
		<table class='fuente_general' width="100%"><thead><tr><th>Fuentes:
		<br><?php echo pg_fetch_result($rsDet,0,"\"fuente\"").'<br>';?></th></tr></thead>
		</table>
	<?php

	$capa='consulta_pma_fenomenos_prov';
	if (!isset($_GET['excel'])) {
		//$ruta=$capa.'.phtml?excel=excel&capa='.$capa.'&ovalor='.$pvalor.'&name = '.$name;
		$ruta=$capa.'.phtml?excel=excel&capa='.$capa.'&ovalor='.$pvalor.'&olayer='.$player.'&niv_descarga='.$niv_descarga.'&descarga='.$descarga;
		include 'inc/consulta_pie.php';
	}
	if (isset($_SESSION['usuario'])) {
		grabar_log_accesos('ingreso', $cod_user, $name, $descripcion);
	}
	?>
		</td></tr>
	</table>
	</td></tr>
</table>
</body> 
<script language="javascript" type="text/javascript">
	$(document).ready(function(){
		$("#u1").h2c_acordeon();
		$("#u2").h2c_acordeon();
		$("#u3").h2c_acordeon();
		$("#u4").h2c_acordeon();
		$("#u5").h2c_acordeon();
		$("#u6").h2c_acordeon();
	});
</script>
</html>
<?php include_once("../analyticstracking.php");?>