<?php


if (isset($_GET['excel']) && ($_GET['excel']=='excel')) {
	header("Content-type:application/x-msexcel");
	$file=$_GET['capa'];
	header("Content-Disposition: attachment; filename=".$file.".xls");
	$imgtitulo='';
} else {
	$imgtitulo='<img src="imajes/desplegable.png" width="11" height="11">';
}

/*@session_start();
	if(empty($_SESSION['usuario'])){
        header('Location: ../index.php');
		}else{$cod_user = $_SESSION['usuario'];}*/
	include ('conexion_postgres.phtml');
	include ('injection/funciones.php');
	$player = limpiarCadena($_GET['olayer']);
	$pcampo = limpiarCadena($_GET['ocampo']);
	$pvalor = limpiarNumeros($_GET['ovalor']);
	$linkPG = Conectarse_POSTGRES();

	$gid = $pvalor;
	// Browse Data
	$sQueryS = "SELECT r.*, dppd.pob_py_20";
	$sQueryF = " FROM data_renamu_distrital r  LEFT JOIN data_pobl_proy_dist dppd ON dppd.cod_dist = r.cod_dist::text";
	$sQueryW = " WHERE r.gid = '" . $gid . "'";

	$sQuery = $sQueryS . $sQueryF . $sQueryW;
	$rsDet = pg_query( $linkPG , $sQuery );
	
	$titulo_ventana = 'REPORTE - '. pg_fetch_result($rsDet,0,"nom_dist");
		$titulo = 'REPORTE - '. pg_fetch_result($rsDet,0,"nom_dist");
	//$titulo = $name;
	include ('inc/consulta_cabecera.php');
?>

<table width="100%" border="0" cellspacing="0" cellpadding="10">
  <tr><td>
	<table width="100%" class="marco_general">
	  <tr><td>
		<table class="marco_individual">
		  <tr>
			<td>
				<div id="u1" style="width: 100%;">
					<h1><table width="100%" class="titulo_general">
						  <tr>
							<td><?php echo $imgtitulo;?>&nbsp;&nbsp;UBICACI&Oacute;N GEOGR&Aacute;FICA</td>
						  </tr>
						</table></h1>
					<div>
						<table width='100%' align='center' class='general'>
						<thead>
						  <tr>
							<th width="20%"><?php echo(getTablaCampo('data_renamu_distrital','nom_dpto'));?></th>
							<th width="20%"><?php echo(getTablaCampo('data_renamu_distrital','nom_prov'));?></th>
							<th width="20%"><?php echo(getTablaCampo('data_renamu_distrital','nom_dist'));?></th>
							<th width="20%"><?php echo(getTablaCampo('data_renamu_distrital','cod_dist'));?></th>
							<th width="20%">POBLACI&Oacute;N PROYECTADA 2020 </th>
		
						  </tr>
						</thead>
						<tbody>
						  <tr>
						<?php
							print "<td align='center' class='texto'>".pg_fetch_result($rsDet,0,"\"nom_dpto\"")."</td>";
							print "<td align='center' class='texto'>".pg_fetch_result($rsDet,0,"\"nom_prov\"")."</td>";
							print "<td align='center' class='texto'>".pg_fetch_result($rsDet,0,"\"nom_dist\"")."</td>";
							print "<td align='center' class='texto'>".pg_fetch_result($rsDet,0,"\"cod_dist\"")."</td>";
							print "<td align='center' class='texto'>". number_format(pg_fetch_result($rsDet,0,"\"pob_py_20\""),0)."</td>";
						?> 		  
						  </tr>
						</tbody>
						</table>
					</div>
				</div>
			</td>
		  </tr>
		</table>
		<br>
		
	
	
	<table width="100%" class="marco_individual">
	  <tr>
		<td>
		<div id="u2" style="width: 100%;">
		<h1><table width="100%" class="titulo_general">
		  <tr>
			<td><?php echo $imgtitulo;?>&nbsp;&nbsp;DATOS GENERALES DEL PERSONAL POR CONDICI&Oacute;N LABORAL Y G&Eacute;NERO</td>
		  </tr>
		</table></h1>
		<div>
		<table width='100%' align='center' class='listado'>
<?php
		print "<tr>";
		print "<td align='left' class='lista_titulo'><b>Funcionarios y/o Directivos</td>";
		print "<td align='left' class='lista_titulo'><b>Total Personal</td>";
		print "<td align='left' class='lista_titulo'><b>Hombre</td>";
		print "<td align='left' class='lista_titulo'><b>Mujer</td>";
		print " </tr>";

		print "<tr>";
		print "<td  class='lista_texto'>N&uacute;mero de Funcionarios y/o Directivos</td>";
		print "<td  class='texto'>" . pg_fetch_result($rsDet,0,"\"p20_1_t\"") . "&nbsp;</td>";
		print "<td  class='texto'>" . pg_fetch_result($rsDet,0,"\"tot_hdir\"") . "&nbsp;</td>";
		print "<td  class='texto'>" . pg_fetch_result($rsDet,0,"\"tot_mdir\"") . "&nbsp;</td>";
		print "</tr>";

		print "<tr>";
		print "<td class='lista_titulo'>Empleados / Profesionales</td>";
		print "<td align='left' class='lista_titulo'><b>Total Personal</td>";
		print "<td align='left' class='lista_titulo'><b>Hombre</td>";
		print "<td align='left' class='lista_titulo'><b>Mujer</td>";
		print "</tr>";
		
		print "<tr>";
		print "<td  class='lista_texto'>N&uacute;mero de Empleados / Profesionales</td>";
		print "<td  class='texto'>" . pg_fetch_result($rsDet,0,"\"p20_2_t\"") . "&nbsp;</td>";
		print "<td  class='texto'>" . pg_fetch_result($rsDet,0,"\"tot_hpro\"") . "&nbsp;</td>";
		print "<td  class='texto'>" . pg_fetch_result($rsDet,0,"\"tot_mpro\"") . "&nbsp;</td>";
		print "</tr>";
		
		print "<tr>";
		print "<td class='lista_titulo'>Empleados / T&eacute;cnicos</td>";
		print "<td align='left' class='lista_titulo'><b>Total Personal</td>";
		print "<td align='left' class='lista_titulo'><b>Hombre</td>";
		print "<td align='left' class='lista_titulo'><b>Mujer</td>";
		print "</tr>";
		
		print "<tr>";
		print "<td  class='lista_texto'>N&uacute;mero de Empleados / T&eacute;cnicos</td>";
		print "<td  class='texto'>" . pg_fetch_result($rsDet,0,"\"p20_3_t\"") . "&nbsp;</td>";
		print "<td  class='texto'>" . pg_fetch_result($rsDet,0,"\"tot_htec\"") . "&nbsp;</td>";
		print "<td  class='texto'>" . pg_fetch_result($rsDet,0,"\"tot_mtec\"") . "&nbsp;</td>";
		print "</tr>";
		
		print "<tr>";
		print "<td class='lista_titulo'>Empleados / Auxiliares</td>";
		print "<td align='left' class='lista_titulo'><b>Total Personal</td>";
		print "<td align='left' class='lista_titulo'><b>Hombre</td>";
		print "<td align='left' class='lista_titulo'><b>Mujer</td>";
		print "</tr>";
		
		print "<tr>";
		print "<td  class='lista_texto'>N&uacute;mero de Empleados / Auxiliares</td>";
		print "<td  class='texto'>" . pg_fetch_result($rsDet,0,"\"p20_4_t\"") . "&nbsp;</td>";
		print "<td  class='texto'>" . pg_fetch_result($rsDet,0,"\"tot_haux\"") . "&nbsp;</td>";
		print "<td  class='texto'>" . pg_fetch_result($rsDet,0,"\"tot_maux\"") . "&nbsp;</td>";
		print "</tr>";
		
		print "<tr>";
		print "<td align='left' class='lista_titulo'><b>Total de personal municipal</td>";
		print "<td  class='lista_titulo'>" . pg_fetch_result($rsDet,0,"\"tot_pmun\"") . "&nbsp;</td>";
		print "<td  class='lista_titulo'>" . pg_fetch_result($rsDet,0,"\"tot_hom\"") . "&nbsp;</td>";
		print "<td  class='lista_titulo'>" . pg_fetch_result($rsDet,0,"\"tot_muj\"") . "&nbsp;</td>";
		print " </tr>";

		
?>
		</table>
		</div>
		</div>
		</td>
	  </tr>
	</table>
		
		<?php 
	if(getComDesc($player)!=''){
			include ('inc/descarga.php');	
	}
		?>
		<br>
		<table class='fuente_general' width="100%"><thead><tr><th>Fuentes:
		<br><?php echo pg_fetch_result($rsDet,0,"\"fuente\"").'<br>';?></th></tr></thead>
		</table>
	<?php

	$capa='consulta_personal_municipal';
	if (!isset($_GET['excel'])) {
		//$ruta=$capa.'.phtml?excel=excel&capa='.$capa.'&ovalor='.$pvalor.'&name = '.$name;
		$ruta=$capa.'.phtml?excel=excel&capa='.$capa.'&ovalor='.$pvalor.'&olayer='.$player.'&niv_descarga='.$niv_descarga.'&descarga='.$descarga;
		include 'inc/consulta_pie.php';
	}
	if (isset($_SESSION['usuario'])) {
		grabar_log_accesos('ingreso', $cod_user, $name, $descripcion);
	}
	?>
		</td></tr>
	</table>
	</td></tr>
</table>
</body>
<script language="javascript" type="text/javascript">
	$(document).ready(function(){
	$("#u1").h2c_acordeon();
	$("#u2").h2c_acordeon();
	$("#u3").h2c_acordeon();
	$("#u4").h2c_acordeon();
	$("#u5").h2c_acordeon();
	$("#u6").h2c_acordeon();
	});
</script>
</html> 
