<?php

if (isset($_GET['excel']) && ($_GET['excel']=='excel')) {
	header("Content-type:application/x-msexcel");
	$file=$_GET['capa'];
	header("Content-Disposition: attachment; filename=".$file.".xls");
	$imgtitulo='';
} else {
	$imgtitulo='<img src="imajes/desplegable.png" width="11" height="11">';
}

// @session_start();
// 	if(empty($_SESSION['usuario'])){
//         header('Location: ../index.php');
// 		}else{$cod_user = $_SESSION['usuario'];}
	include ('conexion_postgres.phtml');
	include ('injection/funciones.php');
	$player = limpiarCadena($_GET['olayer']);
	$pcampo = limpiarCadena($_GET['ocampo']);
    $pvalor = limpiarNumeros($_GET['ovalor']);
	$linkPG = Conectarse_POSTGRES();

	$sCodIdDist = $pvalor;

	// Browse Data
	$sQueryS = "SELECT *";
	$sQueryF = " FROM peru_info_gl";
	$sQueryW = " WHERE \"gid\" = '" . $sCodIdDist . "'";

	$sQuery = $sQueryS . $sQueryF . $sQueryW;
	$rsDet = pg_query( $linkPG , $sQuery );
	$catmuni=pg_fetch_result($rsDet,0,"\"catmuni\"");
	if($catmuni==2) {
		$titulo_ventana = 'RENAMU - DISTRITO '.pg_fetch_result($rsDet,0,"\"nom_dist\"");
		$titulo = 	'RENAMU <BR> DISTRITO '.pg_fetch_result($rsDet,0,"\"nom_dist\"");
		$log	=	'RENAMU - DISTRITO '.pg_fetch_result($rsDet,0,"\"nom_dist\"");
		$articulo ='EL';
	} else if($catmuni==1){
		$titulo_ventana = 'RENAMU - PROVINCIA '.pg_fetch_result($rsDet,0,"\"nom_prov\"");
		$titulo = 'RENAMU <BR> PROVINCIA '.pg_fetch_result($rsDet,0,"\"nom_prov\"");
		$log='RENAMU - PROVINCIA '.pg_fetch_result($rsDet,0,"\"nom_prov\"");
		$articulo ='LA';
	}
	//$titulo = 'GESTI&Oacute;N - '. pg_fetch_result($rsDet,0,"\"catmuni\"");
	include ('inc/consulta_cabecera.php');
?>
<table width="100%" border="0" cellspacing="0" cellpadding="10">
  <tr><td>
<table width="100%" class="marco_general">
  <tr><td>
	<table width="100%" class="marco_individual">
	  <tr>
		<td>
		<table width="100%" class="titulo_general">
		  <tr>
			<td>&nbsp;&nbsp;UBICACI&Oacute;N GEOGR&Aacute;FICA</td>
		  </tr>
		</table>
		<table width='100%' align='center' class='general'>
			<thead>
			  <tr>
				<th width='25%' align='center'><?php echo(getTablaCampo('peru_info_gl','nom_dpto'));?></th>
<?php	if($catmuni==2) {
			print "<th width='25%'>".getTablaCampo('peru_info_gl','nom_prov')."</th>";
			print "<th width='25%'>".getTablaCampo('peru_info_gl','nom_dist')."</th>";
		} else {
			print "<th width='25%'>".getTablaCampo('peru_info_gl','nom_prov')."</th>";
		}
?>
				<th width='25%'><?php echo(getTablaCampo('peru_info_gl','cod_dist'));?></th>
			  </tr>
			</thead>
			<tbody>
			  <tr>
<?php	if($catmuni==2) {
			print "<td align='center' class='texto'>".pg_fetch_result($rsDet,0,"\"nom_dpto\"")."</td>";
			print "<td align='center' class='texto'>".pg_fetch_result($rsDet,0,"\"nom_prov\"")."</td>";
			print "<td align='center' class='texto'>".pg_fetch_result($rsDet,0,"\"nom_dist\"")."</td>";
			print "<td align='center' class='texto'>".pg_fetch_result($rsDet,0,"\"cod_dist\"")."</td>";
		} else {
			print "<td align='center' class='texto'>".pg_fetch_result($rsDet,0,"\"nom_dpto\"")."</td>";
			print "<td align='center' class='texto'>".pg_fetch_result($rsDet,0,"\"nom_prov\"")."</td>";
			print "<td align='center' class='texto'>".pg_fetch_result($rsDet,0,"\"cod_prov\"")."</td>";
		}
?>
			  </tr>
			</tbody>
		</table>
		</td>
	  </tr>
	</table>
	<br>
	<table width="100%" class="marco_individual">
	  <tr>
		<td>
		<table width="100%" class="titulo_general">
		  <tr>
			<td>&nbsp;&nbsp;DATOS GENERALES</td>
		  </tr>
		</table>
		<table width='100%' align='center' class='listado'>
<?php
		print "<tr>";
		print "<td colspan='2' align='left' class='lista_titulo'><b>DATOS DE GOBIERNO LOCAL</td>";
		print " </tr>";

		print "<tr>";
		print "<td width='55%' class='texto'>".getTablaCampo('peru_info_gl','nom_muni')."</td>";
		print "<td width='45%'  class='texto'>" . pg_fetch_result($rsDet,0,"\"nom_muni\"") . "&nbsp;</td>";
		print "</tr>";
		
		print "<tr>";
		print "<td class='texto'>".getTablaCampo('peru_info_gl','p10')."</td>";
		print "<td  class='texto'>" . pg_fetch_result($rsDet,0,"\"p10\"") . "&nbsp;</td>";
		print "</tr>";

		print "<tr>";
		print "<td width='55%' class='texto'>".getTablaCampo('peru_info_gl','cargo')."</td>";
		print "<td width='45%'  class='texto'>" . pg_fetch_result($rsDet,0,"\"cargo\"") . "&nbsp;</td>";
		print "</tr>";

		print "<tr>";
		print "<td width='55%' class='texto'>Direccion de la municipalidad</td>";
		print "<td width='45%'  class='texto'>" . pg_fetch_result($rsDet,0,"\"dir_mun\"") . "&nbsp;</td>";
		print "</tr>";

		// print "<tr>";
		// print "<td class='texto'>".getTablaCampo('peru_info_gl','p04')."</td>";
		// print "<td class='texto'>" . pg_fetch_result($rsDet,0,"\"p04\"") . "&nbsp;</td>";
		// print "</tr>";

		print "<tr>";
		print "<td class='texto'>".getTablaCampo('peru_info_gl','cc')."</td>";
		print "<td class='texto'>" . pg_fetch_result($rsDet,0,"\"cc\"") . "&nbsp;</td>";
		print "</tr>";

		print "<tr>";
		print "<td class='texto'>".getTablaCampo('peru_info_gl','p06_s')."</td>";
		print "<td class='texto'>" . pg_fetch_result($rsDet,0,"\"p06_s\"") . "&nbsp;</td>";
		print "</tr>";

		print "<tr>";
		print "<td class='texto'>".getTablaCampo('peru_info_gl','p08')."</td>";
		print "<td class='texto'>" . pg_fetch_result($rsDet,0,"\"p08\"") . "&nbsp;</td>";
		print "</tr>";

		print "<tr>";
		print "<td class='texto'>".getTablaCampo('peru_info_gl','p07')."</td>";
		print "<td class='texto'>" . pg_fetch_result($rsDet,0,"\"p07\"") . "&nbsp;</td>";
		print "</tr>";

		print "<tr>";
		print "<td class='texto'>".getTablaCampo('peru_info_gl','p09')."</td>";
		print "<td class='texto'><a href=http://".pg_fetch_result($rsDet,0,"\"p09\"")." target='_blank'>" . pg_fetch_result($rsDet,0,"\"p09\"")."</a></td>";
		print "</tr>";


		if(pg_fetch_result($rsDet,0,"\"p17_1_s\"")==1){
			$p17_1_s='Tiene';
		}else{
			$p17_1_s='No tiene';
		}
		print "<tr>";
		print"<td class='texto'>".getTablaCampo('peru_info_gl','p17_1_s')."</td>";
		print "<td class='texto'>" . $p17_1_s . "&nbsp;</td>";
		print "</tr>";

		print "<tr>";
		print "<td class='texto'>".getTablaCampo('peru_info_gl','p17a_1_s')."</td>";
		print "<td class='texto'>" . pg_fetch_result($rsDet,0,"\"p17a_1_s\"") . "&nbsp;</td>";
		print "</tr>";
		$p17a_2 = pg_fetch_result($rsDet,0,"\"p17a_2_s\"");
		if($p17a_2==1){
			$p17a_2='Banda ancha inalámbrica (Wifi)';
		}else if($p17a_2==2){
			$p17a_2='Banda ancha móvil (Modem, USB)';
		}else if($p17a_2==3){
			$p17a_2='Línea digital (ADSL,DSL)';
		}else if($p17a_2==4){
			$p17a_2='Satelital';
		}else if($p17a_2==5){
			$p17a_2='Cable de fibra óptica';
		}else if($p17a_2==6){
			$p17a_2='Otro / Especifique';
		}
		print "<tr>";
		print "<td class='texto'>".getTablaCampo('peru_info_gl','p17a_2_s')."</td>";
		print "<td class='texto'>" .$p17a_2. "&nbsp;</td>";
		print "</tr>";

		print "<tr>";
		print "<td colspan='2' align='left' class='lista_titulo'><b>REQUIERE ASISTENCIA TÉCNICA?</td>";
		print "</tr>";
		if(pg_fetch_result($rsDet,0,"\"p22_at1_s\"")==1){
			$p22_at1_s='Requiere';
		}else{
			$p22_at1_s='No Requiere';
		}
		print "<tr>";
		print "<td class='texto'>".getTablaCampo('peru_info_gl','p22_at1_s')."</td>";
		print "<td class='texto'>" . $p22_at1_s . "&nbsp;</td>";
		print "</tr>";

		if(pg_fetch_result($rsDet,0,"\"p23_20_s\"")==1){
			$p23_20_s='Requiere';
		}else{
			$p23_20_s='No Requiere';
		}
		print "<tr>";
		print "<td class='texto'>".getTablaCampo('peru_info_gl','p23_20_s')."</td>";
		print "<td class='texto'>" . $p23_20_s. "&nbsp;</td>";
		print "</tr>";




		print "<tr>";
		print "<td colspan='2' align='left' class='lista_titulo'><b>REQUIERE CAPACITACIÓN?</td>";
		print "</tr>";

		if(pg_fetch_result($rsDet,0,"\"p24_8_s\"")==1){
			$p24_8_s='Requiere';
		}else{
			$p24_8_s='No Requiere';
		}
		print "<tr>";
		print "<td class='texto'>".getTablaCampo('peru_info_gl','p24_8_s')."</td>";
		print "<td class='texto'>" . $p24_8_s . "&nbsp;</td>";
		print "</tr>";

		if(pg_fetch_result($rsDet,0,"\"p24_16_s\"")==1){
			$p24_16_s='Requiere';
		}else{
			$p24_16_s='No Requiere';
		}
		print "<tr>";
		print "<td class='texto'>".getTablaCampo('peru_info_gl','p24_16_s')."</td>";
		print "<td class='texto'>" .$p24_16_s. "&nbsp;</td>";
		print "</tr>";
			if(pg_fetch_result($rsDet,0,"\"p24_20_s\"")==1){
			$p24_20_s='Requiere';
		}else{
			$p24_20_s='No Requiere';
		}
		print "<tr>";
		print "<td class='texto'>".getTablaCampo('peru_info_gl','p24_20_s')."</td>";
		print "<td class='texto'>" .$p24_20_s. "&nbsp;</td>";
		print "</tr>";



		print "<tr>";
		print "<td colspan='2' align='left' class='lista_titulo'><b>CUENTA CON INSTRUMENTOS DE GESTIÓN Y DESARROLLO URBANO Y/O RURAL?</td>";
		print "</tr>";

		if(pg_fetch_result($rsDet,0,"\"p25_1_s\"")==1){
			$p25_1_s='Tiene';
		}else{
			$p25_1_s='No Tiene';
		}
		print "<tr>";
		print "<td class='texto'>".getTablaCampo('peru_info_gl','p25_1_s')."</td>";
		print "<td class='texto'>" . $p25_1_s . "&nbsp;</td>";
		print "</tr>";
		if(pg_fetch_result($rsDet,0,"\"p25_2_s\"")==1){
			$p25_2_s='Tiene';
		}else{
			$p25_2_s='No Tiene';
		}
		print "<tr>";
		print "<td class='texto'>".getTablaCampo('peru_info_gl','p25_2_s')."</td>";
		print "<td class='texto'>" . $p25_2_s . "&nbsp;</td>";
		print "</tr>";



		if(pg_fetch_result($rsDet,0,"\"p25_3_s\"")==1){
			$p25_3_s='Tiene';
		}else{
			$p25_3_s='No Tiene';
		}
		print "<tr>";
		print "<td class='texto'>".getTablaCampo('peru_info_gl','p25_3_s')."</td>";
		print "<td class='texto'>" . $p25_3_s . "&nbsp;</td>";
		print "</tr>";
		if(pg_fetch_result($rsDet,0,"\"p25_5_s\"")==1){
			$p25_5_s='Tiene';
		}else{
			$p25_5_s='No Tiene';
		}
		print "<tr>";
		print "<td class='texto'>".getTablaCampo('peru_info_gl','p25_5_s')."</td>";
		print "<td class='texto'>" . $p25_5_s . "&nbsp;</td>";
		print "</tr>";
		if(pg_fetch_result($rsDet,0,"\"p25_6_s\"")==1){
			$p25_6_s='Tiene';
		}else{
			$p25_6_s='No Tiene';
		}
		print "<tr>";
		print "<td class='texto'>".getTablaCampo('peru_info_gl','p25_6_s')."</td>";
		print "<td class='texto'>" . $p25_6_s . "&nbsp;</td>";
		print "</tr>";
	
		if(pg_fetch_result($rsDet,0,"\"p25_6_1\"")==0){
			$p25_6_1='Sin Informacion';
		}else{
			$p25_6_1=(pg_fetch_result($rsDet,0,"\"p25_6_1\""));
		}
		print "<tr>";
		print "<td class='texto'>".getTablaCampo('peru_info_gl','p25_6_1')."</td>";
		print "<td class='texto'>" . $p25_6_1 . "&nbsp;</td>";
		print "</tr>";

		if(pg_fetch_result($rsDet,0,"\"p25_6_2\"")==1){
			$p25_6_2='Falta de aprobación del consejo';
		}else if(pg_fetch_result($rsDet,0,"\"p25_6_2\"")==2){
			$p25_6_2='En elaboración';
		}else if(pg_fetch_result($rsDet,0,"\"p25_6_2\"")==3){
			$p25_6_2='Falta de Recursos para su elaboración';
		}else if(pg_fetch_result($rsDet,0,"\"p25_6_2\"")==4){
			$p25_6_2='Otros';
		}
		else if(pg_fetch_result($rsDet,0,"\"p25_6_2\"")==0){
			$p25_6_2='Sin Información';
		}
		print "<tr>";
		print "<td class='texto'>".getTablaCampo('peru_info_gl','p25_6_2')."</td>";
		print "<td class='texto'>" . $p25_6_2 . "&nbsp;</td>";
		print "</tr>";
		
		if(pg_fetch_result($rsDet,0,"\"p25_7_s\"")==1){
			$p25_7_s='Tiene';
		}else{
			$p25_7_s='No Tiene';
		}
		print "<tr>";
		print "<td class='texto'>".getTablaCampo('peru_info_gl','p25_7_s')."</td>";
		print "<td class='texto'>" . $p25_7_s . "&nbsp;</td>";
		print "</tr>";

		if(pg_fetch_result($rsDet,0,"\"p25_7_1\"")==0){
			$p25_7_1='Sin Informacion';
		}else{
			$p25_7_1=(pg_fetch_result($rsDet,0,"\"p25_7_1\""));
		}
		print "<tr>";
		print "<td class='texto'>".getTablaCampo('peru_info_gl','p25_7_1')."</td>";
		print "<td class='texto'>" . $p25_7_1 . "&nbsp;</td>";
		print "</tr>";

		if(pg_fetch_result($rsDet,0,"\"p25_7_2\"")==1){
			$p25_7_2='Falta de aprobación del consejo';
		}else if(pg_fetch_result($rsDet,0,"\"p25_7_2\"")==2){
			$p25_7_2='En elaboración';
		}else if(pg_fetch_result($rsDet,0,"\"p25_7_2\"")==3){
			$p25_7_2='Falta de Recursos para su elaboración';
		}else if(pg_fetch_result($rsDet,0,"\"p25_7_2\"")==4){
			$p25_7_2='Otros';
		}
		else if(pg_fetch_result($rsDet,0,"\"p25_7_2\"")==0){
			$p25_7_2='Sin Información';
		}
		print "<tr>";
		print "<td class='texto'>".getTablaCampo('peru_info_gl','p25_7_2')."</td>";
		print "<td class='texto'>" . $p25_7_2 . "&nbsp;</td>";
		print "</tr>";

		if(pg_fetch_result($rsDet,0,"\"p25_8_s\"")==1){
			$p25_8_s='Tiene';
		}else{
			$p25_8_s='No Tiene';
		}
				print "<tr>";
		print "<td class='texto'>".getTablaCampo('peru_info_gl','p25_8_s')."</td>";
		print "<td class='texto'>" . $p25_8_s . "&nbsp;</td>";
		print "</tr>";
		if(pg_fetch_result($rsDet,0,"\"p25_11_s\"")==1){
			$p25_11_s='Tiene';
		}else{
			$p25_11_s='No Tiene';
		}
		print "<tr>";
		print "<td class='texto'>".getTablaCampo('peru_info_gl','p25_11_s')."</td>";
		print "<td class='texto'>" . $p25_11_s . "&nbsp;</td>";
		print "</tr>";

		print "<tr>";
		print "<td colspan='2' align='left' class='lista_titulo'><b>CUENTA CON INSTRUMENTOS DE GESTIÓN DE RESIDUOS SÓLIDOS?</td>";
		print "</tr>";

		if(pg_fetch_result($rsDet,0,"\"p46_1_s\"")==0){
			$p46_1_s='Si';
		}else{
			$p46_1_s='No';
		}
		print "<tr>";
		print "<td class='texto'>".getTablaCampo('peru_info_gl','p46_1_s')."</td>";
		print "<td class='texto'>" . $p46_1_s . "&nbsp;</td>";
		print "</tr>";

		print "<tr>";
		print "<td colspan='2' align='left' class='lista_titulo'><b>CUENTA CON INSTRUMENTOS DE GESTIÓN DEL RIESGO DE DESASTRES?</td>";
		print "</tr>";

		if(pg_fetch_result($rsDet,0,"\"p84_1_s\"")==0){
			$p84_1_s='Si';
		}else{
			$p84_1_s='No';
		}
		print "<tr>";
		print "<td class='texto'>".getTablaCampo('peru_info_gl','p84_1_s')."</td>";
		print "<td class='texto'>" . $p84_1_s . "&nbsp;</td>";
		print "</tr>";


		print "<tr>";
		print "<td colspan='2' align='left' class='lista_titulo'><b>CONSEJO DE COORDINACION LOCAL (CCL)?	</td>";
		print "</tr>";

		if(pg_fetch_result($rsDet,0,"\"p26\"")==1){
			$p26='Constituido';
		}else if(pg_fetch_result($rsDet,0,"\"p26\"")==2){
			$p26='No constituido';
		}
		print "<tr>";
		print "<td class='texto'>".getTablaCampo('peru_info_gl','p26')."</td>";
		print "<td class='texto'>" . $p26. "&nbsp;</td>";
		print "</tr>";

		if(pg_fetch_result($rsDet,0,"\"p27\"")==1){
			$p27='Ejecutó';
		}else if(pg_fetch_result($rsDet,0,"\"p27\"")==0){
			$p27='No Ejecutó';
		}
		print "<tr>";
		print "<td class='texto'>".getTablaCampo('peru_info_gl','p27')."</td>";
		print "<td class='texto'>" . $p27. "&nbsp;</td>";
		print "</tr>";
		print "<tr>";
		print "<td colspan='2' align='left' class='lista_titulo'><b>CATASTRO MUNICIPAL?	</td>";
		print "</tr>";
		if(pg_fetch_result($rsDet,0,"\"p28_1\"")==1){
			$p28_1='Tiene';
		}else if(pg_fetch_result($rsDet,0,"\"p28_1\"")==2){
			$p28_1='No tiene';
		}
		print "<tr>";
		print "<td class='texto'>".getTablaCampo('peru_info_gl','p28_1')."</td>";
		print "<td class='texto'>" . $p28_1. "&nbsp;</td>";
		print "</tr>";

		print "<tr>";
		print "<td class='texto'>".getTablaCampo('peru_info_gl','p28_1_1')."</td>";
		print "<td class='texto'>" . pg_fetch_result($rsDet,0,"\"p28_1_1\""). "&nbsp;</td>";
		print "</tr>";

		if(pg_fetch_result($rsDet,0,"\"p28_2\"")==1){
			$p28_2='S&iacute;';
		}	else if(pg_fetch_result($rsDet,0,"\"p28_2\"")==2){
			$p28_2='No';
		}else if(pg_fetch_result($rsDet,0,"\"p28_2\"")==0){
			$p28_2='Sin Informacion';
		}
		print "<tr>";
		print "<td class='texto'>".getTablaCampo('peru_info_gl','p28_2')."</td>";
		print "<td class='texto'>" . $p28_2. "&nbsp;</td>";
		print "</tr>";

		print "<tr>";
		print "<td class='texto'>".getTablaCampo('peru_info_gl','p28_2_1')."</td>";
		print "<td class='texto'>" . pg_fetch_result($rsDet,0,"\"p28_2_1\""). "</td>";
		print "</tr>";

		print "<tr>";
		print "<td colspan='2' align='left' class='lista_titulo'><b>RESIDUOS SÓLIDOS: RECOJO Y SALUBRIDAD</td>";
		print "</tr>";
		
		print "<tr>";
		print "<td width='55%' class='texto'>".getTablaCampo('peru_info_gl','p44_1_s')."</td>";
		print "<td width='45%'  class='texto'>" . pg_fetch_result($rsDet,0,"\"p44_1_s\"") . "&nbsp;</td>";
		print "</tr>";

		print "<tr>";
		print "<td width='55%' class='texto'>".getTablaCampo('peru_info_gl','p47_1_s')."</td>";
		print "<td width='45%'  class='texto'>" . pg_fetch_result($rsDet,0,"\"p47_1_s\"") . "&nbsp;</td>";
		print "</tr>";

		print "<tr>";
		print "<td width='55%' class='texto'>".getTablaCampo('peru_info_gl','p47_2_s')."</td>";
		print "<td width='45%'  class='texto'>" . pg_fetch_result($rsDet,0,"\"p47_2_s\"") . "&nbsp;</td>";
		print "</tr>";

		print "<tr>";
		print "<td width='55%' class='texto'>".getTablaCampo('peru_info_gl','p47_3_s')."</td>";
		print "<td width='45%'  class='texto'>" . pg_fetch_result($rsDet,0,"\"p47_3_s\"") . "&nbsp;</td>";
		print "</tr>";

		print "<tr>";
		print "<td width='55%' class='texto'>".getTablaCampo('peru_info_gl','p47_5_s')."</td>";
		print "<td width='45%'  class='texto'>" . pg_fetch_result($rsDet,0,"\"p47_5_s\"") . "&nbsp;</td>";
		print "</tr>";

		print "<tr>";
		print "<td colspan='2' align='left' class='lista_titulo'><b>SEGURIDAD CIUDADANA	</td>";
		print "</tr>";

			if(pg_fetch_result($rsDet,0,"\"p80_s\"")==1){
			$p80_s='Conform&oacute;';
		}else if(pg_fetch_result($rsDet,0,"\"p80_s\"")==2){
			$p80_s='No Conform&oacute;';
		}
			print "<tr>";
		print "<td class='texto'>".getTablaCampo('peru_info_gl','p80_s')."</td>";
		print "<td class='texto'>" . $p80_s. "&nbsp;</td>";
		print "</tr>";

		if(pg_fetch_result($rsDet,0,"\"p83_1_s\"")==1){
			$p83_1_s='Tiene';
		}else if(pg_fetch_result($rsDet,0,"\"p83_1_s\"")==0){
			$p83_1_s='No Tiene';
		}
		print "<tr>";
		print "<td class='texto'>".getTablaCampo('peru_info_gl','p83_1_s')."</td>";
		print "<td class='texto'>" . $p83_1_s. "&nbsp;</td>";
		print "</tr>";

		if(pg_fetch_result($rsDet,0,"\"p83_2_s\"")==1){
			$p83_2_s='Tiene';
		}else if(pg_fetch_result($rsDet,0,"\"p83_2_s\"")==0){
			$p83_2_s='No Tiene';
		}
		print "<tr>";
		print "<td class='texto'>".getTablaCampo('peru_info_gl','p83_2_s')."</td>";
		print "<td class='texto'>" . $p83_2_s. "&nbsp;</td>";
		print "</tr>";

		if(pg_fetch_result($rsDet,0,"\"p83_3_s\"")==1){
			$p83_3_s='Tiene';
		}else if(pg_fetch_result($rsDet,0,"\"p83_3_s\"")==0){
			$p83_3_s='No Tiene';
		}
		print "<tr>";
		print "<td class='texto'>".getTablaCampo('peru_info_gl','p83_3_s')."</td>";
		print "<td class='texto'>" . $p83_3_s. "&nbsp;</td>";
		print "</tr>";

		if(pg_fetch_result($rsDet,0,"\"p74_s\"")==1){
			$p74_s='S&iacute;';
		}else if(pg_fetch_result($rsDet,0,"\"p74_s\"")==0){
			$p74_s='No Tiene';
		}
			print "<tr>";
		print "<td class='texto'>".getTablaCampo('peru_info_gl','p74_s')."</td>";
		print "<td class='texto'>" . $p74_s. "&nbsp;</td></tr>";

		print "<tr>";
		print "<td class='texto'>".getTablaCampo('peru_info_gl','p74_2_t_s')."</td>";
		print "<td class='texto'>" .pg_fetch_result($rsDet,0,"\"p74_2_t_s\""). "&nbsp;</td>";
		print "</tr>";

		if(pg_fetch_result($rsDet,0,"\"p77_s\"")==1){
			$p77_s='S&iacute;';
		}else if(pg_fetch_result($rsDet,0,"\"p77_s\"")==0){
			$p77_s='No';
		}
		print "<tr>";
		print "<td class='texto'>".getTablaCampo('peru_info_gl','p77_s')."</td>";
		print "<td class='texto'>" . $p77_s. "&nbsp;</td>";
		print "</tr>";

		print "<tr>";
		print "<td colspan='2' align='left' class='lista_titulo'><b>GESTION DEL RIESGO DE DESASTRES		</td>";
		print "</tr>";

		if(pg_fetch_result($rsDet,0,"\"p86\"")==1){
			$p86='Si';
		}
		else if(pg_fetch_result($rsDet,0,"\"p86\"")==0){
			$p86='No ';
		}
		print "<tr>";
		print "<td class='texto'>".getTablaCampo('peru_info_gl','p86')."</td>";
		print "<td class='texto'>" . $p86. "&nbsp;</td></tr>";

		if(pg_fetch_result($rsDet,0,"\"p87\"")==1){
			$p87='Tiene';
		}
		else if(pg_fetch_result($rsDet,0,"\"p87\"")==0){
			$p87='No Tiene';
		}
		print "<tr>";
		print "<td class='texto'>".getTablaCampo('peru_info_gl','p87')."</td>";
		print "<td class='texto'>" . $p87. "&nbsp;</td></tr>";


		// // 		print "<tr>";
		// // print "<td colspan='2' align='left' class='lista_titulo'><b>INFRAESTRUCTURA Y  COMUNICACI&Oacute;N		</td>";
		// // print "</tr>";

		// if(pg_fetch_result($rsDet,0,"\"p112_4\"")==1){
		// 	$p112_4='S&iacute;';
		// }else if(pg_fetch_result($rsDet,0,"\"p112_4\"")==2){
		// 	$p112_4='No';
		// }
		// 	print "<tr>";
		// print "<td class='texto'>".getTablaCampo('peru_info_gl','p112_4')."</td>";
		// print "<td class='texto'>" . $p112_4. "&nbsp;</td></tr>";
		// print "<tr>";
		// print "<td class='texto'>".getTablaCampo('peru_info_gl','p112a_4')."</td>";
		// print "<td class='texto'>" .pg_fetch_result($rsDet,0,"\"p112a_4\""). "&nbsp;</td>";
		// print "</tr>";
?>
		</table>
		<table width="100%" align='center' class='fuente_general'>
		  <tr>
			<td><b>Fuente:</b>
				<br><?php echo(pg_fetch_result($rsDet,0,"\"fuente\"")); ?>
			</td>
		  </tr>
		</table>
		</td>
	  </tr>
	</table>
	<br>

	<?php
	$name=$log;
	$capa='consulta_goblocal';
	if (!isset($_GET['excel'])) {
		$ruta=$capa.'.phtml?excel=excel&capa='.$capa.'&ovalor='.$pvalor;
		include 'inc/consulta_pie.php';
	}
	if (isset($_SESSION['usuario'])) {
		grabar_log_accesos('ingreso', $cod_user, $name, $descripcion);
	}
	?>
		</td></tr>
	</table>
	</td></tr>
</table>
</body>
</html>
<?php include_once("./analyticstracking.php");?>
