<?php

if (isset($_GET['excel']) && ($_GET['excel']=='excel')){
	header("Content-type:application/x-msexcel");
	$file=$_GET['capa'];
	header("Content-Disposition: attachment; filename=".$file.".xls");
	$imgtitulo='';
} else{
	$imgtitulo='<img src="imajes/desplegable.png" width="11" height="11">';
}

/*@session_start();
	if(empty($_SESSION['usuario'])){
        header('Location: ../index.php');
	}else{$cod_user = $_SESSION['usuario'];}*/
	include ('conexion_postgres.phtml');
	include ('injection/funciones.php');
	$player = limpiarCadena($_GET['olayer']);
	$pcampo = limpiarCadena($_GET['ocampo']);
	$pvalor = limpiarNumeros($_GET['ovalor']);
	$linkPG = Conectarse_POSTGRES();
    // Browse Data
    // select pec.cod_des_op, pec.tot_vot,pec.desc_op, pd.cod_dist, pd.nom_dist, pd.cod_prov , pd.nom_prov, pd.cod_dpto, pd.nom_dpto,pd.the_geom from peru_elecciones_congresales pec
	//   	inner join peru_distritos pd on pd.cod_dist = pec.cod_dist where pd.cod_dist = '010101';
	$sQueryS = "select * from vw_peru_suscept_fisica";
	$sQueryW = "  where gid = " . $pvalor;

	$sQuery = $sQueryS . $sQueryW;
	$rsDet = pg_query( $linkPG , $sQuery );
	$titulo_ventana = 'Susceptibilidad Física a procesos naturales e inducidos';
	$titulo = 'Susceptibilidad Física a procesos naturales e inducidos';
	include ('inc/consulta_cabecera.php');
?>
<table width="100%" border="0" cellspacing="0" cellpadding="10">
  <tr><td>
	<table width="100%" class="marco_general">
	  <tr><td>
		
		<br>
		<table width="100%" class="marco_individual">
		  <tr>
			<td>
				<table width="100%" class="titulo_general">
					  <tr>
						<td>&nbsp;&nbsp;DATOS GENERALES</td>
					  </tr>
				</table>
			<table width='100%' align='center' class='general'>

                    <tr>
						<td width='50%' class='texto1'>Nivel de Susceptibilidad Física</td>
						<td width='50%' class='texto1' style='text-align:right;'><?php echo(pg_fetch_result($rsDet,0,"\"desc_susce\"")) ?></td>
					</tr>
                    <tr>
						<td width='50%' class='texto1'>Valor de Susceptibilidad Física</td>
						<td width='50%' class='texto1' style='text-align:right;'><?php  echo(pg_fetch_result($rsDet,0,"\"val_suscep\"")) ?></td>
					</tr>

					<tr>
						<td width='50%' class='texto1'>Superficie (hectáreas)</td>
						<td width='50%' class='texto1' style='text-align:right;'><?php  echo(pg_fetch_result($rsDet,0,"\"hectares\"")) ?></td>
					</tr>

					<tr>
						<td width='50%' class='texto1'>Región Natural</td>
						<td width='50%' class='texto1' style='text-align:right;'><?php  echo(pg_fetch_result($rsDet,0,"\"region\"")) ?></td>
					</tr>

					<tr>
						<td width='50%' class='texto1'>Litología</td>
						<td width='50%' class='texto1' style='text-align:right;'><?php  echo(pg_fetch_result($rsDet,0,"\"lito_des\"")) ?></td>
					</tr>

					<tr>
						<td width='50%' class='texto1'>Fisiografía</td>
						<td width='50%' class='texto1' style='text-align:right;'><?php  echo(pg_fetch_result($rsDet,0,"\"fisiog1\"")) ?></td>
					</tr>

					<tr>
						<td width='50%' class='texto1'>Cobertura y uso actual</td>
						<td width='50%' class='texto1' style='text-align:right;'><?php  echo(pg_fetch_result($rsDet,0,"\"cobuso\"")) ?></td>
					</tr>

					<tr>
						<td width='50%' class='texto1'>Precipitación (mm)</td>
						<td width='50%' class='texto1' style='text-align:right;'><?php  echo(pg_fetch_result($rsDet,0,"\"pp_prom\"")) ?></td>
					</tr>

					<tr>
						<td width='50%' class='texto1'>Pendiente (%)</td>
						<td width='50%' class='texto1' style='text-align:right;'><?php  echo(pg_fetch_result($rsDet,0,"\"pendt\"")) ?></td>
					</tr>
			</table>
			</td>
		  </tr>
		</table>
		<br>
		
		<table class='fuente_general' width="100%"><thead><tr><th><b>Fuente:</b>
			<br><?php echo pg_fetch_result($rsDet,0,"\"fuente\"");?></th></tr></thead>
		</table>
	<?php
	//$name=strtoupper(pg_fetch_result($rsDet,0,"\"tipoaerona\"").' - '.pg_fetch_result($rsDet,0,"\"label\""));
	$name='Susceptibilidad Física a procesos naturales e inducidos';
	$capa='consulta_suscept_fisica';
	if (!isset($_GET['excel'])) {
		$ruta=$capa.'.phtml?excel=excel&capa='.$capa.'&ovalor='.$pvalor.'&olayer=peru_suscept_fisica'.'&ocampo=gid';
		include 'inc/consulta_pie.php';
	}
	if (isset($_SESSION['usuario'])) {
		grabar_log_accesos('ingreso', $cod_user, $name, $descripcion);
	}
	?>
		</td>
	  </tr>
	</table>
	</td>
  </tr>
</table>
</body>
</html>
<?php include_once("./analyticstracking.php");?>


