<?php

if (isset($_GET['excel']) && ($_GET['excel']=='excel')){
	header("Content-type:application/x-msexcel");
	$file=$_GET['capa'];
	header("Content-Disposition: attachment; filename=".$file.".xls");
	$imgtitulo='';
} else{
	$imgtitulo='<img src="imajes/desplegable.png" width="11" height="11">';
}

/*@session_start();
	if(empty($_SESSION['usuario'])){
        header('Location: ../index.php');
	}else{$cod_user = $_SESSION['usuario'];}*/
	include ('conexion_postgres.phtml');
	include ('injection/funciones.php');
	$player = limpiarCadena($_GET['olayer']);
	$pcampo = limpiarCadena($_GET['ocampo']);
	$pvalor = limpiarNumeros($_GET['ovalor']);
	$linkPG = Conectarse_POSTGRES();
    // Browse Data
    // select pec.cod_des_op, pec.tot_vot,pec.desc_op, pd.cod_dist, pd.nom_dist, pd.cod_prov , pd.nom_prov, pd.cod_dpto, pd.nom_dpto,pd.the_geom from peru_elecciones_congresales pec
	//   	inner join peru_distritos pd on pd.cod_dist = pec.cod_dist where pd.cod_dist = '010101';
	$sQueryS = "select * from vw_peru_defunciones_sinadef";
	$sQueryW = "  where gid = " . $pvalor;

	$sQuery = $sQueryS . $sQueryW;
	$rsDet = pg_query( $linkPG , $sQuery );
	$titulo_ventana = 'Defunciones 2021 - Nivel de distrito';
	$titulo = 'Defunciones 2021 - Nivel de distrito';
	include ('inc/consulta_cabecera.php');
?>
<table width="100%" border="0" cellspacing="0" cellpadding="10">
  <tr><td>
	<table width="100%" class="marco_general">
	  <tr><td>
		<table width="100%" class="marco_individual">
		  <tr>
			<td>
				<table width="100%" class="titulo_general">
				  <tr>
					<td>&nbsp;&nbsp;UBICACI&Oacute;N GEOGR&Aacute;FICA</td>
				  </tr>
				</table>
				<table width='100%' align='center' class='general'>
					<thead>
					  <tr>
						<th width='25%'>Departamento</th>
						<th width='25%'>Provincia</th>
						<th width='25%'>Distrito</th>
						<th width='25%'>Codigo Distrito</th>
					  </tr>
					</thead>
					<tbody>
					<tr>
						<td align='center' class='texto'><?php echo(pg_fetch_result($rsDet,0,"\"nom_dpto\"")) ?></td>
						<td align='center' class='texto'><?php echo(pg_fetch_result($rsDet,0,"\"nom_prov\"")) ?></td>
						<td align='center' class='texto'><?php echo(pg_fetch_result($rsDet,0,"\"nom_dist\"")) ?></td>
						<td align='center' class='texto'><?php echo(pg_fetch_result($rsDet,0,"\"cod_dist\"")) ?></td>
					</tr>
	
					</tbody>
				</table>
			</td>
		  </tr>
		</table>
		<br>
		<table width="100%" class="marco_individual">
		  <tr>
			<td>
				<table width="100%" class="titulo_general">
					  <tr>
						<td>&nbsp;&nbsp;DATOS GENERALES</td>
					  </tr>
				</table>
			<table width='100%' align='center' class='general'>

                    <tr>
						<td width='50%' class='texto1' colspan="2">Población (hab.)</td>
						<td width='50%' class='texto1' style='text-align:right;'><?php echo(pg_fetch_result($rsDet,0,"\"pob_2020\"")) ?></td>
					</tr>
                    <tr>
						<td width='50%' class='texto1' colspan="2">Número de defunciones 2021</td>
						<td width='50%' class='texto1' style='text-align:right;'><?php  echo(pg_fetch_result($rsDet,0,"\"num_defun\"")) ?></td>
					</tr>
                    
					<tr>
						<td width='50%' class='texto1' rowspan="2">Defunciones según sexo</td>
						<td width='50%' class='texto1'>Número de hombres fallecidos</td>
						<td width='50%' class='texto1' style='text-align:right;'><?php  echo(pg_fetch_result($rsDet,0,"\"sx_masc\"")) ?></td>
					</tr>

                    <tr>
						<td width='50%' class='texto1'>Número de mujeres fallecidas</td>
						<td width='50%' class='texto1' style='text-align:right;'><?php  echo(pg_fetch_result($rsDet,0,"\"sx_feme\"")) ?></td>
					</tr>

					
                    <tr>
						<td width='50%' class='texto1' rowspan="3">Defunciones registradas por mes</td>
						<td width='50%' class='texto1'>Número de defunciones en el mes de Enero de 2021</td>
						<td width='50%' class='texto1' style='text-align:right;'><?php  echo(pg_fetch_result($rsDet,0,"\"ene_21\"")) ?></td>
					</tr>
                    <tr>
						<td width='50%' class='texto1'>Número de defunciones en el mes de Febrero de 2021</td>
						<td width='50%' class='texto1' style='text-align:right;'><?php  echo(pg_fetch_result($rsDet,0,"\"feb_21\"")) ?></td>
					</tr>

					<tr>
						<td width='50%' class='texto1'>Número de defunciones en el mes de Marzo de 2021</td>
						<td width='50%' class='texto1' style='text-align:right;'><?php  echo(pg_fetch_result($rsDet,0,"\"mar_21\"")) ?></td>
					</tr>


					<tr>
						<td width='50%' class='texto1' rowspan="2">Necropsias</td>
						<td width='50%' class='texto1'>Número de necropsias realizadas</td>
						<td width='50%' class='texto1' style='text-align:right;'><?php  echo(pg_fetch_result($rsDet,0,"\"necro_si\"")) ?></td>
					</tr>
                    <tr>
						<td width='50%' class='texto1'>Número de necropsias no realizadas</td>
						<td width='50%' class='texto1' style='text-align:right;'><?php  echo(pg_fetch_result($rsDet,0,"\"necro_no\"")) ?></td>
					</tr>                 

					<tr>
						<td width='50%' class='texto1' colspan="2">Año de registro de las defunciones</td>
						<td width='50%' class='texto1' style='text-align:right;'><?php  echo(pg_fetch_result($rsDet,0,"\"anio\"")) ?></td>
					</tr>                 
	
			</table>
			</td>
		  </tr>
		</table>
		<br>
		
		<table class='fuente_general' width="100%"><thead><tr><th><b>Fuente:</b>
			<br><?php echo pg_fetch_result($rsDet,0,"\"fuente\"");?></th></tr></thead>
		</table>
	<?php
	//$name=strtoupper(pg_fetch_result($rsDet,0,"\"tipoaerona\"").' - '.pg_fetch_result($rsDet,0,"\"label\""));
	$name='Defunciones 2021 - Nivel de distrito';
	$capa='consulta_fallecidos_sinadef';
	if (!isset($_GET['excel'])) {
		$ruta=$capa.'.phtml?excel=excel&capa='.$capa.'&ovalor='.$pvalor.'&olayer=peru_covid'.'&ocampo=gid';
		include 'inc/consulta_pie.php';
	}
	if (isset($_SESSION['usuario'])) {
		grabar_log_accesos('ingreso', $cod_user, $name, $descripcion);
	}
	?>
		</td>
	  </tr>
	</table>
	</td>
  </tr>
</table>
</body>
</html>
<?php include_once("./analyticstracking.php");?>


