<?php

if (isset($_GET['excel']) && ($_GET['excel']=='excel')) {
	header("Content-type:application/x-msexcel");
	$file=$_GET['capa'];
	header("Content-Disposition: attachment; filename=".$file.".xls");
	$imgtitulo='';
} else {
	$imgtitulo='<img src="imajes/desplegable.png" width="11" height="11">';
}

/*@session_start();
	if(empty($_SESSION['usuario'])){
        header('Location: ../index.php');
	}else{$cod_user = $_SESSION['usuario'];}*/
	include("conexion_postgres.phtml");
	include ('injection/funciones.php');		
	$player = limpiarCadena($_GET['olayer']);
	$pcampo = limpiarCadena($_GET['ocampo']);
	$pvalor = limpiarNumeros($_GET['ovalor']);

	$linkPG = Conectarse_POSTGRES();
	// Browse Data
	$sQueryS = "SELECT *";
	$sQueryF = " FROM vw_peru_muelles";
	$sQueryW = " WHERE gid = '" . $pvalor . "'";

	$sQuery = $sQueryS . $sQueryF . $sQueryW;
	$rsDet = pg_query( $linkPG , $sQuery );

	$titulo_ventana =  strtoupper(pg_fetch_result($rsDet,0,"\"desc_tipo\"")).' - DEPARTAMENTO '.pg_fetch_result($rsDet,0,"nom_dpto");
	$titulo = strtoupper(pg_fetch_result($rsDet,0,"\"desc_tipo\""));

	include ('inc/consulta_cabecera.php');
?>
<table width="100%" border="0" cellspacing="0" cellpadding="10">
  <tr><td>
	<table width="100%" class="marco_general">
	  <tr><td>
		<table width="100%" class="marco_individual">
		  <tr>
			<td>
				<table width="100%" class="titulo_general">
				  <tr>
					<td>&nbsp;&nbsp;UBICACI&Oacute;N GEOGR&Aacute;FICA</td>
				  </tr>
				</table>
				<table width='100%' align='center' class='general'>
					<thead>
					  <tr>
						<th width='25%'>Departamento</th>
						<th width='25%'>Provincia</th>
						<th width='25%'>Distrito</th>
						<th width='25%'>Ubigeo</th>
					  </tr>
					</thead>
					<tbody>
<?php
	print "<tr>
				<td align='center' class='texto'>".pg_fetch_result($rsDet,0,"\"nom_dpto\"")."</td>
				<td align='center' class='texto'>".pg_fetch_result($rsDet,0,"\"nom_prov\"")."</td>
				<td align='center' class='texto'>".pg_fetch_result($rsDet,0,"\"nom_dist\"")."</td>
				<td align='center' class='texto'>".pg_fetch_result($rsDet,0,"\"cod_dist\"")."</td>

				
			</tr>";
?>
					</tbody>
				</table>
			</td>
		  </tr>
		</table>
		<br>
		<table width="100%" class="marco_individual">
		  <tr>
			<td>
				<table width="100%" class="titulo_general">
				  <tr>
					<td>&nbsp;&nbsp;datos generales</td>
				  </tr>
				</table>
				<table width='100%' align='center' class='general'>
	<?php
		print "<tr>
				<td width='40%' class='lista_titulo'>Nombre de la instalaci&oacute;n portuaria</td>
				<td width='60%' class='lista_texto'>".pg_fetch_result($rsDet,0,"\"label\"")."</td>
			  </tr>
			 
			  <tr>
			  <td width='40%' class='lista_titulo'>Código de la instalación portuaria</td>
			  <td width='60%' class='lista_texto'>".pg_fetch_result($rsDet,0,"\"codpuerto\"")."</td>
			  </tr>

			  <tr>
				<td width='40%' class='lista_titulo'>Localidad donde se ubica el puerto</td>
				<td width='60%' class='lista_texto'>".pg_fetch_result($rsDet,0,"\"localidad\"")."</td>
			  </tr>
			  <tr>
				<td class='lista_titulo'>Tipo de instalaci&oacute;n portuaria</td>
				<td class='lista_texto'>".pg_fetch_result($rsDet,0,"\"tipo\"")."</td>
			  </tr>
			  	  <tr>
				<td class='lista_titulo'>Administrador de la infraestructura portuaria</td>
				<td class='lista_texto'>".pg_fetch_result($rsDet,0,"\"administ\"")."</td>
			  </tr>
			  <tr>
				<td class='lista_titulo'>Titular de la administración</td>
				<td class='lista_texto'>".pg_fetch_result($rsDet,0,"\"titular\"")."</td>
			  </tr>
			  <tr>
				<td class='lista_titulo'>Uso de la instalaci&oacute;n portuaria</td>
				<td class='lista_texto'>".pg_fetch_result($rsDet,0,"\"uso\"")."</td>
			  </tr>
			  <tr>
				<td class='lista_titulo'>Estado de la instalaci&oacute;n portuaria</td>
				<td class='lista_texto'>".pg_fetch_result($rsDet,0,"\"estado\"")."</td>
			  </tr>
			  <tr>
              <td class='lista_titulo'>&Aacute;mbito de operaci&oacute;n</td>
              <td class='lista_texto'>".pg_fetch_result($rsDet,0,"\"ambito\"")."</td>
              </tr>
			  <tr>
              <td class='lista_titulo'>Tr&aacute;fico de la instalaci&oacute;n portuaria</td>
              <td class='lista_texto'>".pg_fetch_result($rsDet,0,"\"trafico\""). "</td>
              </tr>
			  <tr>
              <td class='lista_titulo'>Actividad de la instalaci&oacute;n portuaria</td>
              <td class='lista_texto'>".pg_fetch_result($rsDet,0,"\"actividad\"")."</td>
              </tr>
			  <tr>
              <td class='lista_titulo'>Subactividad de la instalación portuaria</td>
              <td class='lista_texto'>".pg_fetch_result($rsDet,0,"\"subactiv\"")."</td>
              </tr>
			  <tr>
				<td class='lista_titulo'> Nivel de alcance de la instalaci&oacute;n portuaria</td>
				<td class='lista_texto'>".pg_fetch_result($rsDet,0,"\"alcance\"")."</td>
			  </tr>
			  <tr>
			  <td class='lista_titulo'> Autorización</td>
			  <td class='lista_texto'>".pg_fetch_result($rsDet,0,"\"autoriza\"")."</td>
			</tr>
			<tr>
				<td class='lista_titulo'> Longitud (x)</td>
				<td class='lista_texto'>".round(pg_fetch_result($rsDet,0,"\"lon\""),6)."</td>
			  </tr> 
			  <tr>
			  <td class='lista_titulo'>Latitud (y)</td>
			  <td class='lista_texto'>".round(pg_fetch_result($rsDet,0,"\"lat\""),6)."</td>
			</tr>"
			;
			
			
	?>
				</table>
			</td>
		  </tr>
		</table>
		<br>
		<!-- <table width="100%" class="marco_individual">
		  <tr>
			<td> -->
				<!-- <table width="100%" class="titulo_general">
				  <tr>
					<td>&nbsp;&nbsp;Reporte de puertos DEL DEPARTAMENTO</td>
				  </tr>
				</table> -->
				<!-- <table width='100%' align='center' class='general'> -->
				<!-- <thead><tr><th>#</th><th>Nombre</th></tr></thead> -->
	<!-- <?php
		$consulta 			= "select * from peru_muelles_2018 where cod_dpto = '".pg_fetch_result($rsDet,0,"\"cod_dpto\"")."' order by label";
		$rsConsulta 		= pg_query( $linkPG , $consulta);
		$numRowsAeropuertos = pg_num_rows($rsConsulta);
		$i=0;
		while ($i<$numRowsAeropuertos) {
			$j=$i+1;
			if ($i%2) {
				$classe = "class='rowpar'";
			} else {
				$classe = "";
			}
			if (isset($_GET['excel']) && ($_GET['excel']=='excel')) {
				$enlace=$j;
			} else {
				$enlace='<a href="consulta_puertos.phtml?ovalor='.pg_fetch_result($rsConsulta,$i,"\"gid\"").'">'.$j.'</a>';
			}
			echo('<tr '.$classe.'><td align="center" class="texto11">'.$enlace.'</td>
					  <td class="texto11">'.pg_fetch_result($rsConsulta,$i,"\"label\"").'</td>');
					  
			$i++;
		}
	?> -->
				<!-- </table> -->
			<!-- </td></tr>
		</table><br> -->
		<table class='fuente_general' width="100%"><thead><tr><th><b>Fuente:</b>
			<br><?php echo(pg_fetch_result($rsDet,0,"\"fuente\"")); ?>
		</th></tr></thead></table>
	<?php
	$name=strtoupper(pg_fetch_result($rsDet,0,"\"label\""));
	$capa='consulta_puertos';
	if (!isset($_GET['excel'])) {
		$ruta=$capa.'.phtml?excel=excel&capa='.$capa.'&ovalor='.$pvalor;
		include 'inc/consulta_pie.php';
	}
	if (isset($_SESSION['usuario'])) {
		grabar_log_accesos('ingreso', $cod_user, $name, $descripcion);
	}
	?>
		</td></tr>
	</table>
	</td></tr>
</table>
</body>
</html>
<?php include_once("./analyticstracking.php");?>
