<?php

if (isset($_GET['excel']) && ($_GET['excel']=='excel')) {
	header("Content-type:application/x-msexcel");
	$file=$_GET['capa'];
	header("Content-Disposition: attachment; filename=".$file.".xls");
	$imgtitulo='';
} else {
	$imgtitulo='<img src="imajes/desplegable.png" width="11" height="11">';
}

/*@session_start();
	if(empty($_SESSION['usuario'])){
        header('Location: ../index.php');
	}else{$cod_user = $_SESSION['usuario'];}*/
	include ('conexion_postgres.phtml');
	include ('injection/funciones.php');
	$player = 	limpiarCadena($_GET['olayer']);
	$pcampo = 	limpiarCadena($_GET['ocampo']);
	$gid = limpiarNumeros($_GET['ovalor']);
	
	$linkPG = Conectarse_POSTGRES(); 
	// Browse Data
	$sQueryS = " SELECT *  ";   
	$sQueryF = " FROM peru_telef_movil_nuevo";
	$sQueryW = " WHERE gid = '" . $gid. "'";
	$sQuery = $sQueryS . $sQueryF . $sQueryW;
	$rsDet = pg_query( $linkPG , $sQuery );
	$titulo_ventana = 'COBERTURA DE TELEFONIA M&Oacute;VIL';
	$titulo = $titulo_ventana;
	
	
	include ('inc/consulta_cabecera.php');
?>
<table width="100%" border="0" cellspacing="0" cellpadding="10">
  <tr><td>
	<table width="100%" class="marco_general">
	  <tr><td>
		<table width="100%" class="marco_individual">
		  <tr>
			<td>
			<table width="100%" class="titulo_general">
			  <tr>
				<td>&nbsp;&nbsp;UBICACI&Oacute;N GEOGR&Aacute;FICA</td>
			  </tr>
			</table>
			<table width='100%' align='center' class='general'>
				<thead>
				  <tr>
					<th width='25%'>Departamento</th>
					<th width='25%'>Provincia</th>
					<th width='25%'>Distrito</th>
					<th width='25%'>Ubigeo</th>
				  </tr>
				</thead>
				<tbody>
<?php
		print "<tr>
				<td align='center' class='texto'>".pg_fetch_result($rsDet,0,"\"nom_dpto\"")."</td>
				<td align='center' class='texto'>".pg_fetch_result($rsDet,0,"\"nom_prov\"")."</td>
				<td align='center' class='texto'>".pg_fetch_result($rsDet,0,"\"nom_dist\"")."</td>
				<td align='center' class='texto'>".pg_fetch_result($rsDet,0,"\"cod_dist\"")."</td>
			  </tr>";
?>
				</tbody>
			</table>
			</td>
		  </tr>
		</table>
		<br>
		<table width="100%" class="marco_individual">
		  <tr>
			<td>
			<table width="100%" class="titulo_general">
			  <tr>
				<td>&nbsp;&nbsp;DATOS DE COBERTURA MOVIL DEL CCPP</td>
			  </tr>
			   <tr>
				<td align='center' >&nbsp;&nbsp;TELEFONIA DEL PER&Uacute; S.A.A - MOVISTAR</td>
			  </tr>
			</table>
			<table align='center' width="100%" class="listado" >
			
<?php

//EMPRESA MOVISTAR
		print "<tr>";
		print "<td width='40%' class='lista_titulo' colspan='3' ><b >Tiene cobertura MOVISTAR</b></td>";
		print "<td class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"movistar\"")."</td>";
		print "</tr>";
		

		// 2G INICIO
		print "<tr>";
		print "<td width='40%' class='lista_titulo' colspan='2' rowspan='3' ><b >2G</b></td>";
		print "<td width='40%' class='lista_titulo'><b >GSM_MOV</b></td>";
		print "<td class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"gsm_mov\"")."</td>";
		print "</tr>";

		print "<tr>";
		print "<td width='40%' class='lista_titulo'><b >CDMA_MOV</b></td>";
		print "<td class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"cdma_mov\"")."</td>";
		print "</tr>";

		print "<tr>";
		print "<td width='40%' class='lista_titulo'><b >IDEN_MOV</b></td>";
		print "<td class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"iden_mov\"")."</td>";
		print "</tr>";
		// 2G FIN

		// 2.5G INICIO
		print "<tr>";
		print "<td width='40%' class='lista_titulo' colspan='2' rowspan='2' ><b >2.5G</b></td>";
		print "<td width='40%' class='lista_titulo'><b >GPRS_MOV</b></td>";
		print "<td class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"gprs_mov\"")."</td>";
		print "</tr>";

		print "<tr>";
		print "<td width='40%' class='lista_titulo'><b >EDGE_MOV</b></td>";
		print "<td class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"edge_mov\"")."</td>";
		print "</tr>";
		// 2.5G FIN

		// 3G INICIO
		print "<tr>";
		print "<td width='40%' class='lista_titulo' colspan='2' rowspan='1' ><b >3G</b></td>";
		print "<td width='40%' class='lista_titulo'><b >UMTS_MOV</b></td>";
		print "<td class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"umts_mov\"")."</td>";
		print "</tr>";
		// 3G FIN

		// 3.5G INICIO
		print "<tr>";
		print "<td width='40%' class='lista_titulo' colspan='2' rowspan='3' ><b >3.5G</b></td>";
		print "<td width='40%' class='lista_titulo'><b >HSDPA_MOV</b></td>";
		print "<td class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"hsdpa_mov\"")."</td>";
		print "</tr>";

		print "<tr>";
		print "<td width='40%' class='lista_titulo'><b >HSUPA_MOV</b></td>";
		print "<td class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"hsupa_mov\"")."</td>";
		print "</tr>";

		print "<tr>";
		print "<td width='40%' class='lista_titulo'><b >HSPA__MOV</b></td>";
		print "<td class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"hspa__mov\"")."</td>";
		print "</tr>";
		// 3.5G FIN

		// 4G INICIO
		print "<tr>";
		print "<td width='40%' class='lista_titulo' colspan='2' rowspan='2' ><b >4G</b></td>";
		print "<td width='40%' class='lista_titulo'><b >LTE_MOV</b></td>";
		print "<td class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"lte_mov\"")."</td>";
		print "</tr>";

		print "<tr>";
		print "<td width='40%' class='lista_titulo'><b >WIMAX_MOV</b></td>";
		print "<td class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"wimax_mov\"")."</td>";
		print "</tr>";
		// 4G FIN

		// 5G INICIO
		print "<tr>";
		print "<td width='40%' class='lista_titulo' colspan='2' rowspan='2' ><b >5G</b></td>";
		print "<td width='40%' class='lista_titulo'><b >N5G_MOV</b></td>";
		print "<td class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"n5g_mov\"")."</td>";
		print "</tr>";
		// 5G FIN
	
	?>
			</table>
			</br>
			</br>
			<table width="100%" class="titulo_general">
			   <tr>
				<td align='center'>&nbsp;&nbsp;AM&EacuteRICA M&OacuteVIL S.A.A - CLARO</td>
			  </tr>
			</table>
						<table width="100%" class="listado">
<?php	
//EMPRESA CLARO
		print "<tr>";
		print "<td width='40%' class='lista_titulo' colspan='3' ><b >Tiene cobertura CLARO</b></td>";
		print "<td class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"claro\"")."</td>";
		print "</tr>";
		

		// 2G INICIO
		print "<tr>";
		print "<td width='40%' class='lista_titulo' colspan='2' rowspan='3' ><b >2G</b></td>";
		print "<td width='40%' class='lista_titulo'><b >GSM_CLA</b></td>";
		print "<td class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"gsm_cla\"")."</td>";
		print "</tr>";

		print "<tr>";
		print "<td width='40%' class='lista_titulo'><b >CDMA_CLA</b></td>";
		print "<td class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"cdma_cla\"")."</td>";
		print "</tr>";

		print "<tr>";
		print "<td width='40%' class='lista_titulo'><b >IDEN_CLA</b></td>";
		print "<td class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"iden_cla\"")."</td>";
		print "</tr>";
		// 2G FIN

		// 2.5G INICIO
		print "<tr>";
		print "<td width='40%' class='lista_titulo' colspan='2' rowspan='2' ><b >2.5G</b></td>";
		print "<td width='40%' class='lista_titulo'><b >GPRS_CLA</b></td>";
		print "<td class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"gprs_cla\"")."</td>";
		print "</tr>";

		print "<tr>";
		print "<td width='40%' class='lista_titulo'><b >EDGE_CLA</b></td>";
		print "<td class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"edge_cla\"")."</td>";
		print "</tr>";
		// 2.5G FIN

		// 3G INICIO
		print "<tr>";
		print "<td width='40%' class='lista_titulo' colspan='2' rowspan='1' ><b >3G</b></td>";
		print "<td width='40%' class='lista_titulo'><b >UMTS_CLA</b></td>";
		print "<td class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"umts_cla\"")."</td>";
		print "</tr>";
		// 3G FIN

		// 3.5G INICIO
		print "<tr>";
		print "<td width='40%' class='lista_titulo' colspan='2' rowspan='3' ><b >3.5G</b></td>";
		print "<td width='40%' class='lista_titulo'><b >HSDPA_CLA</b></td>";
		print "<td class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"hsdpa_cla\"")."</td>";
		print "</tr>";

		print "<tr>";
		print "<td width='40%' class='lista_titulo'><b >HSUPA_CLA</b></td>";
		print "<td class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"hsupa_mov\"")."</td>";
		print "</tr>";

		print "<tr>";
		print "<td width='40%' class='lista_titulo'><b >HSPA__CLA</b></td>";
		print "<td class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"hspa__cla\"")."</td>";
		print "</tr>";
		// 3.5G FIN

		// 4G INICIO
		print "<tr>";
		print "<td width='40%' class='lista_titulo' colspan='2' rowspan='2' ><b >4G</b></td>";
		print "<td width='40%' class='lista_titulo'><b >LTE_CLA</b></td>";
		print "<td class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"lte_cla\"")."</td>";
		print "</tr>";

		print "<tr>";
		print "<td width='40%' class='lista_titulo'><b >WIMAX_CLA</b></td>";
		print "<td class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"wimax_cla\"")."</td>";
		print "</tr>";
		// 4G FIN

		// 5G INICIO
		print "<tr>";
		print "<td width='40%' class='lista_titulo' colspan='2' rowspan='2' ><b >5G</b></td>";
		print "<td width='40%' class='lista_titulo'><b >N5G_CLA</b></td>";
		print "<td class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"n5g_cla\"")."</td>";
		print "</tr>";
		// 5G FIN
		
	
	?>
			</table>
			
		</br>
			</br>
			<table width="100%" class="titulo_general">
			   <tr>
				<td align='center'>&nbsp;&nbsp;ENTEL PER&Uacute; S.A - ENTEL</td>
			  </tr>
			</table>
						<table width="100%" class="listado">
<?php
		//EMPRESA ENTEL
		print "<tr>";
		print "<td width='40%' class='lista_titulo' colspan='3' ><b >Tiene cobertura ENTEL</b></td>";
		print "<td class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"entel\"")."</td>";
		print "</tr>";


		// 2G INICIO
		print "<tr>";
		print "<td width='40%' class='lista_titulo' colspan='2' rowspan='3' ><b >2G</b></td>";
		print "<td width='40%' class='lista_titulo'><b >GSM_ENT</b></td>";
		print "<td class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"gsm_ent\"")."</td>";
		print "</tr>";

		print "<tr>";
		print "<td width='40%' class='lista_titulo'><b >CDMA_ENT</b></td>";
		print "<td class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"cdma_ent\"")."</td>";
		print "</tr>";

		print "<tr>";
		print "<td width='40%' class='lista_titulo'><b >IDEN_ENT</b></td>";
		print "<td class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"iden_ent\"")."</td>";
		print "</tr>";
		// 2G FIN

		// 2.5G INICIO
		print "<tr>";
		print "<td width='40%' class='lista_titulo' colspan='2' rowspan='2' ><b >2.5G</b></td>";
		print "<td width='40%' class='lista_titulo'><b >GPRS_ENT</b></td>";
		print "<td class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"gprs_ent\"")."</td>";
		print "</tr>";

		print "<tr>";
		print "<td width='40%' class='lista_titulo'><b >EDGE_ENT</b></td>";
		print "<td class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"edge_ent\"")."</td>";
		print "</tr>";
		// 2.5G FIN

		// 3G INICIO
		print "<tr>";
		print "<td width='40%' class='lista_titulo' colspan='2' rowspan='1' ><b >3G</b></td>";
		print "<td width='40%' class='lista_titulo'><b >UMTS_ENT</b></td>";
		print "<td class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"umts_ent\"")."</td>";
		print "</tr>";
		// 3G FIN

		// 3.5G INICIO
		print "<tr>";
		print "<td width='40%' class='lista_titulo' colspan='2' rowspan='3' ><b >3.5G</b></td>";
		print "<td width='40%' class='lista_titulo'><b >HSDPA_ENT</b></td>";
		print "<td class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"hsdpa_ent\"")."</td>";
		print "</tr>";

		print "<tr>";
		print "<td width='40%' class='lista_titulo'><b >HSUPA_ENT</b></td>";
		print "<td class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"hsupa_ent\"")."</td>";
		print "</tr>";

		print "<tr>";
		print "<td width='40%' class='lista_titulo'><b >HSPA__ENT</b></td>";
		print "<td class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"hspa__ent\"")."</td>";
		print "</tr>";
		// 3.5G FIN

		// 4G INICIO
		print "<tr>";
		print "<td width='40%' class='lista_titulo' colspan='2' rowspan='2' ><b >4G</b></td>";
		print "<td width='40%' class='lista_titulo'><b >LTE_ENT</b></td>";
		print "<td class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"lte_ent\"")."</td>";
		print "</tr>";

		print "<tr>";
		print "<td width='40%' class='lista_titulo'><b >WIMAX_ENT</b></td>";
		print "<td class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"wimax_ent\"")."</td>";
		print "</tr>";
		// 4G FIN

		// 5G INICIO
		print "<tr>";
		print "<td width='40%' class='lista_titulo' colspan='2' rowspan='2' ><b >5G</b></td>";
		print "<td width='40%' class='lista_titulo'><b >N5G_ENT</b></td>";
		print "<td class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"n5g_ent\"")."</td>";
		print "</tr>";
		// 5G FIN
	
	?>
			</table>
			
			</br>
			</br>
			<table width="100%" class="titulo_general">
			   <tr>
				<td align='center'>&nbsp;&nbsp;VIETTEL DEL PER&Uacute; S.A.C. - BITEL</td>
			  </tr>
			</table>
						<table width="100%" class="listado">
<?php

		//EMPRESA BITEL
		print "<tr>";
		print "<td width='40%' class='lista_titulo' colspan='3' ><b >Tiene cobertura BITEL</b></td>";
		print "<td class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"bitel\"")."</td>";
		print "</tr>";


		// 2G INICIO
		print "<tr>";
		print "<td width='40%' class='lista_titulo' colspan='2' rowspan='3' ><b >2G</b></td>";
		print "<td width='40%' class='lista_titulo'><b >GSM_BIT</b></td>";
		print "<td class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"gsm_bit\"")."</td>";
		print "</tr>";

		print "<tr>";
		print "<td width='40%' class='lista_titulo'><b >CDMA_BIT</b></td>";
		print "<td class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"cdma_bit\"")."</td>";
		print "</tr>";

		print "<tr>";
		print "<td width='40%' class='lista_titulo'><b >IDEN_BIT</b></td>";
		print "<td class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"iden_bit\"")."</td>";
		print "</tr>";
		// 2G FIN

		// 2.5G INICIO
		print "<tr>";
		print "<td width='40%' class='lista_titulo' colspan='2' rowspan='2' ><b >2.5G</b></td>";
		print "<td width='40%' class='lista_titulo'><b >GPRS_BIT</b></td>";
		print "<td class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"gprs_bit\"")."</td>";
		print "</tr>";

		print "<tr>";
		print "<td width='40%' class='lista_titulo'><b >EDGE_BIT</b></td>";
		print "<td class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"edge_bit\"")."</td>";
		print "</tr>";
		// 2.5G FIN

		// 3G INICIO
		print "<tr>";
		print "<td width='40%' class='lista_titulo' colspan='2' rowspan='1' ><b >3G</b></td>";
		print "<td width='40%' class='lista_titulo'><b >UMTS_BIT</b></td>";
		print "<td class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"umts_bit\"")."</td>";
		print "</tr>";
		// 3G FIN

		// 3.5G INICIO
		print "<tr>";
		print "<td width='40%' class='lista_titulo' colspan='2' rowspan='3' ><b >3.5G</b></td>";
		print "<td width='40%' class='lista_titulo'><b >HSDPA_BIT</b></td>";
		print "<td class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"hsdpa_bit\"")."</td>";
		print "</tr>";

		print "<tr>";
		print "<td width='40%' class='lista_titulo'><b >HSUPA_BIT</b></td>";
		print "<td class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"hsupa_bit\"")."</td>";
		print "</tr>";

		print "<tr>";
		print "<td width='40%' class='lista_titulo'><b >HSPA__BIT</b></td>";
		print "<td class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"hspa__bit\"")."</td>";
		print "</tr>";
		// 3.5G FIN

		// 4G INICIO
		print "<tr>";
		print "<td width='40%' class='lista_titulo' colspan='2' rowspan='2' ><b >4G</b></td>";
		print "<td width='40%' class='lista_titulo'><b >LTE_BIT</b></td>";
		print "<td class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"lte_bit\"")."</td>";
		print "</tr>";

		print "<tr>";
		print "<td width='40%' class='lista_titulo'><b >WIMAX_BIT</b></td>";
		print "<td class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"wimax_bit\"")."</td>";
		print "</tr>";
		// 4G FIN

		// 5G INICIO
		print "<tr>";
		print "<td width='40%' class='lista_titulo' colspan='2' rowspan='2' ><b >5G</b></td>";
		print "<td width='40%' class='lista_titulo'><b >N5G_BIT</b></td>";
		print "<td class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"n5g_bit\"")."</td>";
		print "</tr>";
		// 5G FIN
	
	?>
			</table>
			</td>
		  </tr>
		</table>
		<br>
		<table class='fuente_general' width="100%"><thead><tr><th><b>Fuente:</b>
			<br><?php echo(pg_fetch_result($rsDet,0,"\"fuente\"")); ?>
		</th></tr></thead></table>
	<?php
	$name='Internet';
	$capa='peru_telef_movil_nuevo';
	if (!isset($_GET['excel'])) {
		$ruta='consulta_telefonia_movil.phtml?excel=excel&capa='.$capa.'&ovalor='.$gid;
		include 'inc/consulta_pie.php';
	}
	if (isset($_SESSION['usuario'])) {
		grabar_log_accesos('ingreso', $cod_user, $name, $descripcion);
	}
	?>
</td></tr>
	</table>
	</td></tr>
</table>
</body>

</html>


<?php include_once("./analyticstracking.php");?>
