
<?php

if (isset($_GET['excel']) && ($_GET['excel']=='excel')){
	header("Content-type:application/x-msexcel");
	$file=$_GET['capa'];
	header("Content-Disposition: attachment; filename=".$file.".xls");
	$imgtitulo='';
} else{
	$imgtitulo='<img src="imajes/desplegable.png" width="11" height="11">';
}

/*@session_start();
	if(empty($_SESSION['usuario'])){
        header('Location: ../index.php');
	}else{$cod_user = $_SESSION['usuario'];}*/
	include ('conexion_postgres.phtml');
	include ('injection/funciones.php');
	$player = 	limpiarCadena($_GET['olayer']);
	$pcampo = 	limpiarCadena($_GET['ocampo']);
	$pvalor = limpiarCadena(limpiarNumeros($_GET['ovalor']));
	$linkPG = Conectarse_POSTGRES();
	// Browse Data
	$sQueryS = "SELECT *";
	$sQueryF = " FROM vw_peru_seguciu_adolesinfra_servicio_orient_adoles";
	$sQueryW = " WHERE gid = '" . $pvalor . "'";

	$sQuery = $sQueryS . $sQueryF . $sQueryW;
	$rsDet = pg_query( $linkPG , $sQuery );
	$titulo_ventana = 'SERVICIO DE ORIENTACIÓN AL ADOLESCENTE (SOA)';
	$titulo = 'SERVICIO DE ORIENTACIÓN AL ADOLESCENTE (SOA)';
	include ('inc/consulta_cabecera.php');
?>
<table width="100%" border="0" cellspacing="0" cellpadding="10">
  <tr><td>
	<table width="100%" class="marco_general">
	  <tr><td>
		<table width="100%" class="marco_individual">
		  <!--tr>
			<td>
				<table width="100%" class="titulo_general">
				  <tr>
					<td>&nbsp;&nbsp;UBICACI&Oacute;N GEOGR&Aacute;FICA</td>
				  </tr>
				</table>
				<table width='100%' align='center' class='general'>
					<thead>
					  <tr>
						<th width='25%'>Departamento</th>
						<th width='25%'>Provincia</th>
						<th width='25%'>Distrito</th>
						<th width='25%'>Codigo Distrito</th>
					  </tr>
					</thead>
					<tbody>
					<tr>
						<td align='center' class='texto'><?php echo(pg_fetch_result($rsDet,0,"\"nom_dpto\"")) ?></td>
						<td align='center' class='texto'><?php echo(pg_fetch_result($rsDet,0,"\"nom_prov\"")) ?></td>
						<td align='center' class='texto'><?php echo(pg_fetch_result($rsDet,0,"\"nom_dist\"")) ?></td>
						<td align='center' class='texto'><?php echo(pg_fetch_result($rsDet,0,"\"cod_dist\"")) ?></td>
					</tr>
	
					</tbody>
				</table>
			</td>
		  </tr-->
		</table>
		<br>
		<table width="100%" class="marco_individual">
		  <tr>
			<td>
				<table width="100%" class="titulo_general">
					  <tr>
						<td>&nbsp;&nbsp;POBLACIÓN TOTAL POR GÉNERO</td>
					  </tr>
					  
				</table>

				<table width='100%' align='center' class='general'>
		<?php
        print "
        		<tr>
				<td width='50%' class='lista_titulo'>N° de adolescentes infractores de género femenino</td>
				<td width='50%' class='texto1'>".pg_fetch_result($rsDet,0,"\"femenino\"")."</td>
				</tr>

				<tr>
				<td width='50%' class='lista_titulo'>N° de adolescentes infractores de género masculino</td>
				<td width='50%' class='texto1'>".pg_fetch_result($rsDet,0,"\"masculino\"")."</td>
			  	</tr>

			";
		?>
			</table>

				<table width="100%" class="titulo_general">
					  <tr>
						<td>&nbsp;&nbsp;POBLACIÓN TOTAL POR RANGO DE EDAD</td>
					  </tr>
				</table>
			<table width='100%' align='center' class='general'>
		<?php
        print "
        		<tr>
				<td width='50%' class='lista_titulo'>N° de adolescentes infractores de 14 años</td>
				<td width='50%' class='texto1'>".pg_fetch_result($rsDet,0,"\"edad_14\"")."</td>
				</tr>
				
        		<tr>
				<td width='50%' class='lista_titulo'>N° de adolescentes infractores de 15 años</td>
				<td width='50%' class='texto1'>".pg_fetch_result($rsDet,0,"\"edad_15\"")."</td>
				</tr>
				
        		<tr>
				<td width='50%' class='lista_titulo'>N° de adolescentes infractores de 16 años</td>
				<td width='50%' class='texto1'>".pg_fetch_result($rsDet,0,"\"edad_16\"")."</td>
				</tr>
				
        		<tr>
				<td width='50%' class='lista_titulo'>N° de adolescentes infractores de 17 años</td>
				<td width='50%' class='texto1'>".pg_fetch_result($rsDet,0,"\"edad_17\"")."</td>
				</tr>
				
        		<tr>
				<td width='50%' class='lista_titulo'>N° de adolescentes infractores de 18 años</td>
				<td width='50%' class='texto1'>".pg_fetch_result($rsDet,0,"\"edad_18\"")."</td>
				</tr>
				
        		<tr>
				<td width='50%' class='lista_titulo'>N° de adolescentes infractores de 19 años</td>
				<td width='50%' class='texto1'>".pg_fetch_result($rsDet,0,"\"edad_19\"")."</td>
				</tr>
				
        		<tr>
				<td width='50%' class='lista_titulo'>N° de adolescentes infractores de 20 años</td>
				<td width='50%' class='texto1'>".pg_fetch_result($rsDet,0,"\"edad_20\"")."</td>
				</tr>
				
        		<tr>
				<td width='50%' class='lista_titulo'>N° de adolescentes infractores de 21 años</td>
				<td width='50%' class='texto1'>".pg_fetch_result($rsDet,0,"\"edad_21\"")."</td>
				</tr>
				
        		<tr>
				<td width='50%' class='lista_titulo'>N° de adolescentes infractores de 22 años</td>
				<td width='50%' class='texto1'>".pg_fetch_result($rsDet,0,"\"edad_22\"")."</td>
				</tr>
				
        		<tr>
				<td width='50%' class='lista_titulo'>N° de adolescentes infractores de 23 años</td>
				<td width='50%' class='texto1'>".pg_fetch_result($rsDet,0,"\"edad_23\"")."</td>
				</tr>
				
        		<tr>
				<td width='50%' class='lista_titulo'>N° de adolescentes infractores de 24 años</td>
				<td width='50%' class='texto1'>".pg_fetch_result($rsDet,0,"\"edad_24\"")."</td>
				</tr>
				
        		<tr>
				<td width='50%' class='lista_titulo'>N° de adolescentes infractores de 25 años</td>
				<td width='50%' class='texto1'>".pg_fetch_result($rsDet,0,"\"edad_25\"")."</td>
				</tr>		

			";
		?>
			</table>

			<table width="100%" class="marco_individual">
		  <tr>
			<td>
				<table width="100%" class="titulo_general">
					  <tr>
						<td>&nbsp;&nbsp;POBLACIÓN TOTAL POR SITUACIÓN JURÍDICA</td>
					  </tr>
					  
				</table>

				<table width='100%' align='center' class='general'>
		<?php
        print "
        		<tr>
				<td width='50%' class='lista_titulo'>N° de adolescentes infractores procesados</td>
				<td width='50%' class='texto1'>".pg_fetch_result($rsDet,0,"\"procesado\"")."</td>
				</tr>

				<tr>
				<td width='50%' class='lista_titulo'>N° de adolescentes infractores sentenciados</td>
				<td width='50%' class='texto1'>".pg_fetch_result($rsDet,0,"\"sentenc\"")."</td>
			  	</tr>

			";
		?>
			</table>

			
			<table width="100%" class="marco_individual">
		  <tr>
			<td>
				<table width="100%" class="titulo_general">
					  <tr>
						<td>&nbsp;&nbsp;POBLACIÓN TOTAL POR DELITO GENÉRICO</td>
					  </tr>
					  
				</table>

				<table width='100%' align='center' class='general'>
		<?php
        print "
        		<tr>
				<td width='50%' class='lista_titulo'>N° de adolescentes infractores por delito contra el orden financiero y monetario</td>
				<td width='50%' class='texto1'>".pg_fetch_result($rsDet,0,"\"cont_or_fi\"")."</td>
				</tr>

        		<tr>
				<td width='50%' class='lista_titulo'>N° de adolescentes infractores por delito contra el patrimonio</td>
				<td width='50%' class='texto1'>".pg_fetch_result($rsDet,0,"\"cont_patr\"")."</td>
				</tr>

        		<tr>
				<td width='50%' class='lista_titulo'>N° de adolescentes infractores por delito contra la administración pública</td>
				<td width='50%' class='texto1'>".pg_fetch_result($rsDet,0,"\"cont_ad_pu\"")."</td>
				</tr>

        		<tr>
				<td width='50%' class='lista_titulo'>N° de adolescentes infractores por delito contra la familia</td>
				<td width='50%' class='texto1'>".pg_fetch_result($rsDet,0,"\"cont_fam\"")."</td>
				</tr>

        		<tr>
				<td width='50%' class='lista_titulo'>N° de adolescentes infractores por delito contra la fe pública</td>
				<td width='50%' class='texto1'>".pg_fetch_result($rsDet,0,"\"cont_fe_pu\"")."</td>
				</tr>

        		<tr>
				<td width='50%' class='lista_titulo'>N° de adolescentes infractores por delito contra la libertad</td>
				<td width='50%' class='texto1'>".pg_fetch_result($rsDet,0,"\"cont_lib\"")."</td>
				</tr>

        		<tr>
				<td width='50%' class='lista_titulo'>N° de adolescentes infractores por delito contra la libertad personal</td>
				<td width='50%' class='texto1'>".pg_fetch_result($rsDet,0,"\"cont_li_pe\"")."</td>
				</tr>

        		<tr>
				<td width='50%' class='lista_titulo'>N° de adolescentes infractores por delito contra la libertad sexual</td>
				<td width='50%' class='texto1'>".pg_fetch_result($rsDet,0,"\"cont_li_se\"")."</td>
				</tr>

        		<tr>
				<td width='50%' class='lista_titulo'>N° de adolescentes infractores por delito contra la salud pública</td>
				<td width='50%' class='texto1'>".pg_fetch_result($rsDet,0,"\"cont_sa_pu\"")."</td>
				</tr>

        		<tr>
				<td width='50%' class='lista_titulo'>N° de adolescentes infractores por delito contra la seguridad pública</td>
				<td width='50%' class='texto1'>".pg_fetch_result($rsDet,0,"\"cont_se_pu\"")."</td>
				</tr>

        		<tr>
				<td width='50%' class='lista_titulo'>N° de adolescentes infractores por delito contra la tranquilidad pública</td>
				<td width='50%' class='texto1'>".pg_fetch_result($rsDet,0,"\"cont_tr_pu\"")."</td>
				</tr>

        		<tr>
				<td width='50%' class='lista_titulo'>N° de adolescentes infractores por delito contra la vida, el cuerpo y la salud</td>
				<td width='50%' class='texto1'>".pg_fetch_result($rsDet,0,"\"cont_v_c_s\"")."</td>
				</tr>

        		<tr>
				<td width='50%' class='lista_titulo'>N° de adolescentes infractores por otros tipos de delitos</td>
				<td width='50%' class='texto1'>".pg_fetch_result($rsDet,0,"\"otros\"")."</td>
				</tr>
				
			";
		?>
			</table>

			<table width="100%" class="marco_individual">
		  <tr>
			<td>
				<table width="100%" class="titulo_general">
					  <tr>
						<td>&nbsp;&nbsp;POBLACIÓN TOTAL POR FRECUENCIA DE INGRESO</td>
					  </tr>
					  
				</table>

				<table width='100%' align='center' class='general'>
		<?php
        print "
        		<tr>
				<td width='50%' class='lista_titulo'>N° de adolescentes infractores con primer Internamiento</td>
				<td width='50%' class='texto1'>".pg_fetch_result($rsDet,0,"\"prim_inter\"")."</td>
				</tr>

				<tr>
				<td width='50%' class='lista_titulo'>N° de adolescentes infractores con segundo Internamiento</td>
				<td width='50%' class='texto1'>".pg_fetch_result($rsDet,0,"\"seg_inter\"")."</td>
			  	</tr>

        		<tr>
				<td width='50%' class='lista_titulo'>N° de adolescentes infractores con tercer Internamiento</td>
				<td width='50%' class='texto1'>".pg_fetch_result($rsDet,0,"\"ter_inter\"")."</td>
				</tr>

				<tr>
				<td width='50%' class='lista_titulo'>N° de adolescentes infractores con cambio de medida</td>
				<td width='50%' class='texto1'>".pg_fetch_result($rsDet,0,"\"camb_med\"")."</td>
			  	</tr>

			";
		?>
			</table>

			<table width="100%" class="marco_individual">
		  <tr>
			<td>
				<table width="100%" class="titulo_general">
					  <tr>
						<td>&nbsp;&nbsp;TIPO DE SEGURO MÉDICO</td>
					  </tr>
					  
				</table>

				<table width='100%' align='center' class='general'>
		<?php
        print "
        		<tr>
				<td width='50%' class='lista_titulo'>N° de adolescentes infractores con ESSALUD</td>
				<td width='50%' class='texto1'>".pg_fetch_result($rsDet,0,"\"essalud\"")."</td>
				</tr>

				<tr>
				<td width='50%' class='lista_titulo'>N° de adolescentes infractores con SIS</td>
				<td width='50%' class='texto1'>".pg_fetch_result($rsDet,0,"\"sis\"")."</td>
			  	</tr>

        		<tr>
				<td width='50%' class='lista_titulo'>N° de adolescentes infractores con seguro particular</td>
				<td width='50%' class='texto1'>".pg_fetch_result($rsDet,0,"\"particular\"")."</td>
				</tr>

				<tr>
				<td width='50%' class='lista_titulo'>N° de adolescentes infractores sin seguro médico</td>
				<td width='50%' class='texto1'>".pg_fetch_result($rsDet,0,"\"ninguno\"")."</td>
			  	</tr>

			";
		?>
			</table>

			<table width="100%" class="marco_individual">
		  <tr>
			<td>
				<table width="100%" class="titulo_general">
					  <tr>
						<td>&nbsp;&nbsp;GRADO DE INSTRUCCIÓN ACTUAL</td>
					  </tr>
					  
				</table>

				<table width='100%' align='center' class='general'>
		<?php
        print "
        		<tr>
				<td width='50%' class='lista_titulo'>N° de adolescentes infractores con 1° Secundaria</td>
				<td width='50%' class='texto1'>".pg_fetch_result($rsDet,0,"\"prim_sec\"")."</td>
				</tr>

        		<tr>
				<td width='50%' class='lista_titulo'>N° de adolescentes infractores con 2° Secundaria</td>
				<td width='50%' class='texto1'>".pg_fetch_result($rsDet,0,"\"seg_sec\"")."</td>
				</tr>

        		<tr>
				<td width='50%' class='lista_titulo'>N° de adolescentes infractores con 3° Secundaria</td>
				<td width='50%' class='texto1'>".pg_fetch_result($rsDet,0,"\"ter_sec\"")."</td>
				</tr>

        		<tr>
				<td width='50%' class='lista_titulo'>N° de adolescentes infractores con 4° Secundaria</td>
				<td width='50%' class='texto1'>".pg_fetch_result($rsDet,0,"\"cua_sec\"")."</td>
				</tr>

        		<tr>
				<td width='50%' class='lista_titulo'>N° de adolescentes infractores con 5° Secundaria</td>
				<td width='50%' class='texto1'>".pg_fetch_result($rsDet,0,"\"qui_sec\"")."</td>
				</tr>

        		<tr>
				<td width='50%' class='lista_titulo'>N° de adolescentes infractores con Ceba Inicial</td>
				<td width='50%' class='texto1'>".pg_fetch_result($rsDet,0,"\"ceba_inic\"")."</td>
				</tr>

        		<tr>
				<td width='50%' class='lista_titulo'>N° de adolescentes infractores con Ceba Intermedio</td>
				<td width='50%' class='texto1'>".pg_fetch_result($rsDet,0,"\"ceba_inter\"")."</td>
				</tr>

				<tr>
				<td width='50%' class='lista_titulo'>N° de adolescentes infractores con Ceba Avanzado</td>
				<td width='50%' class='texto1'>".pg_fetch_result($rsDet,0,"\"ceba_avanz\"")."</td>
				</tr>

        		<tr>
				<td width='50%' class='lista_titulo'>N° de adolescentes infractores con Academia</td>
				<td width='50%' class='texto1'>".pg_fetch_result($rsDet,0,"\"academia\"")."</td>
				</tr>

        		<tr>
				<td width='50%' class='lista_titulo'>N° de adolescentes infractores con 1° - 2° Educación técnica</td>
				<td width='50%' class='texto1'>".pg_fetch_result($rsDet,0,"\"ed_tec_1_2\"")."</td>
				</tr>

        		<tr>
				<td width='50%' class='lista_titulo'>N° de adolescentes infractores con 3° - 4° Educación técnica</td>
				<td width='50%' class='texto1'>".pg_fetch_result($rsDet,0,"\"ed_tec_3_4\"")."</td>
				</tr>

        		<tr>
				<td width='50%' class='lista_titulo'>N° de adolescentes infractores con 5° - 6° Educación técnica</td>
				<td width='50%' class='texto1'>".pg_fetch_result($rsDet,0,"\"ed_tec_5_6\"")."</td>
				</tr>

        		<tr>
				<td width='50%' class='lista_titulo'>N° de adolescentes infractores con Educación ocupacional</td>
				<td width='50%' class='texto1'>".pg_fetch_result($rsDet,0,"\"educ_ocup\"")."</td>
				</tr>

        		<tr>
				<td width='50%' class='lista_titulo'>N° de adolescentes infractores con Estudios universitarios</td>
				<td width='50%' class='texto1'>".pg_fetch_result($rsDet,0,"\"est_univ\"")."</td>
				</tr>

        		<tr>
				<td width='50%' class='lista_titulo'>N° de adolescentes infractores sin ningún grado de instrucción</td>
				<td width='50%' class='texto1'>".pg_fetch_result($rsDet,0,"\"sin_gra\"")."</td>
				</tr>


			";
		?>
			</table>
			</td>
		  </tr>
		</table>
		<br>
		
		<table class='fuente_general' width="100%"><thead><tr><th><b>Fuente:</b>
			<br><?php echo pg_fetch_result($rsDet,0,"\"fuente\"");?></th></tr></thead>
		</table>
	<?php
	//$name=strtoupper(pg_fetch_result($rsDet,0,"\"tipoaerona\"").' - '.pg_fetch_result($rsDet,0,"\"label\""));
	$name='SERVICIO DE ORIENTACIÓN AL ADOLESCENTE (SOA)';
	$capa='SERVICIO DE ORIENTACIÓN AL ADOLESCENTE (SOA)';
	if (!isset($_GET['excel'])) {
		$ruta=$capa.'.phtml?excel=excel&capa='.$capa.'&ovalor='.$pvalor.'&olayer=peru_discapacidad_regiones'.'&ocampo=gid';
		include 'inc/consulta_pie.php';
	}
	if (isset($_SESSION['usuario'])) {
		grabar_log_accesos('ingreso', $cod_user, $name, $descripcion);
	}
	?>
		</td>
	  </tr>
	</table>
	</td>
  </tr>
</table>
</body>
</html>
<?php include_once("./analyticstracking.php");?>