<?php

if (isset($_GET['excel']) && ($_GET['excel']=='excel')) {
	header("Content-type:application/x-msexcel");
	$file=$_GET['capa'];
	header("Content-Disposition: attachment; filename=".$file.".xls");
	$imgtitulo='';
} else {
	$imgtitulo='<img src="imajes/desplegable.png" width="11" height="11">';
}

/*@session_start();
	if(empty($_SESSION['usuario'])){
        header('Location: ../index.php');
		}else{$cod_user = $_SESSION['usuario'];}*/
	include("conexion_postgres.phtml");
	include ('injection/funciones.php');
	$player = limpiarCadena($_GET['olayer']);
	$pcampo = limpiarCadena($_GET['ocampo']);
	$pvalor = limpiarNumeros($_GET['ovalor']);
	$linkPG = Conectarse_POSTGRES();

	// Browse Data
	$sQueryS = "SELECT * ";
	$sQueryF = " FROM peru_idh_2019";
	$sQueryW = " WHERE gid = '" . $pvalor . "'";

	$sQuery = $sQueryS . $sQueryF . $sQueryW;
	$rsDet = pg_query( $linkPG , $sQuery );

	
	
	$titulo_ventana = '&Iacute;NDICE DE DESARROLLO HUMANO (IDH) 2019 - Distrito '.pg_fetch_result($rsDet,0,"\"nom_dist\"");
	$titulo = '&Iacute;NDICE DE DESARROLLO HUMANO (IDH) 2019<br> Distrito - '.pg_fetch_result($rsDet,0,"\"nom_dist\"");
	
	
	
	include ('inc/consulta_cabecera.php');
?>
<table width="100%" border="0" cellspacing="0" cellpadding="10">
  <tr><td>
	<table width="100%" class="marco_general">
	  <tr><td>
		<table class="marco_individual">
		  <tr>
			<td>
				<div id="u1" style="width: 100%;">
					<h1><table width="100%" class="titulo_general">
						  <tr>
							<td><?php echo $imgtitulo;?>&nbsp;&nbsp;UBICACI&Oacute;N GEOGR&Aacute;FICA</td>
						  </tr>
						</table></h1>
					<div>
					<table width="100%" align='center' class="general">
					<thead>
					  <tr>
						<?php 
							print('<th width="25%">Departamento</th>');
							print('<th width="25%">Provincia</th>');
							print('<th width="25%">Distrito</th>');
							print('<th width="25%">Ubigeo</th>');
						?>
					  </tr>
					</thead>
					<tbody>
					  <tr>
					<?php 
						
						print('<td align="center" class="texto">'.pg_fetch_result($rsDet,0,"\"nom_dpto\"").'</td>');
						print('<td align="center" class="texto">'.pg_fetch_result($rsDet,0,"\"nom_prov\"").'</td>');
						print('<td align="center" class="texto">'.pg_fetch_result($rsDet,0,"\"nom_dist\"").'</td>');
						print('<td align="center" class="texto">'.pg_fetch_result($rsDet,0,"\"cod_dist\"").'</td>');
					?> 		  
					  </tr>
					</tbody>
					</table>
					</div>
				</div>
			</td>
		  </tr>
		</table>
		<br>
		<table width="100%" class="marco_individual">
		  <tr>
			<td>
				<div id="u2" style="width: 100%;">
					<h1><table width="100%" class="titulo_general">
						  <tr>
							<td><?php echo $imgtitulo;?>&nbsp;&nbsp;DATOS DEL MAPA &Iacute;ndice de desarrollo humano</td>
						  </tr>
						</table></h1>
					<div>
						<table width="100%" align="center" border="0" cellspacing="0" cellpadding="10">
						  <tr>
							<td valign="top" width="60%">
							<table width='100%' align='center' class='listado'>
		<?php
			
			print "<tr><td width='70%' class='lista_titulo'>Poblaci&oacute;n (habitantes)</td><td width='30%' class='numero'>" .number_format(pg_fetch_result($rsDet,0,"\"pob_hab\""),0)."</td></tr>";
			print "<tr><td class='lista_titulo'>Poblaci&oacute;n (Ranking)</td><td class='numero'>" .pg_fetch_result($rsDet,0,"\"pob_rank\""). "</td></tr>";
			print "<tr><td class='lista_titulo'>&Iacute;ndice de Desarrollo Humano (IDH) 2019</td><td class='numero'>" .number_format(pg_fetch_result($rsDet,0,"\"idh\""),4). "</td></tr>";
			print "<tr><td class='lista_titulo'>&Iacute;ndice de Desarrollo Humano (IDH) 2019 (Ranking)</td><td class='numero'>" .pg_fetch_result($rsDet,0,"\"idh_rank\""). "</td></tr>";
			print "<tr><td class='lista_titulo'>Esperanza de vida al nacer (a&ntilde;os)</td><td class='numero'>" .number_format(pg_fetch_result($rsDet,0,"\"evn_annos\""),2). "</td></tr>";
			print "<tr><td class='lista_titulo'>Esperanza de vida al nacer (Ranking)</td><td class='numero'>" .pg_fetch_result($rsDet,0,"\"evn_rank\""). "</td></tr>";

			print "<tr><td class='lista_titulo'>Población (18 años) con educación secundaria completa (%)</td><td class='numero'>" .number_format(pg_fetch_result($rsDet,0,"\"pes_co_por\""),2). "</td></tr>";
			print "<tr><td class='lista_titulo'>Población (18 años) con educación secundaria completa (Ranking)</td><td class='numero'>" .pg_fetch_result($rsDet,0,"\"pesco_rank\""). "</td></tr>";

			print "<tr><td class='lista_titulo'>Años de educación (Población de 25 años y más)</td><td class='numero'>" .number_format(pg_fetch_result($rsDet,0,"\"ae_annos\""),2). "</td></tr>";
			print "<tr><td class='lista_titulo'>Años de educación (Población de 25 años y más) (Ranking)</td><td class='numero'>" .pg_fetch_result($rsDet,0,"\"ae_rank\""). "</td></tr>";

			print "<tr><td class='lista_titulo'>Ingreso familiar per cápita (soles por mes)</td><td class='numero'>" .number_format(pg_fetch_result($rsDet,0,"\"ifp_ns_mes\""),2). "</td></tr>";
			print "<tr><td class='lista_titulo'>Ingreso familiar per cápita (Ranking)</td><td class='numero'>" .pg_fetch_result($rsDet,0,"\"ifp_rank\""). "</td></tr>";

			print "<tr><td class='lista_titulo'>Quintil de la estratificación IDH</td><td class='numero'>" .pg_fetch_result($rsDet,0,"\"quintil\""). "</td></tr>";
			
			print "</table>";
		?>
							</td>
						  </tr>
						</table>
					</div>
				</div>
			</td>
		  </tr>
		</table>
		
				<br>
		<table class='fuente_general' width="100%"><thead><tr><th><b>Fuente:</b>
			<br><?php echo pg_fetch_result($rsDet,0,"\"fuente\"");?></th></tr></thead>
		</table>
	<?php
	$name=$titulo_ventana;
	$capa='consulta_idh';
	if (!isset($_GET['excel'])) {
		$ruta=$capa.'.phtml?excel=excel&capa='.$capa.'&ovalor='.$pvalor;
		include 'inc/consulta_pie.php';
	}
	if (isset($_SESSION['usuario'])) {
		grabar_log_accesos('ingreso', $cod_user, $name, $descripcion);
	}
	?>
		</td></tr>
	</table>
	</td></tr>
</table>
</body>

<script language="javascript" type="text/javascript">
	$(document).ready(function(){
		$("#u1").h2c_acordeon();
		$("#u2").h2c_acordeon();
		$("#u3").h2c_acordeon();
		$("#u4").h2c_acordeon();
		$("#u5").h2c_acordeon();
	});
</script>

</html>
