<?php

if (isset($_GET['excel']) && ($_GET['excel']=='excel')) {
	header("Content-type:application/x-msexcel");
	$file=$_GET['capa'];
	header("Content-Disposition: attachment; filename=".$file.".xls");
	$imgtitulo='';
} else {
	$imgtitulo='<img src="imajes/desplegable.png" width="11" height="11">';
}
function valorsino($campo){
				if($campo=='1'){$valor='S&iacute;';}elseif($campo=='2'){$valor='No';}elseif($campo=='0'){$valor='Sin datos';}
				return $valor;
			}
/*@session_start();
	if(empty($_SESSION['usuario'])){
        header('Location: ../index.php');
		}else{$cod_user = $_SESSION['usuario'];}*/
	include ('conexion_postgres.phtml');
	include ('injection/funciones.php');
	$player = limpiarCadena($_GET['olayer']);
	$pcampo = limpiarCadena($_GET['ocampo']);
    $pvalor = limpiarNumeros($_GET['ovalor']);
	$linkPG = Conectarse_POSTGRES();
	// Browse Data
	$sQueryS = "SELECT *";
	//$sQueryF = " FROM unidades_min_produccion_mayo2022";
	$sQueryF = " FROM vw_peru_tumbes_mapa_de_peligros";
	$sQueryW = " WHERE \"gid\" = '" . $pvalor . "'";

	$sQuery = $sQueryS . $sQueryF . $sQueryW;
	$rsDet = pg_query( $linkPG , $sQuery );
	$titulo_ventana = 'MAPA DE PELIGROS';
	$titulo = $titulo_ventana;
	include ('inc/consulta_cabecera.php');
?>
<table width="100%" border="0" cellspacing="0" cellpadding="10">
  <tr><td>
	<table width="100%" class="marco_general">
	  <tr><td>
		<table width="100%" class="marco_individual">
		  <tr>
			<td>
			<table width="100%" class="titulo_general">
			  <tr>
				<td>&nbsp;&nbsp;UBICACI&Oacute;N GEOGR&Aacute;FICA</td>
			  </tr>
			</table>
			<table width='100%' align='center' class='general'>
				<thead>
				<?php print" <tr>
					<th width='20%'>DEPARTAMENTO</th>
					<th width='20%'>UBIGEO</th>
				  </tr>";?>
				</thead>
				<tbody>
	<?php
			print "<tr>
					<td align='center' class='texto'>".pg_fetch_result($rsDet,0,"\"nom_dpto\"")."</td>
					<td align='center' class='texto'>".pg_fetch_result($rsDet,0,"\"cod_dpto\"")."</td>
				  </tr>";
	?>
				</tbody>
			</table>
			</td>
		  </tr>
		</table>
		<br>
        <table width="100%" class="marco_individual">
		  <tr>
			<td>
			<table width="100%" class="titulo_general">
			  <tr>
				<td>&nbsp;&nbsp;DATOS MAPA DE PELIGROS</td>
			  </tr>
			</table>
			<table width="100%" class="listado">
	<?php
		print "<tr>
				<td width='50%' class='lista_titulo'>Nivel de peligro</td>
				<td align='' class='texto'>".pg_fetch_result($rsDet,0,"\"peligro\"")."</td>
			  </tr>
			  <tr>
				<td class='lista_titulo'>Región</td>
				<td align='' class='texto'>".pg_fetch_result($rsDet,0,"\"region\"")."</td>
			  </tr>
			  <tr>
				<td class='lista_titulo'>Descripción de litología</td>
				<td align='' class='texto'>".pg_fetch_result($rsDet,0,"\"lito_des\"")."</td>
              </tr>
              <tr>
                <td class='lista_titulo'>Símbolo Litología</td>
                <td class='texto'>".pg_fetch_result($rsDet,0,"\"simbolo_\"")."</td>
              </tr>
              <tr>
                <td class='lista_titulo'>Fisiografía</td>
                <td class='texto'>".pg_fetch_result($rsDet,0,"\"fisiograf\"")."</td>
              </tr>
			  <tr>
			  <td class='lista_titulo'>Cobertura y Uso actual</td>
			  <td align='' class='texto'>".pg_fetch_result($rsDet,0,"\"cobuso\"")."</td>
			</tr>
			<tr>
			  <td class='lista_titulo'>Precipitación promedio</td>
			  <td class='texto'>".pg_fetch_result($rsDet,0,"\"pp_prom\"")."</td>
			</tr>
			<tr>
			<td class='lista_titulo'>Pendiente</td>
			<td align='' class='texto'>".pg_fetch_result($rsDet,0,"\"pendt\"")."</td>
		  </tr>
		  <tr>
			<td class='lista_titulo'>Vulnerabilidad</td>
			<td class='texto'>".pg_fetch_result($rsDet,0,"\"vulnerabil\"")."</td>
		  </tr>
		  <tr>
			<td class='lista_titulo'>Áreas inundables por Tsunami</td>
			<td class='texto'>".pg_fetch_result($rsDet,0,"\"tsunami\"")."</td>
		  </tr>
		  <tr>
		  <td class='lista_titulo'>Intensidad sísmica Mercalli</td>
		  <td align='' class='texto'>".pg_fetch_result($rsDet,0,"\"intensidad\"")."</td>
		</tr>
		<tr>
		  <td class='lista_titulo'>Descripción de la intensidad sísmica Mercalli</td>
		  <td class='texto'>".pg_fetch_result($rsDet,0,"\"desc_merca\"")."</td>
		</tr>
		<tr>
		  <td class='lista_titulo'>Magnitud de Sismo (Richter)</td>
		  <td align='' class='texto'>".pg_fetch_result($rsDet,0,"\"mag_ritcht\"")."</td>
		</tr>
		<tr>
		  <td class='lista_titulo'>Descripción de Magnitud Local</td>
		  <td class='texto'>".pg_fetch_result($rsDet,0,"\"descrip_ml\"")."</td>
		</tr>
			";
	    ?>
			</table>
			</td>
		  </tr>
		</table>  

		<table class='fuente_general' width="100%"><thead><tr><th><b>Fuente:</b>
			<br><?php echo('Programa de Preparación ante Desastres de la Oficina de Ayuda Humanitaria de la Unión Europea (DIPECHO). Sistema de Información de Recursos para la Atención de Desastres en Piura y Tumbes (SIRAD Piura-Tumbes). Proyecto 00073720 / septiembre 2013 - marzo 2014.');?>
		</th></tr></thead></table>
	<?php
	$name='CONADIS - Población con discapacidad';
	$capa='peru_discapacidad_pobla_discap_';
	if (!isset($_GET['excel'])) {
		$ruta=$capa.'.phtml?excel=excel&capa='.$capa.'&ovalor='.$pvalor.'&olayer=peru_conadis'.'&ocampo=gid';
		
		include 'inc/consulta_pie.php';
	}
	if (isset($_SESSION['usuario'])) {
		grabar_log_accesos('ingreso', $cod_user, $name, $descripcion);
	}
	?>
		</td></tr>
	</table>
	</td></tr>
</table>
</body>
</html>
<?php include_once("./analyticstracking.php");?>
