
<?php

if (isset($_GET['excel']) && ($_GET['excel']=='excel')){
	header("Content-type:application/x-msexcel");
	$file=$_GET['capa'];
	header("Content-Disposition: attachment; filename=".$file.".xls");
	$imgtitulo='';
} else{
	$imgtitulo='<img src="imajes/desplegable.png" width="11" height="11">';
}

/*@session_start();
	if(empty($_SESSION['usuario'])){
        header('Location: ../index.php');
	}else{$cod_user = $_SESSION['usuario'];}*/
	include ('conexion_postgres.phtml');
	include ('injection/funciones.php');
	$player = 	limpiarCadena($_GET['olayer']);
	$pcampo = 	limpiarCadena($_GET['ocampo']);
	$pvalor = limpiarCadena(limpiarNumeros($_GET['ovalor']));
	$linkPG = Conectarse_POSTGRES();
	// Browse Data
	$sQueryS = "SELECT *";
	$sQueryF = " FROM vw_peru_discapacidad_pcm_ministerio";
	$sQueryW = " WHERE gid = '" . $pvalor . "'";

	$sQuery = $sQueryS . $sQueryF . $sQueryW;
	$rsDet = pg_query( $linkPG , $sQuery );
	$titulo_ventana = 'CUMPLIMIENTO DE LA CUOTA DE EMPLEO (5%) - MINISTERIOS';
	$titulo = 'CUMPLIMIENTO DE LA CUOTA DE EMPLEO (5%) - MINISTERIOS';
	include ('inc/consulta_cabecera.php');
?>
<table width="100%" border="0" cellspacing="0" cellpadding="10">
  <tr><td>
	<table width="100%" class="marco_general">
	  <tr><td>
		<table width="100%" class="marco_individual">
		  <!--tr>
			<td>
				<table width="100%" class="titulo_general">
				  <tr>
					<td>&nbsp;&nbsp;UBICACI&Oacute;N GEOGR&Aacute;FICA</td>
				  </tr>
				</table>
				<table width='100%' align='center' class='general'>
					<thead>
					  <tr>
						<th width='25%'>Departamento</th>
						<th width='25%'>Provincia</th>
						<th width='25%'>Distrito</th>
						<th width='25%'>Codigo Distrito</th>
					  </tr>
					</thead>
					<tbody>
					<tr>
						<td align='center' class='texto'><?php echo(pg_fetch_result($rsDet,0,"\"nom_dpto\"")) ?></td>
						<td align='center' class='texto'><?php echo(pg_fetch_result($rsDet,0,"\"nom_prov\"")) ?></td>
						<td align='center' class='texto'><?php echo(pg_fetch_result($rsDet,0,"\"nom_dist\"")) ?></td>
						<td align='center' class='texto'><?php echo(pg_fetch_result($rsDet,0,"\"cod_dist\"")) ?></td>
					</tr>
	
					</tbody>
				</table>
			</td>
		  </tr-->
		</table>
		<br>
		<table width="100%" class="marco_individual">
		  <tr>
			<td>
				<table width="100%" class="titulo_general">
					  <tr>
						<td>&nbsp;&nbsp;DATOS DEL MAPA</td>
					  </tr>
				</table>
				<table width="100%" class="titulo_general">
					  <tr>
						<td>&nbsp;&nbsp;CUMPLIMIENTO DE LA CUOTA DE EMPLEO (5%) - MINISTERIOS</td>
					  </tr>
				</table>
			<table width='100%' align='center' class='general'>
		<?php
        print "
			<tr>
				<td width='50%' class='lista_titulo'>Nombre del Ministerio</td>
				<td width='50%' class='texto1'>".pg_fetch_result($rsDet,0,"\"entidades\"")."</td>
      		</tr>
        	<tr>
				<td width='50%' class='lista_titulo'>Total de Trabajadores</td>
				<td width='50%' class='texto1'>".pg_fetch_result($rsDet,0,"\"tot_trab_text\"")."</td>
			  </tr>
			  <tr>
				<td class='lista_titulo'>Total de Personas con Discapacidad</td>
                <td class='texto1'>".pg_fetch_result($rsDet,0,"\"tot_pcd_text\"")."&nbsp;</td>
			  </tr>
			  
			  <tr>
				<td class='lista_titulo'>% de Cumplimiento</td>
				<td class='texto1'>".pg_fetch_result($rsDet,0,"\"p_cumplim_text\"")."</td>
				</tr>
              <tr>
                <td class='lista_titulo'>Total de Personas con Discapacidad faltantes </td>
                <td class='texto1'>".pg_fetch_result($rsDet,0,"\"tot_pcd_f_text\"")."&nbsp;</td>
              </tr>
              <tr>
                <td class='lista_titulo'>% Faltante al cumplimiento del 5%</td>
                <td class='texto1'>".pg_fetch_result($rsDet,0,"\"p_falt_cu5_text\"")."</td>
              </tr>

              <tr>
                <td class='lista_titulo'>Total de Entidades Fiscalizadas</td>
                <td class='texto1'>".pg_fetch_result($rsDet,0,"\"t_ent_fisc\"")."</td>
              </tr>

              <tr>
                <td class='lista_titulo'>N° de entidades que SI dan Cumplimiento de la Cuota de Empleo (5%)</td>
               <td class='texto1'>".pg_fetch_result($rsDet,0,"\"cu_ce5_si\"")."</td>
              </tr>
              <tr>
                <td class='lista_titulo'>N° de entidades que NO dan Cumplimiento de la Cuota de Empleo (5%)</td>
                <td class='texto1'>".pg_fetch_result($rsDet,0,"\"cu_ce5_no\"")."</td>
              </tr>

              <tr>
              <td class='lista_titulo'>Total de Entidades que No se presentaron a la Fiscalización</td>
              <td class='texto1'>".pg_fetch_result($rsDet,0,"\"t_en_nofis\"")."</td>
              </tr>

			";
		?>
			</table>
			</td>
		  </tr>
		</table>
		<br>
		
		<table class='fuente_general' width="100%"><thead><tr><th><b>Fuente:</b>
			<br><?php echo pg_fetch_result($rsDet,0,"\"fuente\"");?></th></tr></thead>
		</table>
	<?php
	//$name=strtoupper(pg_fetch_result($rsDet,0,"\"tipoaerona\"").' - '.pg_fetch_result($rsDet,0,"\"label\""));
	$name='CUMPLIMIENTO DE LA CUOTA DE EMPLEO (5%) - MINISTERIO';
	$capa='CUMPLIMIENTO DE LA CUOTA DE EMPLEO (5%) - MINISTERIO';
	if (!isset($_GET['excel'])) {
		$ruta=$capa.'.phtml?excel=excel&capa='.$capa.'&ovalor='.$pvalor.'&olayer=peru_discapacidad_pcm_ministerio'.'&ocampo=gid';
		include 'inc/consulta_pie.php';
	}
	if (isset($_SESSION['usuario'])) {
		grabar_log_accesos('ingreso', $cod_user, $name, $descripcion);
	}
	?>
		</td>
	  </tr>
	</table>
	</td>
  </tr>
</table>
</body>
</html>
<?php include_once("./analyticstracking.php");?>