<?php

if (isset($_GET['excel']) && ($_GET['excel']=='excel')) {
	header("Content-type:application/x-msexcel");
	$file=$_GET['capa'];
	header("Content-Disposition: attachment; filename=".$file.".xls");
	$imgtitulo='';
} else {
	$imgtitulo='<img src="imajes/desplegable.png" width="11" height="11">';
}

/*@session_start();
	if(empty($_SESSION['usuario'])){
        header('Location: ../index.php');
	}else{$cod_user = $_SESSION['usuario'];}*/
	include ('conexion_postgres.phtml');
	include ('injection/funciones.php');
	$player = limpiarCadena($_GET['olayer']);
	$pvalor =$_GET['ovalor'];
	$sQuery = " SELECT * FROM peru_concesiones_mineras where gid = '".$pvalor."'";
	$pcampo = limpiarCadena($_GET['ocampo']);
	$linkPG = Conectarse_POSTGRES();
	$rsDet = pg_query( $linkPG , $sQuery );
	

		$titulo_ventana = 'CONCESIONES MINERAS - '.pg_fetch_result($rsDet,0,"\"nombre\"");
		$titulo = 'CONCESIONES MINERAS <br> '.pg_fetch_result($rsDet,0,"\"nombre\"");
		include ('inc/consulta_cabecera.php');
?>

<table width="100%" class="marco_general">
  <tr><td><table width="100%" class="marco_individual">
	  <tr>
		<td>
		<table width="100%" class="titulo_general">
		  <tr>
			<td>&nbsp;&nbsp;UBICACI&Oacute;N GEOGR&Aacute;FICA</td>
		  </tr>
		</table>
		<table width='100%' align='center' class='general'>
			<thead>
			  <tr>
				<th width='25%'><?php echo( getTablaCampo('peru_concesiones_mineras','nom_dpto'));?></th>
				<th width='25%'><?php echo( getTablaCampo('peru_concesiones_mineras','nom_prov'));?></th>
				<th width='25%'><?php echo( getTablaCampo('peru_concesiones_mineras','nom_dist'));?></th>
				<th width='25%'><?php echo( getTablaCampo('peru_concesiones_mineras','codigo'));?></th>
			  </tr>
			</thead>
			<tbody>
<?php
		    print"<tr><td align='center' class='texto'>".pg_fetch_result($rsDet,0,"\"nom_dpto\"")."</td>";
			print"<td align='center' class='texto'>".pg_fetch_result($rsDet,0,"\"nom_prov\"")."</td>";
			print"<td align='center' class='texto'>".pg_fetch_result($rsDet,0,"\"nom_dist\"")."</td>
					<td align='center' class='texto'>".pg_fetch_result($rsDet,0,"\"codigo\"")."</td></tr>";
?>
			</tbody>
		</table>
		</td>
	  </tr>
	</table>
</br>
  <table width="100%" class="marco_individual">
		<tr>
			<td colspan="3">
				<table width="100%" class="titulo_general">
				  <tr>
					<td>&nbsp;&nbsp;Datos Generales</td>
				  </tr>
				</table>
			</td>
		</tr>
<?php
	echo('<tr><td><table width="100%" align="center" class="general">
			<tbody>
			<tr>
				<td  class="texto1">Nombre de la concesión</td>
				<td  class="texto1">'.pg_fetch_result($rsDet,0,"\"nombre\"").'</td>
			</tr>
			<tr>
				<td  class="texto1">Código</td>
				<td  class="texto1">'.pg_fetch_result($rsDet,0,"\"codigo\"").'</td>
			</tr>
			<tr>
				<td  class="texto1">Titular de la concesión minera</td>
				<td  class="texto1">'.pg_fetch_result($rsDet,0,"\"titularref\"").'</td>
			</tr>
				<tr>
				<td  class="texto1">Fecha de denuncio</td>
				<td  class="texto1">'.pg_fetch_result($rsDet,0,"\"fec_denu\"").'</td>
			</tr>
			<tr >
				<td  class="texto1">Zona geográfica UTM</td>
				<td  class="texto1">'.pg_fetch_result($rsDet,0,"\"zona\"").'</td>
			</tr>
			<tr>
				<td  class="texto1">Carta</td>
				<td  class="texto1">'.pg_fetch_result($rsDet,0,"\"carta\"").'</td>
			</tr>
			<tr >
				<td  class="texto1">Estado de la concesión minera</td>
				<td  class="texto1">'.pg_fetch_result($rsDet,0,"\"estado\"").'</td>
			</tr>
			<tr >
				<td  class="texto1">Descripción del estado de la concesión</td>
				<td  class="texto1">'.pg_fetch_result($rsDet,0,"\"desc_estad\"").'</td>
			</tr>
			<tr >
				<td  class="texto1">Descripción de la sustancia de derecho minero</td>
				<td  class="texto1">'.pg_fetch_result($rsDet,0,"\"desc_susta\"").'</td>
			</tr>
			<tr >
				<td  class="texto1">Área (ha)</td>
				<td  class="texto1">'.pg_fetch_result($rsDet,0,"\"hectareas\"").'</td>
			</tr>
		</tbody>
</table>');
?> 

</td></tr></table><br> <table class='fuente_general' width="100%"><thead><tr><th><b>Fuente de elaboraci&oacute;n del estudio:</b>
			<br><?php echo(pg_fetch_result($rsDet,0,"\"fuente\"")); ?>
		</th></tr></thead></table>
</td></tr>
</table>
 <?php
 	$name=$titulo_ventana;
	$capa='consulta_concesiones_mineras';
	if (!isset($_GET['excel'])) {
		$ruta=$capa.'.phtml?excel=excel&capa='.$capa.'&ovalor='.$pvalor;
		include 'inc/consulta_pie.php';
	}
	if (isset($_SESSION['usuario'])) {
		grabar_log_accesos('ingreso', $cod_user, $name, $descripcion);
	}
	?>
</body></html>
<?php include_once("./analyticstracking.php");?>