<?php
/***************************************************************************************
Organización: 	Presidencia del Consejo de Ministros - PCM
Gerencia	: 	Secretaría de Descentralización
Sistema		: 	Sistema Nacional de Información Geográfica - SAYWITE
Coordinador/Desarrollador TIC: Vitaly Uriel Cespedes Reynaga vitalyuri@hotmail.com/vitalyuri@gmail.com/969228151
Periodo		: 	Septiembre 2012 - 2013
***************************************************************************************/

if (isset($_GET['excel']) && ($_GET['excel']=='excel')) {
	header("Content-type:application/x-msexcel");
	$file=$_GET['capa'];
	header("Content-Disposition: attachment; filename=".$file.".xls");
	$imgtitulo='';
} else {
	$imgtitulo='<img src="imajes/desplegable.png" width="11" height="11">';
}

// @session_start();
// 	if(empty($_SESSION['usuario'])){
//         header('Location: ../index.php');
// 		}else{$cod_user = $_SESSION['usuario'];}
	
	include ('conexion_postgres.phtml');
	
	include ('injection/funciones.php');
	
	set_time_limit(1000);		
	$player = limpiarCadena($_GET['olayer']);
	$pcampo = limpiarCadena($_GET['ocampo']);
	$pvalor = limpiarCadena(limpiarNumeros($_GET['ovalor']));
	$linkPG = Conectarse_POSTGRES(); 

	$gid = $pvalor;
	// Browse Data
	$sQueryS = "SELECT *";   
	$sQueryF = " FROM peru_instituciones_educativas";
	$sQueryW = " WHERE \"gid\" = '" . $gid . "'";

	$sQuery = $sQueryS . $sQueryF . $sQueryW;   
	$rsDet = pg_query( $linkPG , $sQuery );
	$titulo_ventana = 'INFORMACI&Oacute;N DE LA INSTITUCI&Oacute;N EDUCATIVA';
	$titulo = 'INFORMACI&Oacute;N DE LA INSTITUCI&Oacute;N EDUCATIVA';
	include ('inc/consulta_cabecera.php');
?>
<table width="100%" border="0" cellspacing="0" cellpadding="10">
  <tr><td>
	<table width="100%" class="marco_general">
	  <tr><td>
		<table class="marco_individual">
		  <tr>
			<td>
				<div id="u1" style="width: 100%;">
					<h1><table width="100%" class="titulo_general">
						  <tr>
							<td><?php echo $imgtitulo;?>&nbsp;&nbsp;UBICACI&Oacute;N GEOGR&Aacute;FICA</td>
						  </tr>
						</table></h1>
					<div>
						<table width='100%' align='center' class='general'>
							<thead>
							  <tr>
								<th width='20%'>Departamento</th>
								<th width='20%'>Provincia</th>
								<th width='20%'>Distrito</th>
								<th width='20%'>Direcci&oacute;n</th>
							  </tr>
							</thead>
						<tbody>
				<?php
					print "<tr>
							<td align='center' class='texto'>".pg_fetch_result($rsDet,0,"\"nom_dpto\"")."</td>
							<td align='center' class='texto'>".pg_fetch_result($rsDet,0,"\"nom_prov\"")."</td>
							<td align='center' class='texto'>".pg_fetch_result($rsDet,0,"\"nom_dist\"")."</td>
							<td align='center' class='texto'>".pg_fetch_result($rsDet,0,"\"dircen\"")."</td>
						   </tr>";
				?>
						</tbody>
						</table>
					</div>
				</div>
			</td>
		  </tr>
		</table>
		<br>
		<table width="100%" class="marco_individual">
		  <tr>
			<td>
				<div id="u2" style="width: 100%;">
					<h1><table width="100%" class="titulo_general">
						  <tr>
							<td><?php echo $imgtitulo;?>&nbsp;&nbsp;DATOS DE LA INSTITUCI&Oacute;N EDUCATIVA</td>
						  </tr>
						</table></h1>
					<div>
						<table width='100%' align='center' class='listado'>
		  <?php
		  		print "<tr>";
				print "<td width='50%' class='lista_titulo'>Direcci&oacute;n  Regional de Educaci&oacute;n</td>";
		  		print "<td width='50%' class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"ugel_dreno\"")."&nbsp;</td>";
				print "</tr>";
		  		print "<tr>";
				print "<td class='lista_titulo'>DRE o UGEL que supervisa la instituci&oacute;n educativa</td>";
				print "<td class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"ugel_nouge\"")."&nbsp;</td>";
		  		print "</tr>";
				print "<tr>";
				print "<td class='lista_titulo'>Nombre del centro poblado</td>";
				print "<td class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"cenpob\"")."&nbsp;</td>";
		  		print "</tr>";
				print "<tr>";
				print "<td class='lista_titulo'>Área</td>";
				print "<td class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"areaval\"")."&nbsp;</td>";
		  		print "</tr>";
				print "<tr >";
				print "<td class='lista_titulo'>Nombre de la instituci&oacute;n educativa</td>";
				print "<td class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"cenedu\"")."&nbsp;</td>";
		  		print "</tr>";
				print "<tr >";
				print "<td class='lista_titulo'>Código modular de la institución educativa</td>";
				print "<td class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"codmod\"")."&nbsp;</td>";
		  		print "</tr>";
				print "<tr >";
				print "<td class='lista_titulo'>Código del local escolar</td>";
				print "<td class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"cod_local\"")."&nbsp;</td>";
		  		print "</tr>";				
		  		print "<tr>";
				print "<td class='lista_titulo'>Modalidad o nivel educativo que ofrece la institución educativa</td>";
				print "<td class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"nivmod_val\"")."&nbsp;</td>";
		  		print "</tr>";
				print "<tr>";
				print "<td class='lista_titulo'>Forma en que se ofrece el servicio de enseñanza</td>";
				print "<td class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"form_valor\"")."&nbsp;</td>";
		  		print "</tr>";
				print "<tr>";
				print "<td class='lista_titulo'>Género de la población escolar</td>";
				print "<td class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"gene_valor\"")."&nbsp;</td>";
		  		print "</tr>";
				print "<tr>";
				print "<td class='lista_titulo'>Nombre del Director de la institución educativa</td>";
				print "<td class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"director\"")."&nbsp;</td>";
		  		print "</tr>";				
				print "<tr>";
				print "<td class='lista_titulo'>Lengua materna predominante en el centro poblado</td>";
				print "<td class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"lenetnica\"")."&nbsp;</td>";
		  		print "</tr>";		
				print "<tr>";
				print "<td class='lista_titulo'>Relación entre el número de docentes y el número de secciones que atienden</td>";
				print "<td class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"car_valor\"")."&nbsp;</td>";
		  		print "</tr>";		
				print "<tr>";
				print "<td class='lista_titulo'>Número telefónico de la institución educativa.</td>";
				print "<td class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"telefono\"")."&nbsp;</td>";
		  		print "</tr>";		
				print "<tr>";
				print "<td class='lista_titulo'>Dirección de correo electrónico de la institución educativa.</td>";
				print "<td class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"email\"")."&nbsp;</td>";
		  		print "</tr>";		
				print "<tr>";
				print "<td class='lista_titulo'>Turno que se imparte el servicio educativo</td>";
				print "<td class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"turn_valor\"")."&nbsp;</td>";
		  		print "</tr>";		
				print "<tr>";
				print "<td class='lista_titulo'>Entidad que gestiona la institución educativa</td>";
				print "<td class='lista_textosub'>".pg_fetch_result($rsDet,0,"\"gesdep_val\"")."&nbsp;</td>";
		  		print "</tr>";
				
?>
						</table>
					</div>
				</div>
			</td>
		  </tr>
		</table>
		<br>
		<table width="100%" class="marco_individual">
		  <tr>
			<td>
				<div id="u3" style="width: 100%;">
					<h1><table width="100%" class="titulo_general">
						  <tr>
							<td><?php echo $imgtitulo;?>&nbsp;&nbsp;INSTITUCIONES EDUCATIVAS - DISTRITO <?php print pg_fetch_result($rsDet,0,"\"nom_dist\"");?></td>
						  </tr>
						</table></h1>
					<div>
<?php
			$cabecera_tabla = "<table width='100%' align='center' class='general'>
								<tr><td width='28%' class='titulosub'><b>Instituci&oacute;n Educativa (I.E.)</b></td>
								<td width='8%' class='titulosub'><b>Inicial</b></td>
								<td width='8%' class='titulosub'><b>Primaria</b></td>
								<td width='8%' class='titulosub'><b>Secundaria</b></td>
								<td width='8%' class='titulosub'><b>Básica Alternativa CEBA</b></td>
								<td width='8%' class='titulosub'><b>Especial</b></td>
								<td width='8%' class='titulosub'><b>Superior Pedagógico - ISP</b></td>
								<td width='8%' class='titulosub'><b>Técnico Prod. - CETPRO</b></td>
								<td width='8%' class='titulosub'><b>Superior Artística - ESFA</b></td>
								<td width='8%' class='titulosub'><b>Superior Tecnológica - IST</b></td>
								</tr>";
//lista de centros educativos a nivel distrital
	$cceeQuery="select * from peru_instituciones_educativas where cod_dist = '".pg_fetch_result($rsDet,0,"\"cod_dist\"")."' order by cenedu";
	$rsDetcenedu = pg_query($linkPG , $cceeQuery);
    $numrowscenedu = pg_num_rows($rsDetcenedu);
	echo($cabecera_tabla);	
	$i=0;
	$j=1;
while($i<$numrowscenedu){
	if(pg_fetch_result($rsDetcenedu,$i,"\"gid\"")==pg_fetch_result($rsDet,0,"\"gid\"")){
		$classet=' class="titulo11"';
		$classe=' align="left" class="titulo11"';
		$class=' align = "center" class="titulo11"';
	} else {
		$classet='class="titulo111"';
		$classe='class="textosub"';
		$class=' align = "center" class="fondocuerpo"';
	}
	if (isset($_GET['excel']) && ($_GET['excel']=='excel')) {
		$enlace=$j;
	} else {
		$enlace='<a href="consulta_Institucion_educativa.phtml?olayer=educacion_primaria&ocampo='.$pcampo.'&ovalor='.pg_fetch_result($rsDetcenedu,$i,"\"gid\"").'">'.$j.'</a>';
	}
	echo('<tr><td '.$classet.'>'.$enlace.'- '.pg_fetch_result($rsDetcenedu,$i,"\"cenedu\"").'</td>');
		
		
		
		$nivel_mod = pg_fetch_result($rsDetcenedu,$i,"\"nivmod_cod\"");	
		for($columnas=0;$columnas<9;$columnas++){
				if($columnas==0){
					if($nivel_mod=='A1'||$nivel_mod=='A2'||$nivel_mod=='A3'||$nivel_mod=='A5'){
						echo('<td '.$classe.'><img src="imajes/check.png"" width="15" height="15"/></td>');
					} else {
						echo('<td '.$classe.'>&nbsp</td>');
					}
				}else if($columnas==1){
					if($nivel_mod=='B0'||$nivel_mod=='C0'){
						echo('<td '.$classe.'><img src="imajes/check.png"" width="15" height="15"/></td>');
					} else {
						echo('<td '.$classe.'>&nbsp;</td>');
					}
				}else if($columnas==2){
					if($nivel_mod=='F0'||$nivel_mod=='G0'){
						echo('<td '.$classe.'><img src="imajes/check.png"" width="15" height="15"/></td>');
					} else {
						echo('<td '.$classe.'>&nbsp;</td>');
					}
				}else if($columnas==3){
					if($nivel_mod=='D0'){
						echo('<td '.$classe.'><img src="imajes/check.png"" width="15" height="15"/></td>');
					} else {
						echo('<td '.$classe.'>&nbsp;</td>');
					}
				}else if($columnas==4){
					if($nivel_mod=='E0'){
						echo('<td '.$classe.'><img src="imajes/check.png"" width="15" height="15"/></td>');
					} else {
						echo('<td '.$classe.'>&nbsp;</td>');
					}
				}else if($columnas==5){
					if($nivel_mod=='K0'){
						echo('<td '.$classe.'><img src="imajes/check.png"" width="15" height="15"/></td>');
					} else {
						echo('<td '.$classe.'>&nbsp;</td>');
					}
				}else if($columnas==6){
					if($nivel_mod=='L0'){
						echo('<td '.$classe.'><img src="imajes/check.png"" width="15" height="15"/></td>');
					} else {
						echo('<td '.$classe.'>&nbsp;</td>');
					}
				}else if($columnas==7){
					if($nivel_mod=='M0'){
						echo('<td '.$classe.'><img src="imajes/check.png"" width="15" height="15"/></td>');
					} else {
						echo('<td '.$classe.'>&nbsp;</td>');
					}
				}else if($columnas==8){
					if($nivel_mod=='T0'){
						echo('<td '.$classe.'><img src="imajes/check.png"" width="15" height="15"/></td>');
					} else {
						echo('<td '.$classe.'>&nbsp;</td>');
					}
				}
		}

	$i++;
	$j++;
	echo('</tr>');
}

echo('<tr><td class="titulosub">Total</td>');
for($total_distrital=0; $total_distrital<9; $total_distrital++){
	if($total_distrital==0){
		$niv_mod = "'A1','A2','A3','A5'";
	}else if($total_distrital==1){
		$niv_mod = "'B0','C0'";
	}else if($total_distrital==2){
		$niv_mod = "'F0','G0'";
	}else if($total_distrital==3){
		$niv_mod = "'D0'";
	}else if($total_distrital==4){
		$niv_mod = "'E0'";
	}else if($total_distrital==5){
		$niv_mod = "'K0'";
	}else if($total_distrital==6){
		$niv_mod = "'L0'";
	}else if($total_distrital==7){
		$niv_mod = "'M0'";
	}else if($total_distrital==8){
		$niv_mod = "'T0'";
	}
	$consultaDistrito   = "select count(*) as cantidaddist from peru_instituciones_educativas where cod_dist ='".pg_fetch_result($rsDet,0,"\"cod_dist\"")."' and nivmod_cod in(".$niv_mod.")";
	$rsconsultaDistrito = pg_query($linkPG , $consultaDistrito);
		echo('<td class="titulosub"><b>'.pg_fetch_result($rsconsultaDistrito,0,"\"cantidaddist\"").'</b></td>');
		}
echo ('</tr></table>');
		?>
					</div>
				</div>
			</td>
		  </tr>
		</table>
		<br>
		<table width="100%" class="marco_individual">
		  <tr>
			<td>
				<div id="u4" style="width: 100%;">
					<h1><table width="100%" class="titulo_general">
						  <tr>
							<td><?php echo $imgtitulo;?>&nbsp;&nbsp;INSTITUCIONES EDUCATIVAS - PROVINCIA <?php echo pg_fetch_result($rsDet,0,"\"nom_prov\"");?></td>
						  </tr>
						</table></h1>
					<div>
<?php
			echo($cabecera_tabla);
			$distQuery		=	"select count(cod_dist) cantidad,cod_dist,nom_dist from peru_instituciones_educativas where cod_prov='".pg_fetch_result($rsDet,0,"\"cod_prov\"")."' group by cod_dist, nom_dist order by cod_dist";
			$rsDetdist 		= 	pg_query($linkPG , $distQuery);
			$numrowsDist 	= 	pg_num_rows($rsDetdist);
			$k = 0;
			$l = 1;
			
			$total_dist_inicial		=0;
			$total_dist_primaria	=0;
			$total_dist_secundaria	=0;
			$total_dist_seba		=0;
			$total_dist_especial	=0;
			$total_dist_isp			=0;
			$total_dist_cetpro		=0;
			$total_dist_esfa		=0;
			$total_dist_ist			=0;
			while($k<$numrowsDist){
				if(pg_fetch_result($rsDetdist,$k,"\"cod_dist\"")==pg_fetch_result($rsDet,0,"\"cod_dist\"")){
					$classe=' align="center" class="titulo11"';
					} else {
					$classe=' class="textosub"';
				}
			
			echo('<tr><td '.$classet.'>'.pg_fetch_result($rsDetdist,$k,"\"nom_dist\"").'</td>');
			for($total_distrital=0; $total_distrital<9; $total_distrital++){
				if($total_distrital==0){
					$niv_mod = "'A1','A2','A3','A5'";
				}else if($total_distrital==1){
					$niv_mod = "'B0','C0'";
				}else if($total_distrital==2){
					$niv_mod = "'F0','G0'";
				}else if($total_distrital==3){
					$niv_mod = "'D0'";
				}else if($total_distrital==4){
					$niv_mod = "'E0'";
				}else if($total_distrital==5){
					$niv_mod = "'K0'";
				}else if($total_distrital==6){
					$niv_mod = "'L0'";
				}else if($total_distrital==7){
					$niv_mod = "'M0'";
				}else if($total_distrital==8){
					$niv_mod = "'T0'";
				}
				$consultaProvincia   = "select count(*) as cantidaddist from peru_instituciones_educativas where cod_dist ='".pg_fetch_result($rsDetdist,$k,"\"cod_dist\"")."' and nivmod_cod in(".$niv_mod.")";
					$rsconsultaProvincia = pg_query($linkPG , $consultaProvincia);
					echo('<td '.$classe.'>'.pg_fetch_result($rsconsultaProvincia,0,"\"cantidaddist\"").'</td>');
					
						if($total_distrital==0){
							$total_dist_inicial = $total_dist_inicial + pg_fetch_result($rsconsultaProvincia,0,"\"cantidaddist\"");
						}else if($total_distrital==1){
							$total_dist_primaria = $total_dist_primaria + pg_fetch_result($rsconsultaProvincia,0,"\"cantidaddist\"");
						}else if($total_distrital==2){
							$total_dist_secundaria = $total_dist_secundaria + pg_fetch_result($rsconsultaProvincia,0,"\"cantidaddist\"");
						}else if($total_distrital==3){
							$total_dist_seba = $total_dist_seba + pg_fetch_result($rsconsultaProvincia,0,"\"cantidaddist\"");
						}else if($total_distrital==4){
							$total_dist_especial = $total_dist_especial + pg_fetch_result($rsconsultaProvincia,0,"\"cantidaddist\"");
						}else if($total_distrital==5){
							$total_dist_isp = $total_dist_isp + pg_fetch_result($rsconsultaProvincia,0,"\"cantidaddist\"");
						}else if($total_distrital==6){
							$total_dist_cetpro = $total_dist_cetpro + pg_fetch_result($rsconsultaProvincia,0,"\"cantidaddist\"");
						}else if($total_distrital==7){
							$total_dist_esfa = $total_dist_esfa + pg_fetch_result($rsconsultaProvincia,0,"\"cantidaddist\"");
						}else if($total_distrital==8){
							$total_dist_ist = $total_dist_ist + pg_fetch_result($rsconsultaProvincia,0,"\"cantidaddist\"");
						}
					}
			$k++;
			$l++;
			}
			print("<tr><td class='titulosub'>Total</td>");
			print("<td class='titulosub'>".$total_dist_inicial."</td>");
			print("<td class='titulosub'>".$total_dist_primaria."</td>");
			print("<td class='titulosub'>".$total_dist_secundaria."</td>");
			print("<td class='titulosub'>".$total_dist_seba."</td>");
			print("<td class='titulosub'>".$total_dist_especial."</td>");
			print("<td class='titulosub'>".$total_dist_isp."</td>");
			print("<td class='titulosub'>".$total_dist_cetpro."</td>");
			print("<td class='titulosub'>".$total_dist_esfa."</td>");
			print("<td class='titulosub'>".$total_dist_ist."</td>");
			
			print("</tr>");
			echo("</table>");
		?>
					</div>
				</div>
			</td>
		  </tr>
		</table>
		<br>
		<table width="100%" class="marco_individual">
		  <tr>
			<td>
				<div id="u5" style="width: 100%;">
					<h1><table width="100%" class="titulo_general">
						  <tr>
							<td><?php echo $imgtitulo;?>&nbsp;&nbsp;INSTITUCIONES EDUCATIVAS - DEPARTAMENTO <?php echo pg_fetch_result($rsDet,0,"\"nom_dpto\"");?></td>
						  </tr>
						</table></h1>
					<div>
			<?php
			echo($cabecera_tabla);
//lista de provincias por departamento
			$provQuery		=	"select count(cod_prov) as cantidad, cod_prov, nom_prov from peru_instituciones_educativas where cod_dpto = '".pg_fetch_result($rsDet,0,"\"cod_dpto\"")."' group by cod_prov, nom_prov";
			$rsDetprov 		= 	pg_query($linkPG , $provQuery);
			$numrowsProv 	= 	pg_num_rows($rsDetprov);
			$m = 0;
			$n = 1;
			$total_prov_inicial		=0;
			$total_prov_primaria	=0;
			$total_prov_secundaria	=0;
			$total_prov_seba		=0;
			$total_prov_especial	=0;
			$total_prov_isp			=0;
			$total_prov_cetpro		=0;
			$total_prov_esfa		=0;
			$total_prov_ist			=0;
			while($m<$numrowsProv){
				if(pg_fetch_result($rsDetprov,$m,"\"cod_prov\"")==pg_fetch_result($rsDet,0,"\"cod_prov\"")){
					$classe='align="center" class="titulo11"';
				} else {
					$classe='class="textosub"';
				}

				echo('<tr><td '.$classet.'>'.pg_fetch_result($rsDetprov,$m,"\"nom_prov\"").'</td>');
					
					for($total_departamento=0; $total_departamento<9; $total_departamento++){
					if($total_departamento==0){
						$niv_modd = "'A1','A2','A3','A5'";
					}else if($total_departamento==1){
						$niv_modd = "'B0','C0'";
					}else if($total_departamento==2){
						$niv_modd = "'F0','G0'";
					}else if($total_departamento==3){
						$niv_modd = "'D0'";
					}else if($total_departamento==4){
						$niv_modd = "'E0'";
					}else if($total_departamento==5){
						$niv_modd = "'K0'";
					}else if($total_departamento==6){
						$niv_modd = "'L0'";
					}else if($total_departamento==7){
						$niv_modd = "'M0'";
					}else if($total_departamento==8){
						$niv_modd = "'T0'";
					}
					$consultaProvinciass   = "select count(*) as cantidadprovin from peru_instituciones_educativas where cod_prov ='".pg_fetch_result($rsDetprov,$m,"\"cod_prov\"")."' and nivmod_cod in(".$niv_modd.")";
					$rsconsultaProvincias = pg_query($linkPG , $consultaProvinciass);
						echo('<td '.$classe.'>'.pg_fetch_result($rsconsultaProvincias,0,"\"cantidadprovin\"").'</td>');
						
						if($total_departamento==0){
							$total_prov_inicial = $total_prov_inicial + pg_fetch_result($rsconsultaProvincias,0,"\"cantidadprovin\"");
						}else if($total_departamento==1){
							$total_prov_primaria = $total_prov_primaria + pg_fetch_result($rsconsultaProvincias,0,"\"cantidadprovin\"");
						}else if($total_departamento==2){
							$total_prov_secundaria = $total_prov_secundaria + pg_fetch_result($rsconsultaProvincias,0,"\"cantidadprovin\"");
						}else if($total_departamento==3){
							$total_prov_seba = $total_prov_seba + pg_fetch_result($rsconsultaProvincias,0,"\"cantidadprovin\"");
						}else if($total_departamento==4){
							$total_prov_especial = $total_prov_especial + pg_fetch_result($rsconsultaProvincias,0,"\"cantidadprovin\"");
						}else if($total_departamento==5){
							$total_prov_isp = $total_prov_isp + pg_fetch_result($rsconsultaProvincias,0,"\"cantidadprovin\"");
						}else if($total_departamento==6){
							$total_prov_cetpro = $total_prov_cetpro + pg_fetch_result($rsconsultaProvincias,0,"\"cantidadprovin\"");
						}else if($total_departamento==7){
							$total_prov_esfa = $total_prov_esfa + pg_fetch_result($rsconsultaProvincias,0,"\"cantidadprovin\"");
						}else if($total_departamento==8){
							$total_prov_ist = $total_prov_ist + pg_fetch_result($rsconsultaProvincias,0,"\"cantidadprovin\"");
						}
						
						}
				
				$m++;
				$n++;
			}
			
			print("<tr><td class='titulosub'>Total</td>
			<td class='titulosub'>".$total_prov_inicial."</td>
			<td class='titulosub'>".$total_prov_primaria."</td><td class='titulosub'>".$total_prov_secundaria."</td><td class='titulosub'>".$total_prov_seba."</td><td class='titulosub'>".$total_prov_especial."</td><td class='titulosub'>".$total_prov_isp."</td><td class='titulosub'>".$total_prov_cetpro."</td><td class='titulosub'>".$total_prov_esfa."</td><td class='titulosub'>".$total_prov_ist."</td>
			</tr>");
			
?>
					</table>
					</div>
				</div>
			</td>
		  </tr>
		</table><?php 
	if(getComDesc($player)!=''){
			include ('inc/descarga.php');	
	}
		?><br>
		<table class='fuente_general' width="100%"><thead><tr><th><b>Fuente:</b>
			<br><?php echo pg_fetch_result($rsDet,0,"\"fuente\"");?>
			</th></tr></thead>
		</table>
	<?php
	$name=strtoupper('INSTITUCION EDUCATIVA ');
	$capa='consulta_Institucion_educativa';
	if (!isset($_GET['excel'])) {
		//$ruta=$capa.'.phtml?excel=excel&capa='.$capa.'&ovalor='.$pvalor;
		$ruta=$capa.'.phtml?excel=excel&capa='.$capa.'&ovalor='. $pvalor.'&olayer='.$player.'&niv_descarga='.$niv_descarga.'&descarga='.$descarga;
		include 'inc/consulta_pie.php';
	}
	if (isset($_SESSION['usuario'])) {
		grabar_log_accesos('ingreso', $cod_user, $name, $descripcion);
	}
	
	pg_close($linkPG);
	?>
		</td></tr>
	</table>
	</td></tr>
</table>
</body>

<script language="javascript" type="text/javascript">
	$(document).ready(function(){
		$("#u1").h2c_acordeon();
		$("#u2").h2c_acordeon();
		$("#u3").h2c_acordeon();
		$("#u4").h2c_acordeon();
		$("#u5").h2c_acordeon();
		$("#u6").h2c_acordeon();
	});
</script>

</html>
