
<?php

if (isset($_GET['excel']) && ($_GET['excel']=='excel')){
	header("Content-type:application/x-msexcel");
	$file=$_GET['capa'];
	header("Content-Disposition: attachment; filename=".$file.".xls");
	$imgtitulo='';
} else{
	$imgtitulo='<img src="imajes/desplegable.png" width="11" height="11">';
}

/*@session_start();
	if(empty($_SESSION['usuario'])){
        header('Location: ../index.php');
	}else{$cod_user = $_SESSION['usuario'];}*/
	include ('conexion_postgres.phtml');
	include ('injection/funciones.php');
	$player = 	limpiarCadena($_GET['olayer']);
	$pcampo = 	limpiarCadena($_GET['ocampo']);
	$pvalor = limpiarCadena(limpiarNumeros($_GET['ovalor']));
	$linkPG = Conectarse_POSTGRES();
	// Browse Data
	$sQueryS = "SELECT *";
	$sQueryF = " FROM vw_peru_pronacej_soa";
	$sQueryW = " WHERE gid = '" . $pvalor . "'";

	$sQuery = $sQueryS . $sQueryF . $sQueryW;
	$rsDet = pg_query( $linkPG , $sQuery );
	$titulo_ventana = 'Servicio de Orientación al Adolescente (SOA)';
	$titulo = 'Servicio de Orientación al Adolescente (SOA)';
	include ('inc/consulta_cabecera.php');
?>
<table width="100%" border="0" cellspacing="0" cellpadding="10">
  <tr><td>
	<table width="100%" class="marco_general">
	  <tr><td>
		<table width="100%" class="marco_individual">
		  <!--tr>
			<td>
				<table width="100%" class="titulo_general">
				  <tr>
					<td>&nbsp;&nbsp;UBICACI&Oacute;N GEOGR&Aacute;FICA</td>
				  </tr>
				</table>
				<table width='100%' align='center' class='general'>
					<thead>
					  <tr>
						<th width='25%'>Departamento</th>
						<th width='25%'>Provincia</th>
						<th width='25%'>Distrito</th>
						<th width='25%'>Codigo Distrito</th>
					  </tr>
					</thead>
					<tbody>
					<tr>
						<td align='center' class='texto'><?php echo(pg_fetch_result($rsDet,0,"\"nom_dpto\"")) ?></td>
						<td align='center' class='texto'><?php echo(pg_fetch_result($rsDet,0,"\"nom_prov\"")) ?></td>
						<td align='center' class='texto'><?php echo(pg_fetch_result($rsDet,0,"\"nom_dist\"")) ?></td>
						<td align='center' class='texto'><?php echo(pg_fetch_result($rsDet,0,"\"cod_dist\"")) ?></td>
					</tr>
	
					</tbody>
				</table>
			</td>
		  </tr-->
		</table>
		<br>
		<table width="100%" class="marco_individual">
		  <tr>
			<td>
				<table width="100%" class="titulo_general">
					  <tr>
						<td>&nbsp;&nbsp;DATOS GENERALES</td>
					  </tr>
				</table>
			<table width='100%' align='center' class='general'>
		<?php
        print "
        <tr>
        <td width='50%' class='lista_titulo'>Distrito en el que se cometió el delito</td>
        <td width='50%' class='texto1'>".pg_fetch_result($rsDet,0,"\"nom_dist\"")."</td>
      </tr>
        <tr>
				<td width='50%' class='lista_titulo'>N° de adolescentes infractores por Delito contra la administración pública</td>
				<td width='50%' class='texto1'>".pg_fetch_result($rsDet,0,"\"ctr_adm_pu\"")."</td>
			  </tr>
			  <tr>
				<td class='lista_titulo'>N° de adolescentes infractores por Delito contra la libertad</td>
                <td class='texto1'>".pg_fetch_result($rsDet,0,"\"ctr_libt\"")."</td>
			  </tr>
			  <tr>
				<td class='lista_titulo'>N° de adolescentes infractores por Delito contra la salud pública</td>
				<td class='texto1'>".pg_fetch_result($rsDet,0,"\"ctr_sal_pu\"")."</td>
              </tr>
              <tr>
                <td class='lista_titulo'>N° de adolescentes infractores por Delito contra la seguridad pública</td>
                <td class='texto1'>".pg_fetch_result($rsDet,0,"\"ctr_seg_pu\"")."</td>
              </tr>
              <tr>
                <td class='lista_titulo'>N° de adolescentes infractores por Delito contra la tranquilidad pública</td>
                <td class='texto1'>".pg_fetch_result($rsDet,0,"\"ctr_trq_pu\"")."</td>
              </tr>

              <tr>
                <td class='lista_titulo'>N° de adolescentes infractores por Delito por contaminación y propagación en su forma de violación de medidas sanitarias</td>
                <td class='texto1'>".pg_fetch_result($rsDet,0,"\"vio_md_san\"")."</td>
              </tr>

              <tr>
                <td class='lista_titulo'>N° de adolescentes infractores por Delito contra el Patrimonio</td>
               <td class='texto1'>".pg_fetch_result($rsDet,0,"\"ctr_patrim\"")."</td>
              </tr>

			  <tr>
			  <td class='lista_titulo'>N° de adolescentes infractores por Delito contra la familia</td>
			  <td class='texto1'>".pg_fetch_result($rsDet,0,"\"ctr_fam\"")."</td>
			  </tr>

			  <tr>
			  <td class='lista_titulo'>N° de adolescentes infractores por Delito contra la libertad</td>
		      <td class='texto1'>".pg_fetch_result($rsDet,0,"\"ctr_libt\"")."</td>
		    </tr>

			<tr>
			<td class='lista_titulo'>N° de adolescentes infractores por Delito contra la libertad sexual</td>
			<td class='texto1'>".pg_fetch_result($rsDet,0,"\"ctr_li_sex\"")."</td>
		  </tr>

		  <tr>
			<td class='lista_titulo'>N° de adolescentes infractores por Delito contra la vida el cuerpo y la salud</td>
			<td class='texto1'>".pg_fetch_result($rsDet,0,"\"cvcs\"")."</td>
		  </tr>


		  <tr>
			<td class='lista_titulo'>N° de adolescentes infractores por Delito contra el Estado</td>
			<td class='texto1'>".pg_fetch_result($rsDet,0,"\"ctr_est\"")."</td>
		  </tr>


		  <tr>
			<td class='lista_titulo'>N° de adolescentes infractores por Delito por tráfico ilícito de drogas</td>
			<td class='texto1'>".pg_fetch_result($rsDet,0,"\"trf_il_drg\"")."</td>
		  </tr>

		  <tr>
			<td class='lista_titulo'>N° de adolescentes infractores por otros Delitos</td>
			<td class='texto1'>".pg_fetch_result($rsDet,0,"\"otros\"")."</td>
		  </tr>

		  <tr>
		  <td class='lista_titulo'>Total general</td>
		  <td class='texto1'>".pg_fetch_result($rsDet,0,"\"tot_gen\"")."</td>
		</tr>

			";
		?>
			</table>
			</td>
		  </tr>
		</table>
		<br>
		
		<table class='fuente_general' width="100%"><thead><tr><th><b>Fuente:</b>
			<br><?php echo pg_fetch_result($rsDet,0,"\"fuente\"");?></th></tr></thead>
		</table>

	<?php
	//$name=strtoupper(pg_fetch_result($rsDet,0,"\"tipoaerona\"").' - '.pg_fetch_result($rsDet,0,"\"label\""));
	$name='Población Penitenciaria';
	$capa='Población Penitenciaria';
	if (!isset($_GET['excel'])) {
		$ruta=$capa.'.phtml?excel=excel&capa='.$capa.'&ovalor='.$pvalor.'&olayer=peru_internos_delito'.'&ocampo=gid';
		include 'inc/consulta_pie.php';
	}
	if (isset($_SESSION['usuario'])) {
		grabar_log_accesos('ingreso', $cod_user, $name, $descripcion);
	}
	?>
		</td>
	  </tr>
	</table>
	</td>
  </tr>
</table>
</body>
</html>
<?php include_once("./analyticstracking.php");?>