<?php
/***************************************************************************************
Organización: 	Presidencia del Consejo de Ministros - PCM
Gerencia	: 	Secretaría de Descentralización
Sistema		: 	Sistema Nacional de Información Geográfica - SAYWITE
Coordinador/Desarrollador TIC: Vitaly Uriel Cespedes Reynaga vitalyuri@hotmail.com/vitalyuri@gmail.com/969228151
Periodo		: 	Septiembre 2012 - 2013
***************************************************************************************/

if (isset($_GET['excel']) && ($_GET['excel']=='excel')) {
	header("Content-type:application/x-msexcel");
	$file=$_GET['capa'];
	header("Content-Disposition: attachment; filename=".$file.".xls");
	$imgtitulo='';
} else {
	$imgtitulo='<img src="imajes/desplegable.png" width="11" height="11">';
}
	/*@session_start();
	if(empty($_SESSION['usuario'])){
        header('Location: ../index.php');
		}else{$cod_user = $_SESSION['usuario'];}*/
	include ('conexion_postgres.phtml');
	include ('injection/funciones.php');
	$player = limpiarCadena($_GET['olayer']);
	$pcampo = limpiarCadena($_GET['ocampo']);
	$pvalor = limpiarCadena($_GET['ovalor']);
	$linkPG = Conectarse_POSTGRES();
	// Browse Data
	$sQueryS = " SELECT *";   
	$sQueryF = " FROM data_pma_fenomenos_dist ";
	$sQueryW = " WHERE \"cod_dist\" = '" . $pvalor . "'";

	$sQuery = $sQueryS . $sQueryF . $sQueryW;   
	$rsDet = pg_query( $linkPG , $sQuery );

	$rsDet = pg_query( $linkPG , $sQuery );
	$niv_via15=pg_fetch_result($rsDet,0,"\"niv_via15\"");
				switch ($niv_via15) {
				case 1:
					$niv_via15_='Bajo';
					break;
				case 2:
					$niv_via15_='Medio';
					break;
				case 3:
					  $niv_via15_='Alto';
					break;
				case 4:
					$niv_via15_='Muy alto';
					break;
				}
		$titulo_ventana = '&Iacute;NDICE DE VULNERABILIDAD A LA INSEGURIDAD ALIMENTARIA - DISTRITO '.pg_fetch_result($rsDet,0,"\"nom_dist\"");
		$titulo = '&Iacute;NDICE DE VULNERABILIDAD A LA INSEGURIDAD ALIMENTARIA </br>DISTRITO'.pg_fetch_result($rsDet,0,"\"nom_dist\"");
		$subtitulo='<tr>
					<td width="100%" colspan="2"class="titulo1">Nivel de Vulnerabilidad a la Inseguridad Alimentaria	</td>
					<td class="titulo1">'.$niv_via15_.'</td>
				</tr>
				<tr>
					<td width="100%" colspan="2"class="titulo1">&Iacute;ndice  Vulnerabilidad a la Inseguridad Alimentaria</td>
					<td class="titulo1">'.pg_fetch_result($rsDet,0,"\"via2015\"").'</td>
				</tr>';
	include ('inc/consulta_cabecera.php');
?>
<table width="100%" border="0" cellspacing="0" cellpadding="10">
  <tr><td>
	<table width="100%" class="marco_general">
	  <tr><td>
		<table class="marco_individual">
		  <tr>
			<td>
				<div id="u1" style="width: 100%;">
					<h1><table width="100%" class="titulo_general">
						  <tr>
							<td><?php echo $imgtitulo;?>&nbsp;&nbsp;UBICACI&Oacute;N GEOGR&Aacute;FICA</td>
						  </tr>
						</table></h1>
					<div>
						<table width='100%' align='center' class='general'>
							<thead>
							  <tr>
								<th width='25%' align='center'>Departamento</th>
								<th width="25%" align='center'>Provincia</th>
								<th width="25%" align='center'>Distrito</th>
								<th width='25%' align='center'>Ubigeo</th>
							  </tr>
							</thead>
							<tbody>
	<?php
					print "<tr>
							<td align='center' class='texto'>".pg_fetch_result($rsDet,0,"\"nom_dpto\"")."</td>
							<td align='center' class='texto'>".pg_fetch_result($rsDet,0,"\"nom_prov\"")."</td>
							<td align='center' class='texto'>".pg_fetch_result($rsDet,0,"\"nom_dist\"")."</td>
							<td align='center' class='texto'>".pg_fetch_result($rsDet,0,"\"cod_dist\"")."</td>
						</tr>";
	?>
						</tbody>
						</table>
					</div>
				</div>
			</td>
		  </tr>
		</table>
		<br>
		<table width="100%" class="marco_individual">
		  <tr>
			<td>
				<div id="u2" style="width: 100%;">
					<h1><table width="100%" class="titulo_general">
						  <tr>
							<td><?php echo $imgtitulo;?>&nbsp;&nbsp;DATOS DEL MAPA</td>
						  </tr>
						</table></h1>
					<div>
		<?php
		print "<table width='100%' align='center' class='general'>
				<!--thead>
				  <tr>
					<th height='34' colspan='2'><strong>VARIABLE / INDICADOR</strong></th>
					<th><strong>Cifras Absolutas</strong></th>
					<th><strong>%</strong></th>
				  </tr>
				</thead-->
			<tbody>".$subtitulo;
		echo('
		<tr class="texto">
    <td rowspan="4" class="texto1"><b>Disponibilidad de alimentos</b></td>
    <td class="texto1">Indice de Herfindahl 2007</td>
    <td class="texto1">'.pg_fetch_result($rsDet,0,"\"ind_herf07\"").'</td>
  </tr>
  <tr>
    <td class="texto1">Ratio tierras agr&iacute;colas en secano 2012</td>
    <td class="texto1">'.pg_fetch_result($rsDet,0,"\"rat_ag_s12\"").'</td>
  </tr>
  <tr>
    <td class="texto1">Ratio superficie con cultivos autoconsumo 2012</td>
    <td class="texto1">'.pg_fetch_result($rsDet,0,"\"rat_cu_a12\"").'</td>
  </tr>
  <tr>
    <td class="texto1">Vulnerabilidad a la disponibilidad</td>
    <td class="texto1">'.pg_fetch_result($rsDet,0,"\"vuln_dispo\"").'</td>
  </tr>
  <tr>
    <td rowspan="6" class="texto1"><b>Acceso a los alimentos</b></td>
    <td class="texto1">Brecha Indice ingreso    mensual per c&aacute;pita 2012</td>
    <td class="texto1">'.pg_fetch_result($rsDet,0,"\"b_i_impc12\"").'</td>
  </tr>
  <tr>
    <td class="texto1">Ratio PEA 14 y m&aacute;s en agricultura 2007</td>
    <td class="texto1">'.pg_fetch_result($rsDet,0,"\"rpea14_a07\"").'</td>
  </tr>
  <tr>
    <td class="texto1">Ratio poblac. en viv. piso de tierra 2007</td>
    <td class="texto1">'.pg_fetch_result($rsDet,0,"\"r_pb_vpt07\"").'</td>
  </tr>
  <tr>
    <td class="texto1">Ratio poblac. sin electricidad 2007</td>
    <td class="texto1">'.pg_fetch_result($rsDet,0,"\"r_pb_sel07\"").'</td>
  </tr>
  <tr>
    <td class="texto1">Ratio de la PEPI MIDIS 2012</td>
    <td class="texto1">'.pg_fetch_result($rsDet,0,"\"r_pepi_m12\"").'</td>
  </tr>
  <tr>
    <td class="texto1">Vulnerabilidad al acceso</td>
    <td class="texto1">'.pg_fetch_result($rsDet,0,"\"vuln_acces\"").'</td>
  </tr>
  <tr>
    <td rowspan="6" class="texto1"><b>Utilizaci&oacute;n de alimentos</b></td>
    <td class="texto1">Tasa analfabetismo    mujeres 2007</td>
    <td class="texto1">'.pg_fetch_result($rsDet,0,"\"t_anal_m07\"").'</td>
  </tr>
  <tr>
    <td>Ratio jefes de hogar con primaria incompleta 2007</td>
    <td class="texto1">'.pg_fetch_result($rsDet,0,"\"r_jh_pin07\"").'</td>
  </tr>
  <tr>
    <td class="texto1">Ratio viv sin agua de red ni pilon 2007</td>
    <td class="texto1">'.pg_fetch_result($rsDet,0,"\"r_vsarnp07\"").'</td>
  </tr>
  <tr>
    <td class="texto1">Ratio viv sin desague de red publica 2007</td>
    <td class="texto1">'.pg_fetch_result($rsDet,0,"\"r_vsdrp07\"").'</td>
  </tr>
  <tr>
    <td class="texto1">Ratio poblac. cocinan con le&ntilde;a y otros 2007</td>
    <td class="texto1">'.pg_fetch_result($rsDet,0,"\"r_pb_clo07\"").'</td>
  </tr>
  <tr>
    <td class="texto1">Vulnerabilidad a la utilizaci&oacute;n</td>
    <td class="texto1">'.pg_fetch_result($rsDet,0,"\"vuln_util\"").'</td>
  </tr>
  <tr>
    <td rowspan="3" class="texto1"><b>Institucionalidad</b></td>
    <td class="texto1">Brecha Indice gesti&oacute;n    GL 2014</td>
    <td class="texto1">'.pg_fetch_result($rsDet,0,"\"b_ig_gl14\"").'</td>
  </tr>
  <tr>
    <td class="texto1">Brecha Indice de densidad del estado 2012</td>
    <td class="texto1">'.pg_fetch_result($rsDet,0,"\"b_ide_e_12\"").'</td>
  </tr>
  <tr>
    <td class="texto1">Vulnerabilidad a la institucionalidad</td>
    <td class="texto1">'.pg_fetch_result($rsDet,0,"\"vuln_inst\"").'</td>
  </tr>
  <tr>
    <td class="titulo1" colspan="2">&Iacute;ndice de recurrencia FFNN 2004-2014</td>
    <td class="titulo1">'.pg_fetch_result($rsDet,0,"\"irfn_04_14\"").'</td>
  </tr>');
	print"</tbody></table>";
		
?>
				</div></div>
			</td>
		  </tr>

		</table>
		<?php print "<br><table width='100%' class='fuente_general'><tr>
			<td><b>Fuente :</b></br>".pg_fetch_result($rsDet,0,"\"fuente\"");
			
			echo('...(Descarga estudio <a href="../../sayhuite_repositorio/PDF/PMA_MAPA_DE_VULNARABILIDAD_BAJA.pdf" target="blank"><img src="imajes/descargar.jpg" border ="0" alt="PMA" width="12px"></a>)');
			
			
			print"</td>
		</tr></table><br>";?>
		<?php include('indicadores_socioeconomicos_distrito.phtml');?>
		
	<?php
	$name=$titulo_ventana;
	$capa='consulta_pma_fenomenos_dist_ia2015';
	if (!isset($_GET['excel'])) {
		$ruta=$capa.'.phtml?excel=excel&capa='.$capa.'&ovalor='.$pvalor;
		include 'inc/consulta_pie.php';
	}
	if (isset($_SESSION['usuario'])) {
		grabar_log_accesos('ingreso', $cod_user, $name, $descripcion);
	}
	?>
		</td></tr>
	</table>
	</td></tr>
</table>
</body> 
<script language="javascript" type="text/javascript">
	$(document).ready(function(){
		$("#u1").h2c_acordeon();
		$("#u2").h2c_acordeon();
		$("#u3").h2c_acordeon();
		$("#u4").h2c_acordeon();
		$("#u5").h2c_acordeon();
		$("#u6").h2c_acordeon();
	});
</script>
</html>
<?php include_once("./analyticstracking.php");?>