
<?php

if (isset($_GET['excel']) && ($_GET['excel']=='excel')){
	header("Content-type:application/x-msexcel");
	$file=$_GET['capa'];
	header("Content-Disposition: attachment; filename=".$file.".xls");
	$imgtitulo='';
} else{
	$imgtitulo='<img src="imajes/desplegable.png" width="11" height="11">';
}

/*@session_start();
	if(empty($_SESSION['usuario'])){
        header('Location: ../index.php');
	}else{$cod_user = $_SESSION['usuario'];}*/
	include ('conexion_postgres.phtml');
	include ('injection/funciones.php');
	$player = limpiarCadena($_GET['olayer']);
	$pcampo = limpiarCadena($_GET['ocampo']);
	$pvalor = limpiarNumeros($_GET['ovalor']);
	$linkPG = Conectarse_POSTGRES();
	// Browse Data
	$sQueryS = "SELECT *";
	$sQueryF = " FROM peru_cuenca_petrol_riesgos";
	$sQueryW = " WHERE gid = '" . $pvalor . "'";

	$sQuery = $sQueryS . $sQueryF . $sQueryW;
	$rsDet = pg_query( $linkPG , $sQuery );
	$titulo_ventana = 'CUENCA PETROLERA - RIESGOS DE CONFLICTIVIDAD';
	$titulo = 'CUENCA PETROLERA - RIESGOS DE CONFLICTIVIDAD';
	include ('inc/consulta_cabecera.php');
?>
<table width="100%" border="0" cellspacing="0" cellpadding="10">
  <tr><td>
	<table width="100%" class="marco_general">
	  <tr><td>
		<table width="100%" class="marco_individual">
		  <tr>
			<td>
				<table width="100%" class="titulo_general">
				  <tr>
					<td>&nbsp;&nbsp;UBICACI&Oacute;N GEOGR&Aacute;FICA</td>
				  </tr>
				</table>
				<table width='100%' align='center' class='general'>
					<thead>
					  <tr>
						<th width='20%'>Departamento</th>
						<th width='20%'>Provincia</th>
						<th width='20%'>Distrito</th>
						<th width='20%'>Codigo Distrito</th>
					  </tr>
					</thead>
					<tbody>
					<tr>
						<td align='center' class='texto'><?php echo(pg_fetch_result($rsDet,0,"\"nom_dpto\"")) ?></td>
						<td align='center' class='texto'><?php echo(pg_fetch_result($rsDet,0,"\"nom_prov\"")) ?></td>
						<td align='center' class='texto'><?php echo(pg_fetch_result($rsDet,0,"\"nom_dist\"")) ?></td>
						<td align='center' class='texto'><?php echo(pg_fetch_result($rsDet,0,"\"cod_dist\"")) ?></td>
					</tr>
	
					</tbody>
				</table>
			</td>
		  </tr>
		</table>
		<br>
		<table width="100%" class="marco_individual">
		  <tr>
			<td>
				<table width="100%" class="titulo_general">
					  <tr>
						<td>&nbsp;&nbsp; DATOS GENERALES</td>
					  </tr>
				</table>
			<table width='100%' align='center' class='general'>
		<?php
		print "<tr>
				<td width='50%' class='lista_titulo'>Nombre del Riesgo de Conflictividad:</td>
				<td width='50%' class='texto1'>"
					.pg_fetch_result($rsDet,0,"\"riesg_conf\"").
				"</td>
			  </tr>
			  <tr>
				<td class='lista_titulo'>Descripción del Riesgo:</td>
                <td class='texto1'>"
                    .pg_fetch_result($rsDet,0,"\"descrip1\""). " "
                    .pg_fetch_result($rsDet,0,"\"descrip2\""). " "
                    .pg_fetch_result($rsDet,0,"\"descrip3\"").
                "</td>
			  </tr>

			  <tr>
				<td class='lista_titulo'>Nivel de Riesgo de Conflictividad:</td>
				<td class='texto1'>".pg_fetch_result($rsDet,0,"\"niv_riesg\"")."</td>
			  </tr>
			";
		?>
			</table>
			</td>
		  </tr>
		</table>
		<br>
		
		<table class='fuente_general' width="100%"><thead><tr><th><b>Fuente:</b>
			<br><?php echo pg_fetch_result($rsDet,0,"\"fuente\"");?></th></tr></thead>
		</table>
	<?php
	//$name=strtoupper(pg_fetch_result($rsDet,0,"\"tipoaerona\"").' - '.pg_fetch_result($rsDet,0,"\"label\""));
	$name='CUENCA PETROLERA - RIESGOS DE CONFLICTIVIDAD';
	$capa='consulta_cuenca_petrol';
	if (!isset($_GET['excel'])) {
		$ruta=$capa.'.phtml?excel=excel&capa='.$capa.'&ovalor='.$pvalor.'&olayer=peru_cuenca_petrol'.'&ocampo=gid';
		include 'inc/consulta_pie.php';
	}
	if (isset($_SESSION['usuario'])) {
		grabar_log_accesos('ingreso', $cod_user, $name, $descripcion);
	}
	?>
		</td>
	  </tr>
	</table>
	</td>
  </tr>
</table>
</body>
</html>
<?php include_once("./analyticstracking.php");?>


