<html>

<head>
<meta http-equiv="Content-Script-Type" content="text/javascript" />
 <meta name="description" content="p.mapper - MapServer PHP/MapScript Framework" />
 <meta name="author" content="Armin Burger" />
 <meta name="keywords" content="p.mapper, pmapper, MapServer, PHP, MapScript" />
<body>
 <script src="../usuarios/js/jquery-3.2.1.min.js"></script>
<script src="../usuarios/js/jquery-ui.js"></script>
<script type='text/javascript'>
    
    var j321 = $.noConflict(true);
</script>

<style type='text/css'>


#modal2 {
	display: none;
	position: absolute;
	top: 50%;
	left: 50%;
	overflow: scroll;
	box-sizing: border-box;
	z-index: 5002;
	-moz-transform: translate(-50%, -50%);
	-webkit-transform: translate(-50%, -50%);
	transform: translate(-50%, -50%);
}
#modal-background {
	display: none;
	position: absolute;
	background: #ccc;
	top: 0;
	left: 0;
	width: 100%;
	height: 100%;
	box-sizing: border-box;
	z-index:5001;
	opacity:.75;
	-moz-opacity: 0.75;
	filter: alpha(opacity=75);
}


#modal2.styled {
	width: 55%;
	min-height: 200px;
	min-width: 950px;
	max-height: 550px;
	max-width: 950px;
	overflow: scroll;
	background: #fff;
	padding: 12px 14px;
	border: 1px solid;
	border-color: #aaa #999 #888;
	border-radius: 3px;
	-webkit-border-radius: 3px;
	border-radius: 3px;
	box-shadow: 0 3px 14px -4px #000;
	-ms-box-shadow: 0 3px 14px -4px #000;
	-moz-box-shadow: 0 3px 14px -4px #000;
	-webkit-box-shadow: 0 3px 14px -4px #000;
	box-shadow: 0 3px 14px -4px #000;
}
</style>



<div id="modal-background"></div>

<div id="modal2" class="styled"> <?php
    include 'consulta_capas_definicion.phtml';
?>
	<div align='center'><input type="button" value="Salir" onclick="document.getElementById('modal2').style.display='none';" ></div>
</div>


</body>
</head>
</html>