<!--***************************************************************************************
Organizaci&oacute;n: 	Presidencia del Consejo de Ministros - PCM
Gerencia	: 	Secretar&iacute;a de Descentralizaci&oacute;n
Sistema		: 	Sistema Nacional de Informaci&oacute;n Geogr&aacute;fica - SAYWITE
Coordinador/Desarrollador TIC: Vitaly Uriel Cespedes Reynaga vitalyuri@hotmail.com/vitalyuri@gmail.com/969228151
Periodo		: 	Septiembre 2012 - 2013
***************************************************************************************-->
<style type="text/css">
<!--
.Estilo1 {color: #FFFFFF; font-size: 14px;}
.Estilo2 {font-family: Arial, Helvetica, sans-serif;color: #333333; font-size: 13px; padding-bottom:5px}
-->
</style>
<table width="100%" align="center" class="tabla1">
  <tr>
	<td>
	<table width="100%" align="center" class="tabla2">
	  <tr>
		<td bgcolor="#B86D26"><div align="center" class="Estilo1">WGS84<br>World Geodetic System 84</div></td>
	  </tr>
	  	  <tr>
		<td><div align="justify" class="Estilo2">
		  El WGS84 es un sistema de coordenadas geogr&aacute;ficas mundial que permite localizar cualquier punto de la Tierra (sin necesitar otro de referencia) por medio de tres unidades dadas. WGS84 son las siglas en ingl&eacute;s de World Geodetic System 84 (que significa Sistema Geod&eacute;sico Mundial 1984).</br></br>
		  Se trata de un est&aacute;ndar en geodesia, cartograf&iacute;a, y navegaci&oacute;n, que data de 1984. Tuvo varias revisiones (la &uacute;ltima en 2004), y se considera v&aacute;lido hasta una pr&oacute;xima reuni&oacute;n (a&uacute;n no definida en la p&aacute;gina web oficial de la Agencia de Inteligencia Geoespacial). Se estima un error de c&aacute;lculo menor a 2 cm por lo que es en la que se basa el Sistema de Posicionamiento Global (GPS).<br></br>
		  Consiste en un patr&oacute;n matem&aacute;tico de tres dimensiones que representa la tierra por medio de un elipsoide, un cuerpo geom&eacute;trico m&aacute;s regular que la Tierra, que se denomina WGS 84.<br></br>
		  Mediante Resoluci&oacute;n Jefatural N&#176; 079-2006-IGN-OAJ-DGC, el Instituto Geogr&aacute;fico Nacional (IGN) resolvi&oacute; que para efectos pr&aacute;cticos como elipsoide puede ser utilizado el World Geodetic System 1984 (WGS84).
		</div>
	  </tr>
	</table>
	</td>
  </tr>
</table>
<?php include_once("./analyticstracking.php");?>