version: '3'
services:
  geoperu_reportes:  
    container_name: geoperu-reportes
    restart: always
    image: ""
    volumes:
    - reportes-repository:/var/www/repository
    ports:
      - "8001:8000"
    env_file:
      - docker-compose.prod.env
    # networks:
    # - geoperu
    # logging:
    #   driver: fluentd
    #   options:
    #       fluentd-address: FLUENTD_ADDR