FROM php:7.4-apache as base
RUN apt-get update && apt-get install --no-install-recommends -y libpq-dev \
  && docker-php-ext-configure pgsql -with-pgsql=/usr/local/pgsql \
  && docker-php-ext-install pdo pdo_pgsql pgsql  \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/* \
  && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /usr/share/doc/*

RUN a2enmod rewrite
COPY deployment/container.000-default.conf /etc/apache2/sites-available/000-default.conf
COPY deployment/container.start-apache /usr/local/bin
RUN chmod +x /usr/local/bin/container.start-apache

FROM base as production
COPY . /var/www
RUN chown -R www-data:www-data /var/www

# Default init
CMD ["container.start-apache"] 



