version: '3'
services:
  geoperu_reportes:
    container_name: geoperu_reportes
    restart: always
    build:
      context: .
      target: production
    env_file:
      - docker-compose.prod.env
    volumes:
      - ./repository:/repository_folder
    ports:
      - "8081:8000"
    # environment: 
    #   - DB_HOST=${LOCAL_HOST_IP}
    #   - TZ=America/Lima



