version: '3'
services:
  geoperu_reportes:
    container_name: geoperu_reportes
    restart: always
    build:
      context: .
      target: base
    env_file:
      - docker-compose.prod.env
    volumes:
      - ./:/var/www
    ports:
      - "8081:8000"
    # environment:
    #   - DB_HOST=${LOCAL_HOST_IP}

