<!--***************************************************************************************
Organizaci&oacute;n: 	Presidencia del Consejo de Ministros - PCM
Gerencia	: 	Secretar&iacute;a de Descentralizaci&oacute;n
Sistema		: 	Sistema Nacional de Informaci&oacute;n Geogr&aacute;fica - SAYWITE
Coordinador/Desarrollador TIC: Vitaly Uriel Cespedes Reynaga vitalyuri@hotmail.com/vitalyuri@gmail.com/969228151
Periodo		: 	Septiembre 2012 - 2013
***************************************************************************************-->
<table border="0" align="center">
  <tr>
    <td colspan="5"><div align="center"></div></td>
  </tr>
  <tr>
    <td colspan="2"><img src="programas/imajes/lizzet_quiroz.png"></td>
	
	
    <td width="300" colspan="2"><img src="programas/imajes/donny_chumpitaz.png" /></td>
    <td width="300"><img src="programas/imajes/Vitaly_Cespedes.png"  /></td>
  </tr>
  <tr>
    <td width="300" valign="top"><p>Lizzet Cristina, Quiroz Rodriguez </p>
      <p align="justify"><strong>Coordinadora de la&nbsp; Informaci&oacute;n Geogr&aacute;fica del Sistema Georreferenciado  de la Presidencia del Consejo de Ministros</strong><br/><br/>
        Lizzet posee una amplia experiencia en sistemas de  informaci&oacute;n geogr&aacute;fica, en formulaci&oacute;n y evaluaci&oacute;n de proyectos Ambientales,  Supervisi&oacute;n en Seguridad, Salud y Medio Ambiente, difusi&oacute;n y capacitaci&oacute;n. <br />
    <br/>Lizzet posee el titulo de Ingeniera Ambiental de la  Universidad Federico Villarreal (Lima, Per&uacute;)., egresada de la Maestria en  Gesti&oacute;n y Auditor&iacute;as Ambientales en Ingenier&iacute;a y Tecnolog&iacute;a Ambiental  (FUNIBER), posee diploma en Sistemas Integrados de Gesti&oacute;n de la Calidad, Ambiental,  Seguridad, Salud Ocupacional y Responsabilidad Social</p></td>
    <td width="9" valign="top">&nbsp;</td>
    <td valign="top" width="300"><p>Donny dick Chumpitaz Maldonado </p>
      <p align="justify"><strong>Gestor del  planeamiento, ejecuci&oacute;n y puesta en marcha del Sistema Georreferenciado de</strong><strong> </strong><strong>la Presidencia del Consejo de Ministros</strong><br/><br/>
        Donny posee una amplia experiencia  en gesti&oacute;n de proyectos, implementaci&oacute;n de diagn&oacute;sticos territoriales, planes  de desarrollo y asistencia tecnica para programas de capacitaci&oacute;n en &aacute;reas  urbanas y rurales con enfoque territorial. <br />
    <br/>Donny posee un Master en Project Managment de la Universidad  de La Salle (Barcelona, Espa&ntilde;a), una Magister en Gerencia de Proyectos de ESAN,  egresado de la&nbsp; Maestr&iacute;a de  Administraci&oacute;n y Gerencia Social de la UNFV,posee diplomas en Formulaci&oacute;n de  Proyectos de Inversi&oacute;n P&uacute;blica, Gerencia Pol&iacute;tica, Gobernabilidad y Pol&iacute;ticas  P&uacute;blicas, y un Titulo de Arquitectura de la Universidad Federico Villarreal (Lima,  Per&uacute;). </p></td>
    <td valign="top" width="9">&nbsp;</td>
    <td valign="top" width="300"><p>Vitaly Uriel Cespedes Reynaga </p>
      <p align="justify"><strong>Coordinador</strong><strong> de procesos  de Tecnolog&iacute;as de Informaci&oacute;n del Sistema Georreferenciado de la Presidencia de  Consejo de Ministros.</strong><strong> </strong><br />
<br/>Vitaly posee una amplia experiencia en gesti  &oacute;n de las  tecnologias de informaci&oacute;n y comunicaciones, y mejora de procesos e innovaci&oacute;n  tecnologica. Capaz de Planificar, organizar, dirigir y controlar proyectos de  Sistemas de Informaci&oacute;n y Tecnolog&iacute;as de Informaci&oacute;n exitosos.<br />
    <br/>Vitaly &nbsp;posee el grado  de Bachiller de la carrera de Ingenier&iacute;a de Sistemas realizado en la  Universidad Nacional de Ingenier&iacute;a.&nbsp;  Especialista en Tecnolog&iacute;a de Informaci&oacute;n por la Universidad&nbsp; ESAN. </p></td>
  </tr>
</table>
<?php include_once("./analyticstracking.php");?>